### ISSUE TITLE
Looking for a way to have a stream with debounce cancelled when the base stream is closed

### ISSUE THREAD

**Issue by zoechi** [ReactiveX/rxdart#110]
```dart
    _tickerSubscription = new Observable(onStateChange)
        .doOnDone(() {
          print('done: ${new DateTime.now().second}');
          _tickerSubscription.cancel();
        })
        .debounce(const Duration(seconds: 5))
        .listen((_) {
      print('event: ${new DateTime.now().second}');
        });
```

prints 
```
done: 56
00:00 [32m+29[0m: All tests passed![0m
event: 1
```

This is only an issue when I run it with
```bash
#!/usr/bin/env bash
dart --pause-isolates-on-exit --enable-vm-service=8899 test/all.dart &
sleep 1s
pub global run coverage:collect_coverage --uri=http://localhost:8899 -o coverage/coverage.json --resume-isolates
pub global run coverage:format_coverage --packages=.packages -i coverage/coverage.json -l -o coverage/lcov.info
```
With `pub run test` when "All tests passed!" is printed, there is no dart process hanging around anymore.

I use this in a test with built_redux where I call `store.dispose()` in `tearDown()`

**Comment by zoechi** [comment]
With `--wait-paused` code coverage waits for the debounce timeout to complete, but at least doesn't keep the process open after it's done
```bash
pub global run coverage:collect_coverage --uri=http://localhost:8899 -o coverage/coverage.json --resume-isolates --wait-paused
```

**Comment by brianegan** [comment]
@zoechi I think you've found a bug in our implementation of debounce. Just compared it to RxJS, and found the following:

  - When the base Stream ends, the debounced stream should immediately emit the last item.
  - If the subscription to the debounced stream is cancelled in doOnDone, the debounced stream should not emit any more values.

Does this sound like the behavior you're expecting? If so, I can write up a couple test cases + fix for it.

**Comment by zoechi** [comment]
@brianegan yes, that sounds exactly like what I'm looking for.
