### ISSUE TITLE
The method 'doOnData' isn't defined for the class 'Observable<...>'.

### ISSUE THREAD

**Issue by aubykhan** [ReactiveX/rxdart#114]
I'm getting this error when I try to run the 'flutter' example. It's only 'doOnData' function that's giving this error. Other library functions are just fine.

**Comment by aubykhan** [comment]
I updated the code to use 'call' function and it works now

**Comment by brianegan** [comment]
Oh dang, I need to change the RxDart dependency in that case! The `call` method is deprecated and `doOnData` is indeed the right method to use. Thanks for spotting this!
