### ISSUE TITLE
Has a object which can hold onto multiple observable?

### ISSUE THREAD

**Issue by xiang23** [ReactiveX/rxdart#125]
Just like CompositeDisposable in RxJava

**Comment by frankpepermans** [comment]
There's nothing like that in rxdart, 

It would however be great to bundle n subscriptions and have the ability to cancel or pause in one line, but I feel such a class would better exist outside rxdart, a stream_utils package for example?

**Comment by xiang23** [comment]
OK,Thank you for your answer!

**Comment by zoechi** [comment]
```dart
final _subscriptions = <StreamSubscription>[];
void dispose() => _subscriptions..forEach((ss) => ss.cancel())..clear();
```
should do it.
