### ISSUE TITLE
sink getter on BehaviorSubject and ReplaySubject has different behavior

### ISSUE THREAD

**Issue by frankpepermans** [ReactiveX/rxdart#134]
Adding events to the subject's sink will properly add events to the Stream, but the event is not picked up for the respective use cases of the Subjects.

_For example:_
```
var subject = new BehaviorSubject<int>();

subject.add(1);

expect(subject.value, 1); /// works
```
```
var subject = new BehaviorSubject<int>();

subject.sink.add(1);

expect(subject.value, 1); /// fails!
```
**expected:**
Using sink does not break the Subject like shown above

**Comment by brianegan** [comment]
Fixed by #133
