### ISSUE TITLE
ctr/op wishlist

### ISSUE THREAD

**Issue by frankpepermans** [ReactiveX/rxdart#14]
This issue acts as a priority list for implementing new operators and constructors,
see the full list here: http://reactivex.io/documentation/operators.html

To vote, simply leave a comment which lists the op/ctr names and add a hyperlink to the rx implementation.

For example:
- [ ] `ignoreElements` - http://reactivex.io/documentation/operators/ignoreelements.html

**Comment by brianegan** [comment]
These are two constructors I've used in the Java version that would be handy to have:

  - `concatEager` - like `concat`, but instead of subscribing to each stream sequentially and emitting the results, it runs all streams in parallel and delivers the events in the same order as `concat`.

  - `defer` 
    - http://reactivex.io/documentation/operators/defer.html
    - http://blog.danlew.net/2015/07/23/deferring-observable-code-until-subscription-in-rxjava/

**Comment by brianegan** [comment]
Oh, I just remembered this morning: `switchIfEmpty` is super useful as well.

**Comment by frankpepermans** [comment]
Added defaultIfEmpty!

**Comment by brianegan** [comment]
PRO STYLE!!!!

**Comment by brianegan** [comment]
Another couple:

  - [ ] `empty` constructor - http://reactivex.io/documentation/operators/empty-never-throw.html
  - [ ] `onErrorResumeNext` - http://reactivex.io/documentation/operators/catch.html

**Comment by frankpepermans** [comment]
- [ ] `ignoreElements` constructor - http://reactivex.io/documentation/operators/ignoreelements.html

**Comment by brianegan** [comment]
Did a review of the official operators list from ReactiveX to see where we're. I think we're missing the following features:

  - Never constructor
  - Throw constructor 
  - Range constructor 
  - doOnNext (rename from tap)
  - doOnEach
  - doOnError
  - doOnComplete
  - materialize / dematerialize

**Comment by brianegan** [comment]
- [ ] skipUntil - http://reactivex.io/documentation/operators/skipuntil.html

**Comment by brianegan** [comment]
Two quick ones:

- [ ] zipWith - http://reactivex.io/documentation/operators/zip.html
- [ ] concatWith  - http://reactivex.io/documentation/operators/concat.html

**Comment by brianegan** [comment]
Closing for now as I think we have almost everything covered! If folks feel we're missing anything, they can create individual issues at this point.
