### ISSUE TITLE
rxdart tests fail on a machine with only flutter SDK

### ISSUE THREAD

**Issue by escamoteur** [ReactiveX/rxdart#146]
Hi,

don't know why but I cannot run all tests on the master branch on my machine.
Please find attached the log

All the best 
Thomas
[rxdarttests.log](https://github.com/ReactiveX/rxdart/files/1915846/rxdarttests.log)

**Comment by escamoteur** [comment]
this is my
Dart Version: 

Tools • Dart 2.0.0-dev.43.0.flutter-52afcba3

Flutter 0.2.8 • channel beta

**Comment by frankpepermans** [comment]
No problems here with dev.48

**Comment by brianegan** [comment]
Hey all, this is a funny one. For some reason, even when you use `--preview-dart2-` with the DartVM, it doesn't run in the same mode as `flutter test --preview-dart-2`, which seems to enforce more Runtime type checks.

I can confirm the issue, and It looks like we're running into run-time type errors here with the new Buffer and Window strategies. I'll try to find some time to dig into it a bit more tonight!

**Comment by zoechi** [comment]
There are more flags that can be passed in addition to `--preview-dart-2`. A complete list would be great, but I haven't seen one. I think Flutter passes `--strong` as well. No idea what exactly this changes in addition to `--preview-dart2`.
I only found https://github.com/dart-lang/sdk/blob/3b7199fe639d5591fe5d409a0e9d40b4a8cb360e/runtime/bin/main_options.cc#L72-L76
