### ISSUE TITLE
Inspect pause / resume behavior of Stream classes

### ISSUE THREAD

**Issue by brianegan** [ReactiveX/rxdart#156]
Concat does not pause it's source streams in an `onPause` callback. Other Stream classes (concatEager, combineLatest, etc also fail to handle onPause / onResume).

We should look through these classes and properly implement pause / resume.

**Comment by frankpepermans** [comment]
Argh :/ I'll take a look as well asap

**Comment by frankpepermans** [comment]
track under https://github.com/ReactiveX/rxdart/pull/159

**Comment by brianegan** [comment]
Fixed by #159
