### ISSUE TITLE
[error] The method 'retype' isn't defined for the class 'Stream<T>'

### ISSUE THREAD

**Issue by rich-j** [ReactiveX/rxdart#160]
The deprecated `retype` method was removed as of Dart 2.0.0-dev.62.0 released June 13. Running tests in Chrome using `pub run build_runner test -- -p chrome` now fail at runtime with

    Error compiling dartdevc module:rxdart|lib/futures.ddc.js
  
    [error] The method 'retype' isn't defined for the class 'Stream<T>'. (package:rxdart/src/observable.dart, line 1909, col 33)

If you're not ready to remove the `retype` method from `rxdart` then maybe your implementation of `retype` can be explicitly call `cast`.

**Comment by tobyokeke** [comment]
Upgrading to 0.18.0 worked. Thank you.
