### ISSUE TITLE
Flatmap iterable doesn't emit stream items

### ISSUE THREAD

**Issue by charafau** [ReactiveX/rxdart#162]
I encountered bug while using `flatMapIterable` to transform items in observable

```dart
_items = _query //Stream<List<Item>>
        .flatMap(repository.getItems)
        .flatMapIterable((list) => Observable.just(list))  // if I comment flatmap iterable items are emitted
        .toList()
        .asObservable()
        .asBroadcastStream();  // this never emits items
```

I suspect creating new observable with `Observable.just()` doesn't return items to the stream.

**Comment by brianegan** [comment]
Hey there -- I think you're doing several transformations that all kinda do the same thing.

Would this work:

```dart
query //Stream<List<Item>>
        .flatMapIterable(repository.getItems)
```

If the `repository.getItems` returns a `Stream<List<Item>>`, then `flatMapIterable` will emit each item in the List individually.

Right now, you're doing this, which hopefully shows what's going wrong:

```
_items = _query //Stream<List<Item>>
        .flatMap(repository.getItems) // Get the Stream<List<Item>> and emit each `List<Item>`
        .flatMapIterable((list) => Observable.just(list))  // Convert the List<Item> to emit individual elements. You shouldn't need to use both flatMap and flatMapIterable...
        .toList() // Gathering each item listed and returning a `Future`. If the `_query` Stream never completes, this will not complete! It waits until all items are emitted before returning the List<Item>.
        .asObservable() // Converting the Future into an Observable that emits 1 List<Item>
        .asBroadcastStream();  // This part is fine, if you need to emit these values to multiple listeners
```

**Comment by brianegan** [comment]
@charafau Did this help, or are you still running into trouble?

**Comment by brianegan** [comment]
@charafau Gonna close this out! If I didn't answer the question, or ya feel like I didn't understand the use-case, please feel free to reopen and keep the discussion going :)
