### ISSUE TITLE
Add publish, replay, share, etc

### ISSUE THREAD

**Issue by sir-boformer** [ReactiveX/rxdart#166]
In other Rx implementations, there are various operators to transform a stream into a multicast stream (`share`, `publish`) that automatically subscribes and unsubscribes the source stream (`refCount`) and repeats a certain number of items on subscription (`publishReplay`, `shareReplay`). Is there a way to do this with rxdart or the dart stream api?

The only thing I found is `asBroadcastStream()`. It doesn't replay values, and I'm not sure what happens when all subscribers unsubscribe.

https://www.learnrxjs.io/operators/multicasting/sharereplay.html

https://medium.com/mindorks/how-to-use-rxjava-share-operator-26b08973771a

**Comment by sir-boformer** [comment]
Is the source code publicly available? I'm working on a simple implementation of `shareReplay`, based on the [rxjs implementation](https://github.com/ReactiveX/rxjs/blob/3e4772e44bcd2ffeb12676548abde958379d8024/src/internal/operators/shareReplay.ts) that uses an internal `ReplaySubject`

**Comment by sir-boformer** [comment]
This is what I came up with: https://gist.github.com/sir-boformer/d0518b7b4c832f2384bb3ab1f28bbe67

It's a very poor transformer implementation that can only be used a single time, but seems to work as expected. I'm really looking forward to a proper implementation!

**Comment by brianegan** [comment]
Nice one! It's got a couple of small issues, but it's far simpler than what I've been doing... I've been trying to properly implement the `ConnectableObservable` class from RxJava: http://reactivex.io/RxJava/javadoc/io/reactivex/observables/ConnectableObservable.html

There are a couple tricky problems with the implementation in Dart -- namely the fact that you can't reconnect to most streams (most streams are Single-Subscription). To be honest, I'd wondered if trying to fulfill the observable spec might not make the most sense there, and if it might make more sense to produce Observables that are better-tailored to the Dart environment.

Overall, I don't have anything that's sharable really -- just some ideas on my local machine.

**Comment by sir-boformer** [comment]
I can see why you are not happy. The dart Streams API really differs from other Rx implementations. Especially the fact that you can't reuse a simple stream changes a lot. I hit that problem last night and it forces my to rethink the whole architecture that I'm successfully using on other platforms.

I updated my gist a little bit so that it also handles error and completion events

**Comment by brianegan** [comment]
Gonna slightly rename this one so we're tracking it properly

**Comment by brianegan** [comment]
Hey there -- Took a bit of work, but think I have something in place. Could you please check out #182 and let me know whatcha think?
