### ISSUE TITLE
Add debounce operator with durationSelector

### ISSUE THREAD

**Issue by sir-boformer** [ReactiveX/rxdart#168]
Right now rxdart only supports debouncing with a fixed duration, it would be great to have more control:

```dart
obs.debounceSelector((String event) {
  if(event == 'important') {
    return Observable.empty(); // forward immediately
  }
  else {
    return Observable.timer(null, Duration(seconds: 5)); // debounce 5 seconds
  }
});
````

In rxjs: http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-debounce
(some more discussion: https://github.com/ReactiveX/rxjs/issues/493)

In RxJava: http://reactivex.io/RxJava/javadoc/io/reactivex/Observable.html#debounce-io.reactivex.functions.Function-

**Comment by frankpepermans** [comment]
Hi there! Yup that sure has some use cases, we do in fact have some samplers already, for buffer and window, see also https://github.com/ReactiveX/rxdart/blob/master/lib/src/samplers/buffer_strategy.dart

We could expand this to more ops as we go

**Comment by frankpepermans** [comment]
see https://github.com/ReactiveX/rxdart/pull/249/
