### ISSUE TITLE
BehaviorSubject onCancel incompatible with StreamController

### ISSUE THREAD

**Issue by mjohnsullivan** [ReactiveX/rxdart#172]
I tried to swap out a broadcast StreamController with BehaviorSubject, but hit issues as oinCancel for StreamController takes () => Void, but BehaviorSubject takes () => Future<dynamic>. This lead to less than optimal code for the onCancel function:

  Future<Null> _onCancelFunc() {
    // Do sync stuff here
    return null;
  }

The docs suggest that void is a valid option: The callback may return either void or a future.

**Comment by brianegan** [comment]
Ah, you're totally right. I'll push up a fix for that!

Thanks for the report :)
