### ISSUE TITLE
What happened to the forkJoin operator?

### ISSUE THREAD

**Issue by jonsamwell** [ReactiveX/rxdart#173]
Hi,

I see there was a commit quite some time ago adding the forkJoin operator (https://github.com/ReactiveX/rxdart/commit/38eb65577215724bc8429f69c11df1905e9553cc) but now I can't find it.  Is there any plans to add this back in or is there a new preferred way to combine multiple streams and wait for the last emitted event?

Thanks,

Jon

**Comment by jonsamwell** [comment]
@brianegan thanks for this.  

The only reason I can see to add it would be to help people who are unfamiliar with DartRx but have experience with other Rx implementations.

**Comment by zoechi** [comment]
I'd say listing `forkJoin` in the README.md with a comment how to do it in Dart should be enough in this case.

**Comment by frankpepermans** [comment]
see: https://github.com/ReactiveX/rxdart/issues/173
