### ISSUE TITLE
Throttle: configure leading/trailing events

### ISSUE THREAD

**Issue by greglittlefield-wf** [ReactiveX/rxdart#175]
It would be very useful to be able to configure `ThrottleStreamTransformer` to emit trailing events, as is possible in the JS implementation: https://rxjs-dev.firebaseapp.com/api/operators/throttle

**Comment by brianegan** [comment]
Thanks! Good call -- we can definitely add this.

**Comment by frankpepermans** [comment]
see https://github.com/ReactiveX/rxdart/pull/249/
