### ISSUE TITLE
Does this works on websocket?

### ISSUE THREAD

**Issue by jinfagang** [ReactiveX/rxdart#178]
I have some problem in original dart stream, it will recieved msg again and again when the screen switchs between each other. Does rx can replace stream in websocket?

**Comment by frankpepermans** [comment]
Hi there!

Dart's rx implementation builds upon the standard dart streams, they do not replace them.

Can you be more specific as to what is not working for you? Perhaps share some code?

**Comment by brianegan** [comment]
Gonna go ahead and close this out since there hasn't been a response in a while. Please feel free to write us again if you need more help!
