### ISSUE TITLE
Migrate to ReactiveX?

### ISSUE THREAD

**Issue by brianegan** [ReactiveX/rxdart#18]
Hey, as this project becomes more and more complete (thanks so much for your hard work!), I was wondering if it made sense to potentially move it under the ReactiveX umbrella (https://github.com/ReactiveX)? 

That way it could have more "official" weight as a project, and wouldn't feel like a project so tied to a single maintainer?

Just some food for thought, thanks again!

**Comment by frankpepermans** [comment]
Definitely, there's a PR which greatly improves the readme, once that is merged, I'll ping reactivex to come have a look and go from there

**Comment by frankpepermans** [comment]
We've reached to reactivex.io, will keep this issue updated with their feedback

**Comment by mattpodwysocki** [comment]
@frankpepermans yes, let's go ahead and move it over.  I'll work on getting you permissions

**Comment by frankpepermans** [comment]
@mattpodwysocki sure, no problem. Would it suffice to make you collaborator or do I need to transfer ownership? I believe an admin option is only possible for Github organizations?

**Comment by mattpodwysocki** [comment]
@frankpepermans if you can make me an admin that would work so I could move it over.  Did you get the invite to join the org?

**Comment by frankpepermans** [comment]
Yes thanks got the invite. I'll proceed with transferring the repo to you

**Comment by dotdotcommadot** [comment]
Thanks @mattpodwysocki !!

**Comment by frankpepermans** [comment]
Great work guys!
