### ISSUE TITLE
New Observable constructor

### ISSUE THREAD

**Issue by long1eu** [ReactiveX/rxdart#185]
What do you think about this constructor similar to rxjs?

```
 typedef VoidFunc CreateStream<T>(StreamController<T> subscription);

  factory Observable.create(CreateStream<T> createStream) {
    final StreamController<T> controller = StreamController<T>();
    controller.onListen = () => controller.onCancel = createStream(controller);

    return Observable<T>(controller.stream);
  }
```

**Comment by brianegan** [comment]
Hey there -- yah, we could definitely do something like this. I think it'd make sense to only pass the `EventSink<T>` rather than the StreamController to the function if we did this, since `EventSink` ~= `Observer`.

**Comment by long1eu** [comment]
should I make a PR?

**Comment by brianegan** [comment]
Sure thing! Before we do that, could you describe your use-case for this a bit more?

A couple of things I was thinking about:

  1. Would the controller ever be sync?
  2. What about broadcast Streams? Should this only create single-subscription streams?
  3. How would async work inside this function? A lot of times `create` is used to convert a normal async process into a Stream-based process. But the function couldn't be marked `async`, or it'd need to return a `FutureOr<Stream<T>>`.

**Comment by brianegan** [comment]
Gonna close this out for now. We haven't had too many more requests for this functionality, and the same functionality can be achieved with a normal `StreamController` or `PublishSubject`. If you feel strongly, please reopen :)

**Comment by Elias8** [comment]
I wanted the same thing  for transforming socket io callbacks to Observable and what I did is this

`class CustomObservable<T> extends Stream<T> {
  Stream<T> _stream;

  CustomObservable(this._stream);

  factory CustomObservable.create(Observer<T> observer) {
    StreamController<T> streamController = StreamController();

    observer(streamController);

    return CustomObservable(streamController.stream);
  }

  @override
  StreamSubscription<T> listen(void Function(T event) onData,
      {Function onError, void Function() onDone, bool cancelOnError}) {
    return _stream.listen(
      onData,
      onDone: onDone,
      onError: onError,
      cancelOnError: cancelOnError,
    );
  }
}`
any improvements please!
Thanks.

**Comment by Elias8** [comment]
I wanted the same thing  for transforming socket io callbacks to Observable and what I did is this
`typedef void Observer<T>(StreamController<T> observer);

class CustomObservable<T> extends Stream<T> {
  Stream<T> _stream;

  CustomObservable(this._stream);

  factory CustomObservable.create(Observer<T> observer) {
    StreamController<T> streamController = StreamController();
    observer(streamController);
    return CustomObservable(streamController.stream);
  }

  @override
  StreamSubscription<T> listen(void Function(T event) onData,
      {Function onError, void Function() onDone, bool cancelOnError}) {
    return _stream.listen(
      onData,
      onDone: onDone,
      onError: onError,
      cancelOnError: cancelOnError,
    );
  }
}`
any improvements, please!
Thanks.

**Comment by Elias8** [comment]
I wanted the same thing for transforming socket io callbacks to Observable and what I did is this

`typedef void Observer<T>(StreamController<T> observer);

class CustomObservable<T> extends Stream<T> {
  Stream<T> _stream;

  CustomObservable(this._stream);

  factory CustomObservable.create(Observer<T> observer) {
    StreamController<T> streamController = StreamController();

    observer(streamController);

    return CustomObservable(streamController.stream);
  }

  @override
  StreamSubscription<T> listen(void Function(T event) onData,
      {Function onError, void Function() onDone, bool cancelOnError}) {
    return _stream.listen(
      onData,
      onDone: onDone,
      onError: onError,
      cancelOnError: cancelOnError,
    );
  }
}`         
`
any improvements, please!
Thanks.

**Comment by Elias8** [comment]
I wanted the same thing for transforming socket io callbacks to Observable and what I did is this
 ```dart
typedef void Observer<T>(StreamController<T> observer);

class CustomObservable<T> extends Stream<T> {
  Stream<T> _stream;

  CustomObservable(this._stream);

  factory CustomObservable.create(Observer<T> observer) {
    StreamController<T> streamController = StreamController();

    observer(streamController);

    return CustomObservable(streamController.stream);
  }

  @override
  StreamSubscription<T> listen(void Function(T event) onData,
      {Function onError, void Function() onDone, bool cancelOnError}) {
    return _stream.listen(
      onData,
      onDone: onDone,
      onError: onError,
      cancelOnError: cancelOnError,
    );
  }
}
```
any improvements, please!
Thanks.
