### ISSUE TITLE
Forcing exception on observable will also jump to success?

### ISSUE THREAD

**Issue by lordgreg** [ReactiveX/rxdart#194]
I'm currently having issue understanding why am I also coming into success function of `listen`.

I've created a dummy function:
```dart
  Observable<dynamic> doLogin() {
    return Observable.just('COMPLETED')
    .delay(Duration(milliseconds: 2000))
    .timeout(Duration(milliseconds: 500));
  }
```

As you see, it should return success after 2000, but `TimeoutException` triggers after 0.5 seconds.

Subscribing to the function like this:
```dart
_controller.doLogin().asBroadcastStream().listen((success) {
      print('SUCCESS $success');
    }, onDone: () {
      print('DONE')
    }, onError: (err) {
      // ERROR HERE
    });
```

Provides this result:
```
/flutter (28681): ERROR TimeoutException after 0:00:00.500000: No stream event
I/flutter (28681): SUCCESS COMPLETED
I/flutter (28681): DONE
```

So the question I have is, why do I jump to the SUCCESS block if my `doLogin()` function returned exception?

Using `rxdart: ^0.19.0` with:
```
$ flutter --version
Flutter 0.8.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5ab9e70727 (5 weeks ago) • 2018-09-07 12:33:05 -0700
Engine • revision 58a1894a1c
Tools • Dart 2.1.0-dev.3.1.flutter-760a9690c2
```

**Comment by frankpepermans** [comment]
Hi there!

Sorry for the late reply, life is busy :)

The above is actually correct behaviour, in the Dart `Stream` world.
An error is added to the `Stream`, which will enter your `onError` handler, but by default, this doesn't cancel the `Stream` and does not prevent future events from passing.

If you want to stop the subscription on an error, then simply use `cancelOnError` on the `listen`:

```
_controller.doLogin().asBroadcastStream().listen((success) {
      print('SUCCESS $success');
    }, onDone: () {
      print('DONE')
    }, onError: (err) {
      // ERROR HERE
    }, cancelOnError: true );
```

PS: `timeout` is actually a native Dart `Stream` handler, not an rxdart `Stream` transformer

**Comment by lordgreg** [comment]
Hi @frankpepermans and thank you for your response. Hope life is sometimes also easy-going, not busy all the time :)

Please check the code below, because, as far as I understand it, we should jumpt to `onDone`:

```dart
    Observable.just('SOMETHING')
    .delay(Duration(seconds: 2))
    .timeout(Duration(milliseconds: 1))
    .concatMap((_) => Observable.just('YOLO 1337').delay(Duration(seconds: 2)))
    .map((_) {
      print('JOB DONE. $_');
      return _;
    })
    .listen((onData) {
      print('LISTENED: $onData');
    },
    onDone: () => print('ON DONE.'),
    onError: (err) => print('ERR ${err.toString()}'),
    cancelOnError: true);
```

If it would complete:
1. it should go through SOMETHING
2. it should go through YOLO 1337
3. map and return "JOB DONE"

But, we get the TimeoutException, with `cancelOnError`:

What should happen:
1. it should run SOMETHING but timeout exception!
2. it should arrive in ERROR
3. it should arrive in DONE

What happens:
1. it starts in SOMETHING but timeout exception triggers
2. We arrive in ERROR
3. Nothing else happens.


So, there's a bug somewhere. Is it me? :|

**Comment by frankpepermans** [comment]
Heya!

Well at a quick glance, cancelOnError true will just immediately cancel your subscription after the very first error. So it looks correct to me.

The inner observable on concatMap also closes because the parent closes.

**Comment by frankpepermans** [comment]
Do you mean the onDone call, or the job done in map?

Either way, done is meant to complete when all events on the Stream have been emitted.

Since the error cancels the subscription, any future events are not added, so done does not trigger.

**Comment by lordgreg** [comment]
Thank you for your feedback @frankpepermans.

I'm used to jumping in `finalize` pipe (RxJS) even in case one of the observables threw exception. Also, Feature's `whenComplete` triggers at the end of chaining Features, where one Feature throws. 

So there's currently no way (probably same with Streams?) to have single "finally" in which you would arrive in case of success or failure. That just means operations, that have to been called in both ways, have to be called in onDone and onError.

👍
