### ISSUE TITLE
Using .shareValue doesn't work as expected when used on a sync stream

### ISSUE THREAD

**Issue by enyo** [ReactiveX/rxdart#202]
Again, this might be intended behaviour, but I don't understand why this is happening:

```dart
import 'dart:async';
import 'package:rxdart/rxdart.dart';

main() {
  final onToggleCard = new StreamController<int>(sync: true);

  final selectedCards = Observable(onToggleCard.stream)
      .scan<List>((prev, card, i) => prev..add(card), List())
      .asBroadcastStream();

  final selectedCards2 = selectedCards.shareValue(seedValue: List());

  selectedCards.listen((cards) => print('Selected  $cards'));
  selectedCards2.listen((cards) => print('Selected2  $cards'));

  [1, 2, 3, 4, 5, 6, 7, 8, 9].forEach(onToggleCard.add);
}
```

I would assume that `selectedCards` and `selectedCards2` would emit the same values, but this is the output:

```
Selected  [1]
Selected  [1, 2]
Selected  [1, 2, 3]
Selected  [1, 2, 3, 4]
Selected  [1, 2, 3, 4, 5]
Selected  [1, 2, 3, 4, 5, 6]
Selected  [1, 2, 3, 4, 5, 6, 7]
Selected  [1, 2, 3, 4, 5, 6, 7, 8]
Selected  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Selected2  []
Selected2  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Selected2  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Selected2  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Selected2  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Selected2  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Selected2  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Selected2  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Selected2  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Selected2  [1, 2, 3, 4, 5, 6, 7, 8, 9]
```

**Comment by brianegan** [comment]
Thanks for the report! Unfortunately, we had to kind of hack BehaviorSubject to make it work, and it looks like it broke this use-case.

I'll investigate some potential fixes!

**Comment by enyo** [comment]
I see, that makes sense. Thanks for investigating so thoroughly. I guess that in combination with this problem it makes sense to follow the reactive programming best practices and only work with immutable objects then.

**Comment by brianegan** [comment]
Yah, I think that's the only way to get this work work unfortunately. I wish Streams could be truly sync, but there are just some fundamental pieces of the Stream API that mean we can't guarantee they always will be. Kind of a shame, but it's what we've got!
