### ISSUE TITLE
Notice that something new is added to ValueObservable

### ISSUE THREAD

**Issue by tsuba3** [ReactiveX/rxdart#204]
I use ValueObservable in Flutter development with BLoC pattern.
For testing, I want to cast a ValueObservable as a single-subscription stream, or detect that the bloc
add something new into a ValueObservable.

For example:
```dart
bloc.submit();
await expectLater(bloc.isSubmitting, emits(true));
await expectLater(bloc.isSubmitting, emits(false)); // Actually emits true
```

**Comment by brianegan** [comment]
Hey there -- in this case, rather than doing two separate assertions on the same stream, it's usually easier to use the `emitsInOrder` operator, so you don't run into timing issues like this.

E.g.

```dart
bloc.submit();
expect(bloc.isSubmitting, emitsInOrder([true, false]);
```

**Comment by brianegan** [comment]
Heya @tsuba3, gonna close this out for now, but let let me know if my suggestion didn't work for ya!
