### ISSUE TITLE
feature request pairwise

### ISSUE THREAD

**Issue by zoechi** [ReactiveX/rxdart#205]
https://www.learnrxjs.io/operators/combination/pairwise.html

I think that would solve https://stackoverflow.com/questions/53675041/flutter-streams-how-to-access-previously-emitted-data-from-the-stream

I found it handy in some Angular TS situations.

**Comment by frankpepermans** [comment]
At first glance, it looks a lot like bufferCount(2, 1).

I'll have a closer look later :)

**Comment by frankpepermans** [comment]
see https://github.com/ReactiveX/rxdart/pull/210

**Comment by Shantanu-Kotambkar** [comment]
@zoechi How would this solve my question on StackOverflow. https://stackoverflow.com/questions/53675041/flutter-streams-how-to-access-previously-emitted-data-from-the-stream

**Comment by zoechi** [comment]
With each event you get the new value and the previous value.
If `[1, 2, 3, 4, 5]` are emitted one by one to the stream, pairwise would emit
`[1, null]`, `[2, 1]`, `[3, 2]`, `[4, 3]`, `[5, 4]`.
Is this not what you want?

**Comment by Shantanu-Kotambkar** [comment]
Yes it is what i want, i just don't know how to use this. I was dealing with ReplaySubject, which isn't working for me. If you could answer my question on StackOverflow with a sample example, it would be just great!

**Comment by zoechi** [comment]
It does not exist yet. `bufferCount` ;(nstead of pairwise) should do that when #210 is merged and an update published to pub.

**Comment by zoechi** [comment]
A self-contained running example would probably be helpful to diagnose. 
The maintainers here know much more about that than me anyway.

**Comment by frankpepermans** [comment]
For ReplaySubject, it always helps to check out the tests: https://github.com/ReactiveX/rxdart/blob/master/test/subject/replay_subject_test.dart

**Comment by frankpepermans** [comment]
fixed in 0.20.0
