### ISSUE TITLE
Infinite combineLatest

### ISSUE THREAD

**Issue by mig35** [ReactiveX/rxdart#212]
So the request is to create an combineLatest implementation with a list of streams without 9 streams limitation.

**Comment by mig35** [comment]
wow, thanks, haven't seen this.
when do you think it will be available? I've created my own version, but prefer yours in the lib and not custom one.

**Comment by frankpepermans** [comment]
pretty soon, we have a few PR's open which will be bundled into a new release, sometime this week :)
