### ISSUE TITLE
Create more examples

### ISSUE THREAD

**Issue by dotdotcommadot** [ReactiveX/rxdart#22]
More examples are needed for this API.
I think one example this library really needs is something that explains the transition from Dart Streams (since this API isn't documented that well) to RxDart Obserbables.

**Comment by brianegan** [comment]
+1 -- I wonder if we can simply copy the examples from the RxJS docs and simply adapt them. I'll add a bunch of examples in the code this weekend!

**Comment by brianegan** [comment]
Update: Worked more on refactors the past weekend or so, gonna finish up operators / tests and then document after.
