### ISSUE TITLE
dart 2.1

### ISSUE THREAD

**Issue by JCzz** [ReactiveX/rxdart#222]
Do you know when rxdart will support dart 2.1?

**Comment by JCzz** [comment]
Ahh, just saw this: https://github.com/flutter/flutter/issues/21421

**Comment by frankpepermans** [comment]
rxdart should already support 2.1, what seems to be the issue?

**Comment by JCzz** [comment]
Hi Frank

I get the following:

pub get
Resolving dependencies...
The current Dart SDK version is 2.1.0.

```
Because rxdart depends on browser >=0.3.1+1 which requires SDK version <2.0.0, version solving failed.
exit code 1
```

Just tried to add 2.1 to pubspec.yaml:

```
name: rxdart
version: 0.16.7
authors:
- Frank Pepermans <frank@igindo.com>
- Brian Egan <brian@brianegan.com>
description: RxDart is an implementation of the popular reactiveX api for asynchronous programming, leveraging the native Dart Streams api.
homepage: https://github.com/ReactiveX/rxdart
environment:
  sdk: '>=2.1.0-dev <3.0.0'
dev_dependencies:-
  browser: ^0.10.0+2
  test: ^0.12.34
  benchmark_harness: ">=1.0.0 <2.0.0"
  coverage: ^0.9.2
  stack_trace: "^1.9.2"
web:
  compiler:
    debug: dartdevc

```

I will look for a news version for browser...

**Comment by frankpepermans** [comment]
browser is no longer supported in Dart 2.0

You seem to be targetting rxdart version 0.16.7, but we're already on 0.20.0 now, please update your rxdart dependency to the latest

**Comment by JCzz** [comment]
Ahh sorry, moving fast you guys :-)

Thanks I will let you know even it probably works then.

**Comment by brianegan** [comment]
Perfect! Glad it worked out :)
