### ISSUE TITLE
RFC: HydratedSubject

### ISSUE THREAD

**Issue by lukepighetti** [ReactiveX/rxdart#224]
Hello! I extended BehaviorSubject to persist to local storage on Flutter with `shared_preferences`

The class is here https://github.com/lukepighetti/hydrated/blob/master/lib/hydrated.dart

And the test suite is here https://github.com/lukepighetti/hydrated/blob/master/test/hydrated_test.dart

Is this something you would like added to rxdart? Does it have a place in this package? I published it separately because it is Flutter specific.

Just looking for comment. Cheers!

**Comment by frankpepermans** [comment]
Heya!

Unfortunately we cannot accept Flutter-specific code in our lib (which is enforced  by the shared_preferences import here). 

A utility lib is certainly an option though, i.e. rxdart_flutter, which is something we can consider at some point :)

**Comment by lukepighetti** [comment]
No problem at all!
