### ISSUE TITLE
Interval operator

### ISSUE THREAD

**Issue by timrijckaert** [ReactiveX/rxdart#225]
I'm used to working with RxJava and I'm missing the [interval](http://reactivex.io/RxJava/javadoc/io/reactivex/Flowable.html#interval-long-long-java.util.concurrent.TimeUnit-) operator.
As a replacement I tried `Observable.periodic`, but it has no `initialDelay` argument.

Any workarounds or possibility of a feature request?

Thanks

**Comment by frankpepermans** [comment]
Hi there, sure we can consider adding this, if you need a workaround, try the follwing:

```
Stream<bool> myInterval(Duration delay, {Duration initialDelay}) async* {
    if (initialDelay != null) {
        yield await Future.delayed(initialDelay).then((_) => true);
    } else {
        yield await Future.delayed(delay).then((_) => true);
    }

    yield* myInterval(delay);
}
```

**Comment by hoc081098** [comment]
Can use `concat`, `timer` and `ignoreElements`
```dart
Rx.concat<int>([
  Rx.timer(0, initialDelay).ignoreElements(),
  Stream.periodic(period, (i) => i),
])
```
