### ISSUE TITLE
BehaviorSubject disregards Exception and gives back last valid value when listend to. Intended?

### ISSUE THREAD

**Issue by JSANL** [ReactiveX/rxdart#227]
In my flutter application I have a bloc. It not only sends data with a `BehaviorSubject`, but also exceptions (per `stream.addError()`), which I want to handle in the "front-end" by showing certain error messages to the user.

Let's say this is the bloc output:
- Output 1: valid event.
- Output 2: valid event.
- Output 3: Exception.

Now if I listen to the Stream after Output 3 was added then I will only receive Output 2 and know nothing about Output 3 (the Exception). In the case of my app Output 2 would reflect an old state and might confuse users.

My way of thinking was that the `BehaviorSubject` would emit the last Output to any new listener disregarding if it is a "normal" value or an `Exception`. So in this example Output 3 instead of Output 2.

Is this intended? If yes I think it should be stated in the documentation.

**Comment by JSANL** [comment]
I tried solving it with a different `BehaviorSubject` emitting `Exception`s and having 2 `StreamBuilder`, first checking the `Exception` stream.
This is obviously not a really nice solution.

**Comment by frankpepermans** [comment]
Fixed in master, soon on pub

**Comment by JSANL** [comment]
Thank you very much! :)
