### ISSUE TITLE
`auditTime`?

### ISSUE THREAD

**Issue by lukepighetti** [ReactiveX/rxdart#239]
I have found that neither `debounce()` nor `throttle()` are appropriate for a live search scenario where a user is typing and search API requests are being dispatched as they type.

`debounce()` doesn't work because with a fast typer it will wait until the very end to fire an event.

`throttle()` doesn't work because it will often fire its last event before the typing is complete.

In rxjs I have used `auditTime()` to great effect. This is a debounce that emits events as it goes. Example

```
input:    ***********-
debounce: -----------*
throttle: *--*--*--*--
audit:    --*--*--*--*
```

Would this be a welcome pull request? If so, should it be called `audit(Duration)`? (I honestly never understood where its name came from.)

**Comment by frankpepermans** [comment]
Not familiar with `auditTime`, looks like a `sample` using a periodic `Stream`?

i.e.

```
Observable(inputStream)
    .sample(Stream.periodic(Duration(seconds: 1));
```

**Comment by lukepighetti** [comment]
That could be equivalent, I will play around with it. (I do like that rxdart has a small api surface area)

**Comment by lukepighetti** [comment]
@frankpepermans It looks like that is equivalent. It seems reasonable to me to not add `audit(Duration)`. If you feel differently let me know and I will make a PR.
