### ISSUE TITLE
Why is BehaviorSubject a factory?

### ISSUE THREAD

**Issue by lukepighetti** [ReactiveX/rxdart#242]
I've been trying to add functionality to BehaviorSubject so that my HydratedSubject class is easier to keep up to date with `rxdart` changes but I cannot find a way to extend BehaviorSubject. In poking around it seems that factory generated classes cannot be extended. 

Why is BehaviorSubject a factory? Is the intent to lock it down? 

I have two options:

1) Copy paste BehaviorSubject and add in my own code. (The current method.)

2) Implement BehaviorSubject and all 121 required methods/properties.

<img width="644" alt="screen shot 2019-02-21 at 10 24 03 pm" src="https://user-images.githubusercontent.com/666539/53217820-900e6e00-3627-11e9-9534-4d6007f502e6.png">

Any insights / recommendations?

**Comment by lukepighetti** [comment]
What I was intending to do, more or less:

```dart
class HydratedSubject<T> extends BehaviorSubject<T> {
  final String _key;
  final Hydrate<T> hydrate;
  final Persist<T> persist;

  HydratedSubject(
    String key, {
    Hydrate<T> hydrate,
    Persist<T> persist,
    T seedValue,
    void onListen(),
    void onCancel(),
    bool sync: false,
  }) : super(
          seedValue: seedValue,
          onListen: onListen,
          onCancel: onCancel,
          sync: sync,
        ) {
    _initialHydrate();
  }

  _initialHydrate() async {
    final prefs = await SharedPreferences.getInstance();
    final value = prefs.getString(this._key);
    add(hydrate(value));
  }

  _persist(T event) async {
    final prefs = await SharedPreferences.getInstance();
    prefs.setString(_key, event as String);
  }

  @override
  onAdd(T event) {
    _persist(event);
    super.onAdd(event);
  }
}
```

**Comment by frankpepermans** [comment]
Using a factory allows us to call the *actual* `constructor` with `final` arguments, we create the `controller` inside the factory method, and then pass it to the private constructor so that it becomes a class final property.

Of course this doesn't help you any further :)

Did you try to just `extend Subject` *and* `implement ValueObservable` instead of `extend BehaviorSubject`?

You could then create your own factory, where you return a `BehaviorSubject`?

(i.e. basically do what the `BehaviorSubject` class does)

**Comment by lukepighetti** [comment]
@frankpepermans Thanks for discussing, this should probably be a stack question, so if there's a better place to do this please let me know.

I have been thru the ringer trying to nail this down. Here is my latest attempt given your feedback.

```dart
typedef Hydrate<T> = T Function(String value);
typedef Persist<T> = String Function(T value);

class HydratedSubject<T> extends BehaviorSubject<T> {
  factory HydratedSubject(
    String key, {
    Hydrate<T> hydrate,
    Persist<T> persist,
    T seedValue,
  }) {
    /// The BehaviorSubjet we are wrapping
    final _subject = BehaviorSubject(seedValue: seedValue);

    /// Persist every event
    _subject.listen((val) => _handlePersist<T>(key, persist, val));

    /// Hydrate on creation
    _handleHydrate(key, hydrate).then(_subject.add);

    return _subject;
  }

  static Future<T> _handleHydrate<T>(String key, Hydrate<T> hydrate) async {
    // ...
  }

  static _handlePersist<T>(String key, Persist<T> persist, T val) async {
    // ...
  }
}

```

I get a `type 'BehaviorSubject<SerializedClass>' is not a subtype of type 'HydratedSubject<SerializedClass>'` error when attempting to return a BehaviorSubject

**Comment by lukepighetti** [comment]
Hey guys, I'm looking through the source and BehaviorSubject has gotten a lot more complex since switching to seeded/not-seeded, is there a long term game plan here? rxdart source was a lot more svelte last time I looked and the functionality hasn't seemed to have changed much.

**Comment by frankpepermans** [comment]
Hi Luke, not much has changed really, we needed a separate contructor because in the past, it was impossible to seed with a null value.

**Comment by lukepighetti** [comment]
Yeah, I can see how that would be an issue.
