### ISSUE TITLE
ScanStreamTransformer is not working simultaneously

### ISSUE THREAD

**Issue by afnx** [ReactiveX/rxdart#244]
I'm trying to transfer data from one stream to another. I need to get the data from the second stream right after I added it to the first stream. However, it takes too long time to receive data from the second stream for some reason. Is this behavior expected? Am I doing something wrong?

The reproduction is here:

```dart
void main() {
  test('testScanStreamTransformer', () async {
    final menu = BehaviorSubject<Map<String, String>>();
    final food = PublishSubject<String>();

    food.stream
        .transform(ScanStreamTransformer(
          (Map<String, String> menu, String food, index) {
            menu[food] = food;
            return menu;
          },
          <String, String>{},
        ))
        .pipe(menu);

    food.sink.add('pizza');

    expect(menu?.value?.values?.first ?? '', 'pizza');
  });
}
```

**Comment by frankpepermans** [comment]
`Stream`s are async by default, your test expects the event to be added immediately instead.

Try using `expectLater` instead, or if you really require an immediate push, use `PublishSubject(sync: true)` and `BehaviorSubject(sync: true)` (although I wouldn't recommend this)

**Comment by frankpepermans** [comment]
for example do:

```
test('testScanStreamTransformer', () async {
    final menu = BehaviorSubject<Map<String, String>>();
    final food = PublishSubject<String>();

    food.stream
        .transform(ScanStreamTransformer(
          (Map<String, String> menu, String food, index) {
            menu[food] = food;
            return menu;
          },
          <String, String>{},
        ))
        .pipe(menu);

    food.sink.add('pizza');

    await expectLater(menu,
        emits((Map<String, String> value) => value.values.first == 'pizza'));
  });
```

**Comment by afnx** [comment]
Thank you for your reply, but I need to do pagination in my case. For example, I push 10 different foods to the first stream, which I received from the server. Then, I will need to get the latest data from the second stream to find out where I will start for the next query. If I miss some data, I might query the same data again.

When I use `BehaviorSubject(sync: true)`, it works like I need. What are disadvantages of using it in this way?

**Comment by frankpepermans** [comment]
It's just dangerous in my opinion, your code only works when your Stream is synchronous.
This might have a cascading effect on the rest of your code.

Perhaps we need to build a good pagination example?

Closing, if you feel it should be reopened, feel free
