### ISSUE TITLE
CombineLastest with Iterable of 1 item.

### ISSUE THREAD

**Issue by basketball-ico** [ReactiveX/rxdart#255]
Hello, when I use `Observable<R>.combineLatest<T, R>` and I pass a list with 1 element, I got a error that my list need minimum 2 elements, how can I solve this with the less code.
I use to combine a dynamic number of Streams, but sometimes the list of Stream have only 1 stream, and also I want to apply the `<R> combiner`.
thanks

**Comment by brianegan** [comment]
Oh dang, thanks for catching that! We used to have that check in place before we provided the `combineLatest` method which worked on any list. It used to be only `combineLatest2`, `combineLatest3`, etc.

Now, that check is a bug! I've pushed a PR to fix it: #256

**Comment by basketball-ico** [comment]
Awesome, now I can refactor :D.
Thanks 👍

**Comment by frankpepermans** [comment]
Merged!

**Comment by basketball-ico** [comment]
@frankpepermans hello, sorry, how can I get this update via PUB ?

**Comment by brianegan** [comment]
Heya @basketball-ico -- We're working on a few different updates for the next version and I'd imagine we'll ship this week!

If ya need the commit ASAP, you can use git dependencies: https://www.dartlang.org/tools/pub/dependencies#git-packages
