### ISSUE TITLE
import question

### ISSUE THREAD

**Issue by geoffreylzf** [ReactiveX/rxdart#258]
Hi, I am using BehaviorSubject in rxdart, 
when I want to import the package,
I get 2 option

import 'package:rxdart/rxdart.dart';
import 'package:rxdart/subjects.dart';

which one should I use?

**Comment by frankpepermans** [comment]
Well that's entirely up to you,

rxdart is the full monty,
whereas subjects is, just the subjects.

If you plan to use many rxdart features, then use the first import.

Note: Dart will tree-shake when you compile, so no need to worry about code bloat when using the full import.
