### ISSUE TITLE
Potential Issue w/BehaviorSubject Replaying Errors After Close

### ISSUE THREAD

**Issue by rkunboxed** [ReactiveX/rxdart#260]
I ran into an issue recently while using `addError` with `BehaviorSubject`. I found that if an error is added to the stream and then I navigate away from the view using a button calling `Navigator.of(context).popAndPushNamed('/');` or the back button on the Android emulator (I did not test on a real device.) I get the following error: 

> [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: Cannot add new events after calling close

I do not get the same error when navigating away after data is added to the stream or when navigating away via `popAndPushNamed` in a scaffold drawer. 

Lastly, I only see this error if I call `drain()` as well as `close()` in my bloc's `dispose()` method. It won't surface when using just `close()`.

I have a bunch of code to show but it's probably easiest to just see it in action in a full sample app. You can find it here: https://github.com/rkunboxed/behaviorsubject-error-navigation-bug

Use the drawer to navigate to "Cool Stuff". Then use the buttons to either add data or an error to the stream. Then navigate away.

**Comment by frankpepermans** [comment]
Hiya, can you test to see if this also happens when using a regular `StreamController.broadcast()`, instead of a `BehaviorSubject`?

**Comment by rkunboxed** [comment]
Sure thing. I'll give it a shot and report back.

**Comment by rkunboxed** [comment]
It does not happen with `StreamController.broadcast()`. I pushed branch `streamcontroller-test` with that test to the repo above.
