### ISSUE TITLE
Subject doesn't keep reference of the StreamSubscription in addStream

### ISSUE THREAD

**Issue by Koridev** [ReactiveX/rxdart#263]
It is not possible to get a reference to the `StreamSubscription` created by `source.listen` in the `Subject.addStream` method.

In my case, using flutter firestore and BehaviorSubject together, I have no way to close my stream and stop receiving events without adding a layer in between.

It is easy to make a wrapper around the `BehaviorSubject` to keeps a reference to the `StreamSubscription` and feeds the data through `Subject.add`, but it is redundant and make the `addStream` method feel incomplete.

**Comment by frankpepermans** [comment]
Hi there, we simply wrap `addStream`, which is actually part of the Dart SDK async library.
I'm not 100% sure about this, but I think that if the added `Stream` is *not* a broadcast `Stream`, then calling `cancel` will also cancel the added `Stream`.

With broadcast `Streams`, I'd assume this is not the case.

**Comment by AndruByrne** [comment]
@Koridev might Observable.pipe be of assistance to you? It will close the subject after the stream has completed and you get a Future for that event.

**Comment by brianegan** [comment]
Unfortunately, as previously mentioned, we simply defer to the standard `StreamController` behavior in this case which does not keep a list of these subscriptions that you can access, they are only managed internally to the private `_BroadcastStreamController` class. If you `close` the subject, 

If you need to control when you add items to a StreamController and when you stop, listening to the source stream and manually managing the Subscriptions manually is the best way to go.
