### ISSUE TITLE
BehaviorSubject does not emit last value on Flutter iOS, but does so on Android

### ISSUE THREAD

**Issue by martin-fink** [ReactiveX/rxdart#265]
First of all - sorry if this is unrelated to this repository, and if I should rather post this issue in the flutter repo.

I am building a Flutter app and have run into the following issue. Following the BLoC pattern, my code is structured like this:

BLoC:

```dart
class Bloc {
  final _subject = BehaviourSubject<Data>;

  Observable<Data> get stream => _subject.stream;

  void load() async {
    _subject.sink.add(Data.loading());
    final data = await /* ... */;
    _subject.sink.add(Data.success(data));
  }
}
```

State:
```dart
@override
Widget build(BuildContext context) {
  return StreamBuilder<Data>(
    stream: widget.bloc.stream,
    builder: (context, snapshot) {
      print(snapshot);
      if (!snapshot.hasData || snapshot.data.isLoading) {
        return /* loadingindicator */;
      }

      return /* data view */;
    },
  );
}

@override
void initState() {
  super.initState();
  widget.bloc.load();
}

```

On Android, everything works as expected. The build method gets called for
`Data.loading()` and for `Data.success()`.

On iOS, however, I do not receive any data at all (`snapshot.hasdata == false`). I added a button, which on click, listens to the stream and prints
the received value. On Android, I receive the last event, as it is expected with a BehaviorSubject. On iOS, the listen method did not get called.

Button:
```dart
MaterialButton(
  child: Text('Click me'),
  onPressed: () {
    widget.bloc.stream.listen(print); // prints Data.success on Android, nothing on iOS
  },
),
```

Can anyone give me a push in the right direction?

Thanks

**Comment by martin-fink** [comment]
Ok, I've found the problem. As SO-User herbert pointed out to me, it was very unlikely that rxdart was the problem here.

I have looked into my code and found that my Page was being rebuilt, and because my code was looking like this, the bloc was re-instantiated. This somehow only happened on iOS and not on Android.

```dart
'page': (context) => MyPage(bloc: Bloc()),
```

Sorry for posting an unrelated issue here.

**Comment by shinewanna** [comment]
I didn't get the last value BehaviorSubject.
Firstly i use Sharef to store the last data,now i want to change.it can BehaviorSubject??if yes,suggest bro

**Comment by eldarkk** [comment]
> Ok, I've found the problem. As SO-User herbert pointed out to me, it was very unlikely that rxdart was the problem here.
> 
> I have looked into my code and found that my Page was being rebuilt, and because my code was looking like this, the bloc was re-instantiated. This somehow only happened on iOS and not on Android.
> 
> ```dart
> 'page': (context) => MyPage(bloc: Bloc()),
> ```
> 
> Sorry for posting an unrelated issue here.

So mate. Do you have any solution to fix that ?

**Comment by hoc081098** [comment]
@eldarkk use provider package instead pass instance directly 

_Sent from my 2201117TG using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
