### ISSUE TITLE
Is DefaultIfEmptyStreamTransformer functional?

### ISSUE THREAD

**Issue by CodingAleCR** [ReactiveX/rxdart#271]
So, I tried implementing a DefaultIfEmptyStreamTransformer for 2 of my BehaviorSubjects but saw that there's no reference to this transformer in the main README, only deep inside de docs. So, the question is, is it functional? Thanks in advance.

**Comment by frankpepermans** [comment]
Yes you can use `defaultIfEmpty`, if we're missing docs here then we just need to fix that asap :)

**Comment by CodingAleCR** [comment]
I tried doing it, but no value is given by default when I'm trying to get the value. My approach is using a StreamBuilder to listen to an Observable transformed with the defaultIfEmpty, but when I try to check snapshot.data it does not have anything, how could I retrieve the default value?

**Comment by frankpepermans** [comment]
`defaultIfEmpty` only triggers under the following conditions:
- The `Stream` did not receive any events
- The `Stream` is correctly closed

With the above being true, it will dispatch the default event when `onDone` triggers.

Are you expecting the above behavior, or do you have a different use case?

**Comment by CodingAleCR** [comment]
Oh that was it, I was looking for the wrong transformer then. I changed my approached and did the `startWith` transformer and it worked like a charm. Thanks for the help!
