### ISSUE TITLE
BehaviorSubject.value is null

### ISSUE THREAD

**Issue by aabanaag** [ReactiveX/rxdart#273]
Any ideas why my BehaviorSubject.value returns null?
```
class Bloc {
    final _list = BehaviorSubject<List<T>>();
    Observable<List<T>> get list => _list.stream;

   get() {
       Observable.fromFuture(repository.get())
          .listen(_list.sink.add);
   }
   
   update() {
      print(_list.value); // prints null
   }
}
```

On my Widget
```
Widget build(context) {
  Bloc _bloc = Bloc();
  _bloc.get();
  return Scaffold();
}
```

**Comment by brianegan** [comment]
It looks like you're doing a couple of things wrong:

  1. You're creating the `bloc` in the `build` method. This means any time that `build` method is run, your `bloc` will be recreated.
  2. You're performing an async operation (`repository.get()`), but you may not be waiting for that operation to complete before running the `update` method. In general, you need to ensure you call `update` after the async operation completes, or better yet, use a `StreamBuilder` to listen to the `list` and rebuild when data is added to it.

It would be better if your Widget code did something like this:


```
class MyWidget extends StatefulWidget {
  @override
  _MyWidgetState createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  Bloc bloc;

  @override
  void initState() {
    // Create the bloc in initState so it is only created once
    bloc = Bloc();

    // Fetch the data in initState so it's only fetched up front
    bloc.get();

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: <Widget>[
          const Text('Some Static Widget'),
          // Use StreamBuilder here
          StreamBuilder<List<String>>(
            stream: bloc.list,
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                return ListView(...);
              } else if (snapshot.hasError) {
                return const Text('Error!');
              } else {
                return CircularProgressIndicator();
              }
            },
          ),
        ],
      ),
    );
  }
}
```

**Comment by aabanaag** [comment]
Thanks. I do have StreamBuilder for the list.

**Comment by pratima-globant** [comment]
I have a 'retry' functionality when the API fails, in that case when the user clicks on 'retry' button, how should we reset the hasError state on BehaviorSubject and notify the listeners to show Progress indicator on the widget
