### ISSUE TITLE
BehaviorSubject.first times out if nothing is published in test with setUp

### ISSUE THREAD

**Issue by daniel-v** [ReactiveX/rxdart#280]
I am puzzled by this. It might be that I do something in a way I am not supposed to but this might be a bug.

Expectation:
```dart
test('', () {
     final bloc = BehaviorSubject<String>();
     expect(() => bloc.first, throwsStateError);
     bloc.close();    
});
```

And it works. What doesn't work is if I have `setUp` in the test and `bloc` is instantiated in it. `Stream` work as expected, that's why I report here. The full test case I put together to demonstrate: 

https://gist.github.com/daniel-v/6da6b1f65bcbf4b84f5112a028cf769d

**Dart** `Dart VM version: 2.1.0` and
**Flutter** `Flutter (Channel stable, v1.2.1, on Microsoft Windows)`
**package:rx** 0.21.0
**package:test** 1.5.3

**Comment by exKAZUu** [comment]
@daniel-v  I believe `setUp` is not related to the issue and the behavior depends on whether `bloc.close();` is put in `test` or `tearDown`.

`bloc.first` returns `AsObservableFuture<String>` so `expect(() => bloc.first, throwsStateError);` waits for `bloc` to be closed or wait for some strings to be added in `bloc`.
If `bloc.close();` is put in `tearDown`, `bloc.close();` is called after finishing `test` (i.e. after the time-out).

**Comment by daniel-v** [comment]
Sorry for late reaction! I'll further dig into this based on your comment. I'll keep you posted.
