### ISSUE TITLE
shareValue().value always null

### ISSUE THREAD

**Issue by larssn** [ReactiveX/rxdart#281]
So I'm not sure if this is a bug, or I'm just misunderstanding something.

Given I have a subject like this: `final _mySubject = BehaviorSubject();`
.. then I'd think these two statements are equivalent:
```
ValueObservable get data1 => _mySubject.stream;
ValueObservable get data2 => _mySubject.map((v) => v).shareValue();
```

However `data2` always returns `null`:
```
print(data1.value): <data>
print(data2.value): null
```

~~Is this meant to happen? It would be pretty useful to perform transformations on the stream and convert it back to a `ValueObservable`, but maybe I'm misunderstanding?~~

~~It should be fairly easy to test; basically just attach `.map((v) => v).shareValue()` to a `BehaviorSubject`.~~

**Comment by larssn** [comment]
Ok, so this appears to be because no one has subscribed to the `BehaviorSubject` yet, which is different from the standard Rx contract (in RxJS). In Flutter, in the context of `StreamBuilders`, it can be pretty hard to get an idea of whether an given subject has been subscribed to before.

Feel free to close, or consider it a feature request to align with the standard Rx contract.

**Comment by frankpepermans** [comment]
This is indeed something many users struggle with,  perhaps we could eventually support a way to use eager listening with shareValue.

This is kinda breaking with Dart Streams again, since they are always lazy.

**Comment by larssn** [comment]
Seeing as you are wrapping Dart Streams with your own library; your rules should apply IMO. 😄
But I get where you're coming from..

One thing I always missed from RxJS was something like `shareValue`, that would allow synchronous data access. But the current implementation is not intuitive, to me at least.

As I recall, RxJS had plenty of operators that maintained internal subscriptions like `share` `publishReplay` etc. Is it not desired to align with that kind of functionality?

**Comment by RollyPeres** [comment]
Having an rxdart api very much like RxJs would be cool, but some stuff would just break the way dart streams work, and would probably be awkward for people to think differently based on whether they work with `Stream`'s or `Observable`'s. They kinda need to adhere to `Stream` contract since they build on top of it.

**Comment by larssn** [comment]
Well a lot of people will be flocking to RxDart because of Flutter, and a lot of people will already know JS, and by extension RxJS. So its going to be awkward for one group or another regardless.

I'm just worried about all these 'offshoots' of Rx, that each have their own behavior. Most devs jump between languages quite frequently, and having to recall the particular quirks of your Rx flavour of the day might be undesired overhead. 🙂

**Comment by brianegan** [comment]
Could you describe the behavior you see in RxJS a bit more? My understanding from reading the docs and code is that `share` does not connect to the underlying observable until the first subscriber begins listening for events. This is the default behavior of `refCount`.

Are you seeing a situation where RxJS subscribes to the underlying observable before the first subscription?

https://rxjs.dev/api/operators/share

https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/refCount.ts#L12

**Comment by RollyPeres** [comment]
So far I've used RxJs, Rx.NET and RxDart and they all have their own gotchas. You can't expect to have similar implementations everywhere since language specifics come into play.

**Comment by RollyPeres** [comment]
I believe the most awkward thing about dart `Stream`'s is that they are single subscription by default. Would be curious about the reasoning behind this decision.

**Comment by larssn** [comment]
@brianegan Sorry I should have been more clear, I'm basically just referring to `ConnectableObservable`, which you alluded to. But you're correct, even here, it's the consumer's own responsibility to maintain the subscription from `connect()`.

I'm starting to realize the problems in creating an operator like `shareValue`: If it did an internal subscription, then what is the condition for unsubscribing? - there isn't any.

Solving that would probably be a pretty big rewrite of the Rx architecture, and then I'd be arguing against my own case. 😄 

However, I do believe that a consumer seeing two value observables like:
```
ValueObservable<String> get data1 => BehaviorSubject.seeded('Hello').stream;
ValueObservable<String> get data2 => BehaviorSubject.seeded('World').map((v) => v).shareValue();
```
.. should not need to know the underlying implementation in order to use the API correctly. It breaks basic separation of concerns.

```
if (anyone_has_subscribed_to_data2_previously()) { // :(
    print(data2.value);
}
```

But I can appreciate the challenge involved with this operator.

**Comment by brianegan** [comment]
Hey, I can totally appreciate the confusion around these operators / classes. They confused me when I first used them as well :) "Wait what, why do I `connect` to this thing instead of just listening!?"

Overall, I think providing the `value` is a double-edged sword: Sometimes you really need that initial value synchronously (for StreamBuilder), but I almost never rely on the information being available synchronously since these are inherently async events. Therefore, from the subscriber side, it often makes sensed to assume the `value` might be null since you don't want to tie the subscriber to the implementation of the producer.

So, yah... sorry if this is a bit of a rant, but from this discussion I kinda feel like the `refCount` operator is working as intended, but certainly could be simpler to understand.

**Comment by RollyPeres** [comment]
> Subscribers go from 0 to 1? Subscribe. Subscribers go from 1 to 0: unsubscribe.

@brianegan There's nothing to do, this is what to expect from `refCount`.

**Comment by brianegan** [comment]
Hey all, closing out some old issues! Thanks for writing in, but I think we've taken got a good resolution here :)

**Comment by HerrNiklasRaab** [comment]
I just stumbled across exactly this. If I understood correctly at the moment there is no go-to solution for this problem, right?

``` dart
ValueObservable get data1 => _mySubject.stream;
ValueObservable get data2 => _mySubject.map((v) => v).shareValue();
```

However data2 always returns null:

``` dart
print(data1.value): <data>
print(data2.value): null
```

The thing is, my BehaviorSubject is seeded. Found it totally strange, that value doesn't return anything even for a seeded BehaviorSubject.
 
``` dart
final _mySubject = BehaviorSubject().seeded(123);
```
