### ISSUE TITLE
snapshot.data return null

### ISSUE THREAD

**Issue by farhanrahmadi** [ReactiveX/rxdart#282]
my snapshot data not return data, i do get my data from my server and it no error 
but the data is not save in publish subject

heres some my code
`// get my account 
fetchUser() async {
    User user = await _repository.fetchUser();
 //    print(user.name);
    _accountFetcher.sink.add(user);
    print(_accountFetcher.stream);
  }`

print retrun 

> Instance of 'PublishSubject<User>''

if you want see full code feel free to see here [https://github.com/farhanrahmadi/cariin](url)
my state management on /lib/state_management

thanks for helping

**Comment by frankpepermans** [comment]
Heya, not sure I completely follow: if you want to consume values from a Stream, then you should listen to them first.

Maybe you are looking for a BehaviorSubject? After adding, you can synchronously check the latest value using .value

**Comment by farhanrahmadi** [comment]
@frankpepermans after hour debugin i found some fact could help:
1 i retrive data from server and manage it properly
2  _accountFetcher.sink.add(user); i not sure if the data saved or not
3 on stream builder snapshot.data always null
