### ISSUE TITLE
Issue with pending listening for BehaviorSubject returned from share()

### ISSUE THREAD

**Issue by rota2000** [ReactiveX/rxdart#285]
When I am trying to do such, after data has been added to _stream1 and _stream2, several seconds later subscribing to BehaviorSubject instance, data **never arrives**.

```
final BehaviorSubject<String> _stream1 = BehaviorSubject();
final BehaviorSubject<String> _stream2 = BehaviorSubject();
Observable<String> combStream;

void test() {
	combStream = Observable.combineLatest2<String, String, String>(
		  _stream1,
		  _stream2,
		  (one, two) => one + two,
		).share();
		
	combStream.listen((data) {
	  print(data);
	});

	combStream.listen((data) {
	  print(data);
	}); 
		
	_stream1.add('One');
	_stream2.add('Two');

	combStream.listen((data) {
			print(data); // THIS CALLED
	});

	Future.delayed(Duration(seconds: 2), () {
	  combStream.listen((data) {
		print(data); // THIS NEVER CALLED
	  });
	});
}
```

**Comment by frankpepermans** [comment]
I believe share yields a PublishSubject, not a BehaviorSubject. If you start listening after a delay, it won't replay the last value as you might suspect.

Ideally, share should be used on single subscription Streams only.

**Comment by rota2000** [comment]
No. I checked - there is BehaviorSubject. And several subscriptions are
working, but not one after delay.

пн, 13 мая 2019 г., 22:25 Frank Pepermans <notifications@github.com>:

**Comment by rota2000** [comment]
Sorry, yes.... really my mistake. share() returns PublishSubject, while
shareValue() returns Behavior  one. Thank you very much!

пн, 13 мая 2019 г. в 22:25, Frank Pepermans <notifications@github.com>:
