### ISSUE TITLE
codecov hangs with Dart >=2.3

### ISSUE THREAD

**Issue by frankpepermans** [ReactiveX/rxdart#287]
As the title says, no idea why we suddenly hang up, see also: https://github.com/dart-lang/coverage/issues/249

**Comment by mit-mit** [comment]
See https://github.com/dart-lang/coverage/issues/249#issuecomment-518837530, we think this package needs to update it's deps (it's currently pinning to 0.12 in https://github.com/ReactiveX/rxdart/blob/master/pubspec.yaml#L17)

cc @frankpepermans @brianegan

**Comment by frankpepermans** [comment]
Thanks!

It needed the version bump, but we also had to explicitly add --disable-service-auth-codes in the build config.

Now coverage completes as expected.
