### ISSUE TITLE
flatMap does not resume listening to all streams after pause

### ISSUE THREAD

**Issue by rbellens** [ReactiveX/rxdart#293]
There is a bug in FlatMapStreamTransformer. The variable `otherSubscription` is defined outside the scope of the `onData` function argument of the listen method, but assigned inside this function. This means it will be overwritten every time a new value arrives. The `onDone` callback removes this subscription from the list of subscriptions, but since this might have been overwritten in the mean time, the wrong one might be removed.

As a result, this causes wrong behavior. For example, when the transformed stream is being paused, all streams in the list `subscriptions` will be paused. When, during this pause, the wrong subscription is being removed from this list, resuming the transformed stream will not result in resuming all streams in this list. Therefore, some items will not be emitted in the final stream.

**Comment by frankpepermans** [comment]
Good find :)

Should be fixed in https://github.com/ReactiveX/rxdart/pull/294

There's indeed no reason to remove the subscription when onDone fires
