### ISSUE TITLE
combineLatest returns error events

### ISSUE THREAD

**Issue by drmirk** [ReactiveX/rxdart#296]
I was trying to enable/disable a button based on user input. If all text input matches a certain condition, only then enable the "insert" button.

Normally button gets only enabled, if all the input field is correct. But if one or more incorrect, and user moves to another input field, and change it to correct/incorrect, button gets enabled, even if some field has wrong input. Check gif:

[https://i.stack.imgur.com/jOzpw.gif](url)

Code for login bloc:

  ```
    import 'package:rxdart/rxdart.dart';
    
    class LoginScreenBloc {
      final _firstCtrl = BehaviorSubject<String>();
      final _lastCtrl = BehaviorSubject<String>();
      final _userNameCtrl = BehaviorSubject<String>();
      final _passwordCtrl = BehaviorSubject<String>();
    
      Function(String) get changeFirst => _firstCtrl.sink.add;
      Function(String) get changeLast => _lastCtrl.sink.add;
      Function(String) get changeUser => _userNameCtrl.sink.add;
      Function(String) get changePass => _passwordCtrl.sink.add;
    
      final fieldSize = StreamTransformer<String, String>.fromHandlers(
        handleData: (value, sink) {
          if (value.length > 3) {
            sink.add(value);
          } else {
            sink.addError("Can't be Empty!");
          }
        },
      );
    
      Stream<String> get firstname => _firstCtrl.stream.transform(fieldSize);
      Stream<String> get lastname => _lastCtrl.stream.transform(fieldSize);
      Stream<String> get username => _userNameCtrl.stream.transform(fieldSize);
      Stream<String> get password => _passwordCtrl.stream.transform(fieldSize);
    
      void insertValue() {
        print("${_firstCtrl.value}");
        print("${_lastCtrl.value}");
        print("${_userNameCtrl.value}");
        print("${_passwordCtrl.value}");
      }
    
      Stream<bool> get insertButton {
        return CombineLatestStream(
          [firstname, lastname, username, password],
          (values) {
            return true;
          },
        );
      }
    
      dispose() {
        _firstCtrl.close();
        _lastCtrl.close();
        _userNameCtrl.close();
        _passwordCtrl.close();
      }
    }

```

Code for the button:

```
    Widget insertValue(BuildContext context, LoginScreenBloc bloc) {
      return StreamBuilder<Object>(
        stream: bloc.insertButton,
        builder: (context, snapshot) {
          return RaisedButton(
            child: Text("Insert"),
            onPressed: snapshot.hasData ? bloc.insertValue : null,
          );
        },
      );
    }
```

Related question on stackoverflow: [https://stackoverflow.com/questions/56286287/using-combinelatest-to-enable-disable-a-button-but-button-gets-enabled-even-if](url)

**Comment by RollyPeres** [comment]
Your `insertButton` stream returns true all the time. I'm sure that's not what you want. You should handle the logic there.

**Comment by drmirk** [comment]
> Your `insertButton` stream returns true all the time. I'm sure that's not what you want. You should handle the logic there.

I know i can handle logic inside `insertButton` stream. But my understanding is, we use combineLatest because it combines only successful events, and ignores all error events.
If you see the gif, [https://i.stack.imgur.com/jOzpw.gif](url) you would see, even when the "username" was emitting error, fixing the "password" activates the button.

**Comment by RollyPeres** [comment]
I belive you are trying to achieve something similar to this: [https://github.com/shiang/flutter-form-with-validation-BLOC](url)

**Comment by drmirk** [comment]
Thanks for your suggestion, that repo is an exact copy of [https://github.com/StephenGrider/FlutterCasts/tree/master/login_bloc](url). When searching for my problem, i found that repo, but it didn't solved my problem.

**Comment by brianegan** [comment]
> But my understanding is, we use combineLatest because it combines only successful events, and ignores all error events.

I think this is the fundamental misunderstanding -- combineLatest will not ignore errors. Errors are forwarded to the `combineLatest` stream so you can handle them as you'd handle any normal error.

IMO, I'd recommend against this particular technique. If a form field is invalid, that should not be considered an error (`sink.addError`). Rather, you should create various streams like `buttonValid` which emit `true` / `false` if the field is valid or not, then you can use combineLatest in a simpler way: Just check that all of those streams, such as `emailValid` and `passwordValid`, return true.

**Comment by drmirk** [comment]
> I think this is the fundamental misunderstanding -- combineLatest will not ignore errors. Errors are forwarded to the `combineLatest` stream so you can handle them as you'd handle any normal error.

So, it seems my fundamental understanding was wrong. Thanks for correcting me.

> IMO, I'd recommend against this particular technique. If a form field is invalid, that should not be considered an error (`sink.addError`). Rather, you should create various streams like `buttonValid` which emit `true` / `false` if the field is valid or not, then you can use combineLatest in a simpler way: Just check that all of those streams, such as `emailValid` and `passwordValid`, return true.

And really appreciate your suggestion. Will try to implement it using your suggestion.

**Comment by Makarov96** [comment]
i have the same error, how solved @drmirk ?

**Comment by drmirk** [comment]
@Makarov96 Originally i returned true like:
```
return CombineLatestStream([firstname, lastname, username, password], (values) {
    return true;
    },
);
```

But now i check if all the conditions are met before returning true, like:
```
return CombineLatestStream([firstname, lastname, username, password], (values) {
    if (all button conditions are true)
        return true;
    },
);
```

**Comment by Jan-Stepien** [comment]
Problem cause is explained:
[cause](https://www.didierboelens.com/2020/01/form-validation-using-combinelatest-might-give-false-positives/)
Resolution for my problems found:
[solution](https://dev.to/levi_zitting/flutter-multiple-stream-builder-package-4l10)
[dependency](https://pub.dev/packages/multiple_stream_builder)
