### ISSUE TITLE
shareReplay() not working as expected

### ISSUE THREAD

**Issue by RollyPeres** [ReactiveX/rxdart#297]
I'm combining two `Observables` using `CombineLatest2`. My setup looks something like:
```
final BehaviorSubject<int> dispatcher$ = BehaviorSubject<int>();

  Observable<int> get first$ => dispatcher$
      .flatMap((int number) => computation$(number))
      .scan<int>((int acc, int curr, _) => acc ?? 0 + curr)
      .shareReplay();

  BehaviorSubject<bool> second$ = BehaviorSubject<bool>.seeded(false);

  Observable<String> get combined$ => Observable.combineLatest2(
          first$.map((int number) => number * 10),
          second$.stream,
          (int first, bool second) => '$first - $second')
      .doOnData((String c) => print('combined: $c'));

  Stream<int> computation$(int number) => Observable<int>.just(number)
      .doOnData((int no) => print('$no computed at ${DateTime.now()}'));
``` 

I then listen and dispatch a value:

```
first$.listen(null);
combined$.listen(null);
dispatcher$.add(1);
```

Since I'm using `shareReplay` I would expect that `computation$` to only run once and `first$` emission to be reused within `combineLatest`. Obviously this is not the case, since the `first$` chain seems to be ran twice.

 @brianegan @frankpepermans Am I missing something or is this a bug ?

**Comment by frankpepermans** [comment]
Doesn't look like a bug to me at first glance,

You listen to *both* `first$` and `combined$`:

So you invoke a listen on `first$` twice, once directly and once indirectly with `combined$`.
Given that `dispatcher$` is a `BehaviorSubject`, it will simply dispatch the latest value twice in this case (which is `1`).

`computation$` now logically triggers twice as a result, since it is the first transformation following `dispatcher$`.

**Comment by frankpepermans** [comment]
FYI, you can mimic the behavior you want if you set up `first$` like this:

```
Observable<int> get first$ => Observable.repeat((_) => dispatcher$
    .flatMap((int number) => computation$(number))
    .scan<int>((int acc, int curr, _) => acc ?? 0 + curr));
```

**Comment by RollyPeres** [comment]
Thanks @frankpepermans , I will give it a try later on. 

I mind be in the rxjs mindset here, but shouldn't shareReplay actually transform `first$` into a `replayObservable` that you can listen multiple times and each new subscriber will get the latest emitted value without actually re-running the whole chain again ?

I'm not familiar with `replayObservable` but from it's name I would think of it as something similar to `SomeReplaySubject.stream`.

**Comment by frankpepermans** [comment]
TBH I've never used that op in rxjs :) Maybe @brianegan can chime in here, what `shareReplay` does here, looks okay to me in respect to how the default Dart streams work, but that's another discussion entirely (many rx implementations compromise between default Rx and how Dart Streams work out of the box).

**Comment by RollyPeres** [comment]
@frankpepermans I was completely sure it has to do with how dart streams are implemented, because `shareReplay` in rxjs allows you to basically cache a pipe and whenever a new subscriber joins it will get that cache without re-running the whole pipe again. 
I'm pretty sure it has the same implementation as `RxDart`'s one `publishReplay().refCount()`, but I guess here it is basically used to allow for multiple subscribers not to actually share the last n emitted values.

**Comment by RollyPeres** [comment]
> FYI, you can mimic the behavior you want if you set up `first$` like this:
> 
> ```
> Observable<int> get first$ => Observable.repeat((_) => dispatcher$
>     .flatMap((int number) => computation$(number))
>     .scan<int>((int acc, int curr, _) => acc ?? 0 + curr));
> ```

@frankpepermans I gave your suggestion a shot, but the behavior is exactly the same as my previous attempt, the whole `first$` chain is executed again, instead of being reused.

Would be nice to have an operator which internally uses maybe a `ReplaySubject` to cache the last n values emitted by the chain it is applied to, and whenever there's a new listener, it will immediately give that new listener those cached values. Of course it should subscribe to source and start caching as soon as there's at least one listener and dispose the subscription as soon as there's no active listeners. Basically `.refCount`.

Maybe there's something like that already implemented, but tbh I was living with the impression that `shareReplay`' will do just that :)

**Comment by frankpepermans** [comment]
Urgh yes indeed, dunno what I was thinking there...

You could solve it with a `pipe` maybe?

i.e. create a new Subject: 
```
BehaviorSubject<int> cache$ = BehaviorSubject<int>();
first$.pipe(cache$);
```

Then just use this one instead of first$.

**Comment by RollyPeres** [comment]
That's brilliant, thanks a lot for your time and help @frankpepermans !
