### ISSUE TITLE
Do I need to cancel StreamSubscription after I've closed a Subject ?

### ISSUE THREAD

**Issue by Nico04** [ReactiveX/rxdart#301]
It's more of a question, I didn't found any help elsewhere.
With that code :

`var notes = BehaviorSubject.seeded("test");`
`notes.debounceTime(Duration(seconds: 1)).distinct().where((value) => value != '123').listen(_saveNotes);`

Do I need to call cancel() on the StreamSubscription after I've called close() on notes ?
Same question for all the Observables generated by the distinct and others ?

Thanks

**Comment by LeandroDoldan** [comment]
Short answer: **Yes.**.

Long answer: https://stackoverflow.com/questions/46203364/rxjs-behaviorsubject-unsubscribe

It is better doing it just in case the Subject never completes. If it does complete, the subscription will be closed automatically.

**Comment by frankpepermans** [comment]
Closing this as it's not directly an rxdart issue.

Since `Observable` is built upon `Stream`, you can just follow the best practices regarding this topic.
