### ISSUE TITLE
Plain ol' Subject

### ISSUE THREAD

**Issue by larssn** [ReactiveX/rxdart#306]
I'm missing my RxJS `Subject`, an entity that does not store the latest value.

Is there any equivalent in RxDart?

**Comment by frankpepermans** [comment]
See PublishSubject, or just use a default Dart StreamController

**Comment by larssn** [comment]
We ended up using the PublishSubject. Thanks for the tip.

Not sure I'm fond of the name, as it reminds me of the `publish` operator in RxJS.

**Comment by frankpepermans** [comment]
Well that depends on where you're coming from :)

In java, there is a PublishSubject as well in rxjava

**Comment by larssn** [comment]
I see. Well that makes perfect sense then. I'll go complain at the RxJS guys then (just kidding). :-)

Thanks.
