### ISSUE TITLE
Missing Observable.fromCallable 

### ISSUE THREAD

**Issue by egorikem** [ReactiveX/rxdart#309]
Hi there! You guys are doing an amazing job with this support. However, coming from RxJava2, I was kinda surprised: why there are no methods like `Observable.fromCallable { ... }`? Maybe I'm getting something wrong, but that's the way to do it in RxJava and that seems like an adequate approach. Is there a way to achieve the same idiom in RxDart?

**Comment by frankpepermans** [comment]
Nope we don't have it, but it should be a good addition.

You could check out defer for now and just return the result from the callable.

**Comment by frankpepermans** [comment]
see https://github.com/ReactiveX/rxdart/pull/310
