### ISSUE TITLE
Unit tests with emitsDone are failing after upgrade from 0.22.0 to 0.22.1 version.

### ISSUE THREAD

**Issue by vikdet** [ReactiveX/rxdart#311]
Hi guys! Your lib is awesome, but we faced with a lot of failed unit tests after upgrading to 0.22.1 version. It seems that transformed stream doesn't send done event from original one. There is the example of test which works with 0.22.0, but fails with 0.22.1 version.
```
import 'dart:async';

import 'package:rxdart/rxdart.dart';
import 'package:test/test.dart';

void main() {
  test('process emits status messages', () {
    // Dummy data to mimic something that might be emitted by a process.
    final stdoutLines = Stream.fromIterable([
      'Ready.',
      'Loading took 150ms.',
      'Succeeded!',
    ]);

    final std = stdoutLines.transform<String>(SwitchMapStreamTransformer((value) => Future.value(value).asStream()));

    expect(
        std,
        emitsInOrder(<Object>[
          // Values match individual events.
          'Ready.',

          // Matchers also run against individual events.
          startsWith('Loading took'),

          // Stream matchers can be nested. This asserts that one of two events are
          // emitted after the 'Loading took' line.
          emitsAnyOf(<Object>['Succeeded!', 'Failed!']),

          // By default, more events are allowed after the matcher finishes
          // matching. This asserts instead that the stream emits a done event and
          // nothing else.
          emitsDone,
        ]));
  }, timeout: const Timeout(const Duration(seconds: 1)));
}

```

**Comment by andrewst** [comment]
Hi, guys! I investigated this problem and I have magic for you. 
We have different sources in repository and pub.dev.

https://storage.googleapis.com/pub-packages/packages/rxdart-0.22.1.tar.gz/lib/src/transformers/switch_map.dart#L61
![image](https://user-images.githubusercontent.com/828244/62497149-c7429700-b7e3-11e9-9a33-d693b7242105.png)

vs

https://github.com/ReactiveX/rxdart/blob/v0.22.1/lib/src/transformers/switch_map.dart#L61
![image](https://user-images.githubusercontent.com/828244/62497482-c9f1bc00-b7e4-11e9-8434-5c9512dc89d2.png)

We also have a https://storage.googleapis.com/pub-packages/packages/rxdart-0.22.1.tar.gz/lib/src/utils/bound_stream.dart on pub.dev, which is not in the repository.

@frankpepermans Please publish the package again.

**Comment by frankpepermans** [comment]
Indeed looks like the wrong branch was published, 
I've just upped v0.22.1+1, can you retry the tests?

**Comment by vikdet** [comment]
I retried with v0.22.1+1 and it works now. Thanks to all for fast fix!

**Comment by danwulff** [comment]
I came across this problem as well. Thanks for the quick fix before I could even get a reproduction together!

For those that may run across this same problem and want a simple reproduction. Here is my quick reproduction of the issue:

```
import 'package:rxdart/rxdart.dart';

void main() {
  final Observable<int> multiplyByTwo = Observable.just(3)
      .switchMap((value) => Observable.just(value * 2))
      .doOnData((value) {
    print('multiplyByTwo $value');
  });

  final Observable<double> divideByTwo = multiplyByTwo
      .switchMap((value) => Observable.just(value / 2))
      .doOnData((value) {
    print('divideByTwo: $value');
  });

  divideByTwo.doOnDone(() {
    print(
        'this should happen'); // didn't actually occur with RxDart 0.22.1, but works with 0.22.1+1 (or 0.22.0)
  }).listen((_) {});
}
```
