### ISSUE TITLE
bindto

### ISSUE THREAD

**Issue by SeongBrave** [ReactiveX/rxdart#313]
Does RxDart have an API similar to RxSwift bind to

![image](https://user-images.githubusercontent.com/10784393/62819576-bb5f2800-bb89-11e9-90e9-ac445433811e.png)

**Comment by hoc081098** [comment]
Look at the implementation of bind(to: )
```swift
public func bind<O: ObserverType>(to observer: O) -> Disposable where O.E == E {
    return self.subscribe(observer)
}
```
Subscribe is called inside. :)

**Comment by SeongBrave** [comment]
@hoc081098  this is RxSwift, is there RXDart?

**Comment by hoc081098** [comment]
RxDart Observable has `listen` method (similar to `subscribe` in RxSwift)

**Comment by SeongBrave** [comment]
@hoc081098 Thank you very much for your timely reply, but I still don't know how to use the method like bind to in RxDart environment. Now I am looking for my similar method in RxDart, and I don't know how to use it or which API to use. Could you please help to describe it more clearly?

**Comment by frankpepermans** [comment]
Is this question targeted to Flutter specifically?

RxDart will not have any dependencies on Flutter (or html, io), that said, a separate library (RxFlutter for example) could be the answer here, but there are no current plans from our side.

**Comment by brianegan** [comment]
I'd say if you'd want to "bind" the output of a Streams to a Widget in Flutter, use the `StreamBuilder` Widget! It allows you to rebuild a Widget when the stream emits new values :)
