### ISSUE TITLE
Could Observable.combineLatestList work with a list of 1 element?

### ISSUE THREAD

**Issue by Koridev** [ReactiveX/rxdart#316]
Currently, trying to use Observable.combineLatestList with an Iterable of 1 element failed because of the assert
``` assert(streams.length > 1, 'provide at least 2 streams'),```
in `CombineLatestStream`.

We don't necessarily know in advance the number of streams we will want to combine, is there any reason why a list of 1 element is forbidden?
"Combining" a single stream would just mean emitting its elements wrapped in lists of 1 element. 
It would be helpful if the Observable could take care of that internally.

**Comment by brianegan** [comment]
Hrm, which version of RxDart are you on? We removed this restriction a little while back: https://github.com/ReactiveX/rxdart/pull/256
