### ISSUE TITLE
Github Search example not working

### ISSUE THREAD

**Issue by thaihoa-fe** [ReactiveX/rxdart#317]
Hi, I'm getting this issue when trying to run github_search app in `example` folder: 
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: type 'List<String>' is not a subtype of type 'GithubApi' of 'api'
```

Why do we have `api` argument as Github Api as parameter? I though that main function only accept list of String arguments.

```dart
void main(GithubApi api) {
  runApp(SearchApp(api: api));
}
```

https://github.com/ReactiveX/rxdart/blob/master/example/flutter/github_search/lib/main.dart#L5

**Comment by brianegan** [comment]
Thanks! You're right -- I'll take a look. I was playing around with injecting the GithubApi for testing purposes, but it shouldn't quite work like that.
