### ISSUE TITLE
refCount is not working in the same way as that of RxJS or RxPY

### ISSUE THREAD

**Issue by Nandiin** [ReactiveX/rxdart#318]
Consider this code:
```dart
final source = Observable
    .periodic(Duration(seconds: 1), (v) => v)
    .take(5)
    .shareValue();

StreamSubscription sub;

sub = source.listen((data) {
  print('1: $data');
  sub?.cancel();
  source.listen((data) => print('2: $data'));
});
```

I'd expect it to output:
```
1: 0
2: 0
2: 1
2: 2
2: 3
2: 4
```
However, it only outputs:
```
1: 0
2: 0
```
and then terminates.

The main problem is underlying `BehaviorSubject` of `refCount` is closed after the first subscription is canceled and consequent `listen` does not result in openning a new one.

Although there is no clear definition about this behavior (cancelling all subscriptions on a `refCount` returned stream and then subscribing to it again) in the [`Rx` specification ](http://reactivex.io/documentation/operators/refcount.html), `RxJS` and `RxPY` both behaved as I expected. I haven't experiment this in other language implementations for now but pretty willing to do so if it's necessary.

RxJS code [jsfiddle](https://jsfiddle.net/m6najf7t/):
```javascript
const { interval } = rxjs;
const { share, take } = rxjs.operators;

const source = interval(1000).pipe(take(5), share());

const sub = source.subscribe((a) => {
  console.log(`1: ${a}`);
  sub.unsubscribe();
  source.subscribe((a) => console.log(`2: ${a}`));
})
```

RxPY code:
```python
import rx
import time
from rx import operators as ops

source = rx.interval(1).pipe(ops.take(5), ops.share())

def on_next1(a):
  sub.dispose()
  print(f'1: {a}')
  source.subscribe(on_next2)

def on_next2(a):
  print(f'2: {a}')

sub = source.subscribe(on_next1)

time.sleep(10)

```

**Comment by frankpepermans** [comment]
That's interesting,

There's an easy fix we can apply here, simply do the inner cancel using `scheduleMicrotask`, so that it doesn't take effect immediately, allowing new `Subscription`s in the next few lines.

But I do wonder if this isn't a fringe case? The `cancel` here happens sync, so effectively refCount closes down immediately here, because at the time of `cancel`, only one `Subscription` is open.

If you do:
```
source.listen((data) => print('2: $data'));
sub?.cancel();
```

**Comment by brianegan** [comment]
Yah, I don't think we'll be able to have the same behavior in this case. Why? Due to the nature of Streams. In general, many streams are "Single Subscription," meaning you can only subscribe to and cancel that subscription once. If you re-subscribe to the underlying stream, you will get something like a `State Error: Can't listen to Stream multiple times`.

In normal Rx, "Cold" observables do not have this restriction. Therefore, I don't think we can emulate this same behavior because we simply can't re-listen to the underlying Stream.

Of the subtle differences between Dart Streams and the Rx Observable specification, I often think this one is the hardest to deal with.

**Comment by Nandiin** [comment]
I indeed came up with the idea of lifting second `listen` upon `cancel` call and it solved that problem. However, this "closing the underlying `BehaviorSubject` for good upon cancellation of last subscription" behavior is confusing and causes some ghosty bug.

Despite the agnosticy about flutter framework of this library, we would eventually use in a flutter app. Consider a `StreamBuilder` which depends on `refCount` returned stream, it might be erased from the widget tree under certain condition and come back later, expecting same stream to be still active (but that stream is closed actually). I understand that in this simple example, we should give `StreamBuilder` a new `refCount` returned stream every time it's being rebuilt. But it's a heavy mental burden to track that done if the actual stream given to the `StreamBuilder` is a complex derivative of that `refCount` returned stream.

```dart
// Assume a BLoC -ish class
MyForm {
  Stream<bool> canSubmit; // it's actually a shareValue() returned Observable
  Stream<bool> submitting; // it's the same;
}

// at some point of the widget tree
Widget _buildButton(BuildContext context) {
  final myForm = MyForm.of(context);
  // myForm may be obtained via other means 
  // like ever-existing static global variable, parent injection etc.
  // The point is same myForm instance 
  // survives multiple rebuild of following StreamBuilder
  return StreamBuilder(
    stream: Observable.combineLatest2(
      myForm.canSubmit, 
      myForm.submitting, 
      (canSubmit, submitting) {
          return [canSubmit, submitting];
      },
    ),
    initialData: [false, false],
    builder: (context, snapshot) {
      final canSubmit = snapshot.data[0];
      final submitting = snapshot.data[1];
      return submitting ? progressIndicator : canSubmit ? raisedButton : disabledButton;
      // progressIndicator, raisedButton, disabledButton are all corresponding widgets.
    }
  );
}
```
Imagine that under certain condition `_buildButton` is removed from the widget tree and re-attached later while `myForm` somehow persists during this process. `canSubmit` and `submitting` is subscribed at the first call of `_buildButton` and unsubscribed when `_buildButton` returned widget is removed from the widget tree. Unfortunately, those to streams are closed at this point as there is no listeners subscribing it. When `_buildButton` is again on the table, it never gets update from `myForm`.

**Comment by Nandiin** [comment]
@brianegan I'm not a Rx expert but am able to see what you're pointing out. However, as `ValueConnectableObservable` is implemented with an `BehaviorSubject` underhood, I think the restriction of `Stream` being single subscription is handled. A navie fix I can think of is override `listen` method on `ConnectableObservable` and manage reference count on it's own rather than depending on `StreamController`'s `onListen` and `onCancel` callback.

**Comment by brianegan** [comment]
Yep, BehaviorSubject is a broadcast Stream, but the *source* stream in your example is a Single-Subscription Stream, rather than a "Cold Observable" like in other Rx implementations. 

`refCount` will listen to that source Stream when the first `listen` call happens, and it will unsubscribe from that source stream when there are no more listeners.

In other languages, when you cancel all subscriptions then re-subscribe, it will once again listen to that source Stream and emit the results. That's where it goes a bit wrong in DartLand, since you cannot re-subscribe to the Single-Subscription Stream the same way you can re-subscribe to a Cold Observable.

Therefore, the only way to keep the subscription open as long as you need is to avoid `refCount` and use `connect` instead. It would look something like this:


```dart
void main(List<String> arguments) {
  final source = Observable
      .periodic(Duration(seconds: 1), (v) => v)
      .take(5)
      .publishValue();

  // Begins listening to the underlying observable
  final StreamSubscription connectionSubscription = source.connect();

  StreamSubscription sub;

  sub = source.listen((data) {
    print('1: $data');
    sub?.cancel();
    source.listen((data) => print('2: $data'));
  });

  // Disconnect from the source stream by cancelling the connection
  // Generally want to do this when the Bloc should be disposed in a `dipose`
  // method or something similar
  // connectionSubscription.cancel();
}
```

**Comment by Nandiin** [comment]
I see. Since the single subscription nature of dart stream, we need some kind of `StreamController` to be open in the middle if we want to get a normal Rx like 'cold' observables and that `StreamController` being opened is a leak. So it needs to be explicity closed in the userland no matter how.

**Comment by Nandiin** [comment]
That being said, can we re-implement the `Observable` up from the ground to meet Rx behaviors ? The new `Observable` can still be assignable to a `Stream` variable but it only implments `Stream` class as an interface rather than extending it.

**Comment by frankpepermans** [comment]
This is a discussion that keeps coming back :)

We've decided to follow the Dart Streams way of doing thing whenever these diffs pop up.

There's many reasons as to why, but the main one is that Dart Streams are so tightly integrated with everything, that a user would always be dealing with them at some point.

Sure, you could do a runtime conversion from a Dart Stream to an Observable Stream, but things sure get tricky if you, as a dev, would need to always be very aware that you have 2 Stream implementations that behave differently.
Having these 2 implementations is not a good thing, it would only lead to confusion and inevitable bugs.

Say you open a random Class and see that it accepts Stream stream; for example, it could be either at runtime, consuming it would require you to test the Type, or always convert to Observable/Stream depending on what you expect it to be.

**Comment by Nandiin** [comment]
@frankpepermans Thanks for replying. I might have failed to make myself understood. What I'm suggesting is a `Observable` class as `class Observable<T> implements Stream<T>` rather than `class Observable<T> extends Stream<T>`. In that case, an instance of `Observable` is safely assignable to a variable of type `Stream` without any runtime type check. 

Indeed, `Observable` behaves different from `Stream` when it's being subscribed to (`Observable`s can be subscribed to multiple times), but that is a valid trade off at least IMO.

**Comment by frankpepermans** [comment]
Which boils down to the same thing, a true Rx Observable vs a Dart Stream, with different behavior.

Devs would need to learn both implementations, native Dart Streams are everywhere.

**Comment by Nandiin** [comment]
I see your commitment to align `Observable` with `Stream`. I respect that and am closing this issue as it seems like a 'wontfix'. 

Thanks for the work and replys. :)
