### ISSUE TITLE
BehaviorSubject emitting NULL before the Errors(bug?)

### ISSUE THREAD

**Issue by shinayser** [ReactiveX/rxdart#320]
Check this code:

```dart
void main(List<String> arguments) async {
  var subject = BehaviorSubject.seeded("Seed");
  subject.addError("Just an error");

  await Future.delayed(Duration(milliseconds: 1000));

  var firstValue =
      await (subject.onErrorReturn("An error ocurred up there!").first);

  print("Result: ${firstValue}");
}
``` 

The text `An error ocurred up there!` should be printed on the console but it prints `null`, because the BehaviorSuject first transmits a "null" and only after that it transmits the error. This causes the "first" operator to never catch the error. You can check that with the snippet below:

```dart
void main(List<String> arguments) async {
  var subject = BehaviorSubject.seeded("Seed");
  subject.addError("Just an error");

  await Future.delayed(Duration(milliseconds: 1000));

  subject.listen((it) => print("Arrived data first -> $it"),
      onError: (it) => print("Arrived error -> $it"));

  await Future.delayed(Duration(milliseconds: 1000));
}
```

The correct behavior should be: if the latest value was an error, it should be transmitted first instead of the "null". Makes no sense transmitting a NULL before.

**Comment by frankpepermans** [comment]
Yup, seems like the seeded part of BehaviorSubject was not correctly updated regarding the change we did concerning Errors.

Fixed with https://github.com/ReactiveX/rxdart/pull/321

**Comment by shinayser** [comment]
Nice!! Any idea when it will be live on pub.dev?

**Comment by frankpepermans** [comment]
It's on pub right now, 0.22.2
