### ISSUE TITLE
Unable to Reset ScanStreamTransformer Accumulator

### ISSUE THREAD

**Issue by webtfdml** [ReactiveX/rxdart#324]
I'm trying to use RXDart with Flutter to feed search results to a ListView.builder.

I desperately need to figure out how to reset a ScanStreamTransformer.

I pipe my searchFetcher into my searchOutput like so:

` _searchFetcher.stream.transform(_resultsTransformer()).pipe(_searchOutput);`

And I have my resultsTransformer defined as follows:

```
_resultsTransformer() {
    return ScanStreamTransformer(
      (Map<int, SingleResultModel> cache, SingleResultModel result, index) {
        cache[index] = result;
        return cache;
      },
      <int, SingleResultModel>{},

    );
}
```

At the top of the screen I have a "filter" option that allows users to narrow their search a bit. The problem is that when I do this, there's no way to reset the accumulator on the scanstreamtranformer.

Things I've tried:

- Resetting the cache to null. This gets rid of the results, but the index value doesn't reset. My ListView tries to access elements that don't exist.

- Draining the streams. Flutter prevents you from doing this after you bind the transformer.

- Closing the streams. Flutter prevents you from doing this after you bind the transformer.

- Instantiating a new ScanStreamTransformer. Flutter won't let me unbind the old one or bind the new one.

I've been using clunky work-arounds, but I'm at my wits end with this. Any help would be greatly appreciated.

**Comment by brianegan** [comment]
In my opinion, it sounds like you need to deliver MORE or DIFFERENT information to the `scan` function as part of the data that you're emitting.

Right now, you're only emitting a `SingleResultModel` to the `scan` function. That `SingleResultModel` does not give you the information you need to know if you need to wipe the cache and start fresh. 

Instead, you might need to emit something like a `CacheUpdate` in place of the `SingleResultModel`. That `CacheUpdate` could be a class that has these fields:

```
class CacheUpdate {
  final SingleResultModel result;
  final bool resetData;
}
```

Then the function you're providing to the `scan` transformer can look at the data contained in the event and know if it needs to reset it or not. There's no way to externally reset the accumulated value.
