### ISSUE TITLE
AsyncSubject does not exists

### ISSUE THREAD

**Issue by skyberk** [ReactiveX/rxdart#328]
This subject useful when i make single request and return same response to observers. But i do not see in subjects.dart file. This subject is missing or in development progress ?

**Comment by frankpepermans** [comment]
Hi there!

No, it does not exist, and although it would be straightforward to add it, the same functionality can easily be achieved today:

```
var subject = PublishSubject<int>();
var asyncStream = Observable.from(subject.last);

subject..add(1)..add(2)..add(3); // will only emit 3 on listen
```

... I'll keep it in mind to add it as a proper `AsyncSubject `later

**Comment by skyberk** [comment]
Hi @frankpepermans thanks for suggestion but i think your sample code looking like replaysubject(1) . Also PublishSubject cannot emit data after completion.

**Comment by frankpepermans** [comment]
@skyberk A `ReplaySubject` replays everything from the start.

If you use `.last`, like in the snippet, you get a `Future<T>` which completes with the very last value once `done` is fired.

This is basically what `AsyncSubject` is: http://reactivex.io/RxJava/javadoc/rx/subjects/AsyncSubject.html

**Comment by lukepighetti** [comment]
rxdart seems to take a keep it simple approach and ignore sugary classes which I personally appreciate but I know other's have different opinions
