### ISSUE TITLE
whereType is not working in release mode

### ISSUE THREAD

**Issue by illia-romanenko** [ReactiveX/rxdart#335]
Hi 👋,

I'm having weird issue when whereType is not working in **release** mode in the app I'm currently working (where ofType seems to be working just fine). Here is what it outputs in the logs:

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: type ‘OneDatabaseAction' is not a subtype of type ‘TwoDatabaseAction' of 'myAction'
#0      DatabaseEpics._someEpic.<anonymous closure> (package:secret/common/database/database_epics.dart:0)
#1      SwitchMapStreamTransformer._buildTransformer.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rxdart/src/transformers/switch_map.dart:47)
#2      _rootRunUnary (dart:async/zone.dart:1132)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764)
#8      _StreamController._add (dart:async/stream_controller.dart:640)
#9      _StreamController.add (dart:async/stream_controller.dart:586)
#10     WhereTypeStreamTransformer._buildTransformer.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rxdart/src/transformers/where_type.dart:50)
#11     _rootRunUnary (dart:async/zone.dart:1132)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#15     _DelayedData.perform (dart:async/stream_impl.dart:591)
#16     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707)
#17     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667)
#18     _rootRun (dart:async/zone.dart:1120)
#19     _CustomZone.run (dart:async/zone.dart:1021)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#22     _rootRun (dart:async/zone.dart:1124)
#23     _CustomZone.run (dart:async/zone.dart:1021)
#24     _CustomZone.runGuarded (dart:async/zone.dart:923)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)

Any ideas?

**Comment by frankpepermans** [comment]
Hi there,

Can you provide a reproducible example?

**Comment by hoc081098** [comment]
same issue, freeze UI flutter app when running  in profile or release mode :(

**Comment by illia-romanenko** [comment]
Maybe we need to put that to flutter_redux_epics as I wasn't able to reproduce this one without epics but since it crashes in rxdart I thought it's the better place. Let me know if you think otherwise.


```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_redux/flutter_redux.dart';
import 'package:redux/redux.dart';
import 'package:redux_epics/redux_epics.dart';
import 'package:rxdart/rxdart.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class OneAction {}

class TwoAction {}

class ThirdAction {}

class AppState {}

AppState _reduceNavigateTo(AppState oldState, OneAction action) {
  print(action);
  return oldState;
}

Stream<dynamic> _availablePackagesEpic(
    Stream<dynamic> actions, EpicStore<AppState> store) {
  return new Observable(actions)
      .whereType<OneAction>()
      .switchMap((OneAction requestAction) {
    return new Observable.timer(ThirdAction(), new Duration(seconds: 1));
  });
}

Stream<dynamic> _availablePackagesEpic2(
    Stream<dynamic> actions, EpicStore<AppState> store) {
  return new Observable(actions)
      .whereType<TwoAction>()
      .switchMap((TwoAction requestAction) {
    return new Observable.timer(ThirdAction(), new Duration(seconds: 1));
  });
}

class _MyHomePageState extends State<MyHomePage> {
  final Store<AppState> store = Store<AppState>(
      TypedReducer<AppState, OneAction>(_reduceNavigateTo),
      initialState: AppState(),
      middleware: [
        EpicMiddleware(
            combineEpics([_availablePackagesEpic, _availablePackagesEpic2])),
      ]);

  @override
  void initState() {
    super.initState();
    store.dispatch(OneAction());
    store.dispatch(TwoAction());
  }

  @override
  Widget build(BuildContext context) {
    return StoreProvider(
        store: this.store,
        child: Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text(
                  '',
                ),
              ],
            ),
          ),
        ));
  }
}

```

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.3
  redux_epics: 0.11.0
```

```
To quit, press "q".
I/flutter (32698): Instance of 'OneAction'
E/flutter (32698): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'OneAction' is not a subtype of type 'TwoAction' of 'requestAction'
E/flutter (32698): #0      _availablePackagesEpic2.<anonymous closure> (package:untitled32/main.dart:0)
E/flutter (32698): #1      SwitchMapStreamTransformer._buildTransformer.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rxdart/src/transformers/switch_map.dart:47)
E/flutter (32698): #2      _rootRunUnary (dart:async/zone.dart:1132)
E/flutter (32698): #3      _CustomZone.runUnary (dart:async/zone.dart:1029)
E/flutter (32698): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
E/flutter (32698): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
E/flutter (32698): #6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
E/flutter (32698): #7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764)
E/flutter (32698): #8      _StreamController._add (dart:async/stream_controller.dart:640)
E/flutter (32698): #9      _StreamController.add (dart:async/stream_controller.dart:586)
E/flutter (32698): #10     WhereTypeStreamTransformer._buildTransformer.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rxdart/src/transformers/where_type.dart:50)
E/flutter (32698): #11     _rootRunUnary (dart:async/zone.dart:1132)
E/flutter (32698): #12     _CustomZone.runUnary (dart:async/zone.dart:1029)
E/flutter (32698): #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
E/flutter (32698): #14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
E/flutter (32698): #15     _DelayedData.perform (dart:async/stream_impl.dart:591)
E/flutter (32698): #16     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707)
E/flutter (32698): #17     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667)
E/flutter (32698): #18     _rootRun (dart:async/zone.dart:1120)
E/flutter (32698): #19     _CustomZone.run (dart:async/zone.dart:1021)
E/flutter (32698): #20     _CustomZone.runGuarded (dart:async/zone.dart:923)
E/flutter (32698): #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
E/flutter (32698): #22     _rootRun (dart:async/zone.dart:1124)
E/flutter (32698): #23     _CustomZone.run (dart:async/zone.dart:1021)
E/flutter (32698): #24     _CustomZone.runGuarded (dart:async/zone.dart:923)
E/flutter (32698): #25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
E/flutter (32698): #26     _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter (32698): #27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
E/flutter (32698): 

```

**Comment by frankpepermans** [comment]
@hoc081098 Are you using redux_epics as well?

The `whereType` handler is quite straightforward really, see https://github.com/ReactiveX/rxdart/blob/master/lib/src/transformers/where_type.dart#L43

I didn't run the provided snippet yet, but it seems it would only pass this check if `T` were `dynamic` somehow.

Any thoughts here @brianegan ?

**Comment by hoc081098** [comment]
@frankpepermans I don't use `redux_epics` but same approach like `redux_epics` [Reproduce code](https://github.com/hoc081098/load_more_flutter_BLoC_pattern_RxDart_and_RxRedux/blob/05935bb49203fe9aad22d04bf4ae8fd61d666208/lib/pages/comics/comics_effects.dart#L26)
I don't know what reason but `ofType` is working properly so far

**Comment by frankpepermans** [comment]
Merged the fix from @hoc081098 to master.

Regarding the original solution in whereType, this seems like a Flutter bug, would you mind sharing more specific info?

i.e.
- confirmed that it happens in production builds only
- Flutter/Dart versions
- target platforms (iOS/Android/both)

thanks!

**Comment by illia-romanenko** [comment]
Here is my flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.4 18E227, locale en-UA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

I think it affects both ios & android

Hope that helps!

**Comment by bogdannedelcu** [comment]
Any idea when it will land in STABLE nranch?

**Comment by brianegan** [comment]
@bogdannedelcu This was shipped as part of rxdart `0.22.3`

**Comment by bogdannedelcu** [comment]
👍

**Comment by bogdannedelcu** [comment]
thank you very much @brianegan  for the fast response. Indeed it is a working fix. I am surprised to see this code works in debug but not in release. Does the "as" operator in Dart behave differently in debug then release? Should we file an issue in DART repo?

**Comment by frankpepermans** [comment]
The *only* place the old implementation fails, is in aot builds it seems, others (dev, dartdevc, dart2js) are fine.

So yes, we'll open an issue for it
