### ISSUE TITLE
.take(1) from broadcast -> single subscription stream

### ISSUE THREAD

**Issue by lukepighetti** [ReactiveX/rxdart#341]
I have a situation where I have a PublishSubject and I'm `.take(1)` and I need that Observable to close when it's done emitting that value. It apparently is not cancelling after that value, allegedly because it's coming from a broadcast stream. What is someone to do in this scenario? Is there an opportunity for a PR here?

**Comment by frankpepermans** [comment]
You could do something like this:
`Observable.fromFuture(stream.first);`

If you cannot control `stream` here, then at least your new `Observable` will emit `done` after the first `event` is received?

**Comment by brianegan** [comment]
Could you also describe the behavior you're seeing a bit more and what you'd like to see? This test checks whether a `take(1)` observable is closed (emitsDone) after it emits the first event, and seems to be working.

```dart
test('take emitsDone after emitting 1 element', () {
    final subject = PublishSubject<int>();
    final observable = subject.take(1);

    scheduleMicrotask(() => subject.add(1));

    expect(observable, emitsInOrder(<dynamic>[1, emitsDone]));
  });
```

**Comment by lukepighetti** [comment]
I believe my issue was unrelated to `rxdart` so I will close, thanks!
