### ISSUE TITLE
'Notification' is define in 'flutter/src/widgets/notification_listener.dart'

### ISSUE THREAD

**Issue by read0nly** [ReactiveX/rxdart#344]
hello, the type of 'Notification' is define in rxdart/src/utils/notification.dart.But it is aleardy define in flutter/src/widgets/notification_listener.dart.Now I can't both export 'package:flutter/material.dart' and 'package:rxdart/rxdart.dart'.

**Comment by hoc081098** [comment]
Use alias import or hide or show

**Comment by frankpepermans** [comment]
As pointed out, there's other ways to deal with duplicate names in libraries, there's no need to address rxdart here.
