### ISSUE TITLE
Add "asBehaviorSubject()" extension

### ISSUE THREAD

**Issue by shinayser** [ReactiveX/rxdart#355]
Hey guys!

I am playing with extensions here and was thinking about that one that could be usefull:

```dart
extension BehaviorSubjectExtensions<T> on Stream<T> {
  
  BehaviorSubject<T> asBehaviorSubject([bool pipe = false]) {
    final subject = BehaviorSubject<T>();

    if (pipe) {
      this.pipe(subject);     
    } else {
      subject.addStream(this);
    }

    return subject;
  }
  
}


main() {
  var subject = Stream.value(10).asBehaviorSubject();
}


```

What do you guys think?

**Comment by hoc081098** [comment]
I think it is not usefull :(

**Comment by shinayser** [comment]
Of course my sample is not usefull, it is just a demonstration on how to use it.
But thinking on real world problems it can bring some nice usability to users. 
On my opinion, every extension is usefull.

**Comment by hoc081098** [comment]
Yes. Extensions are usefull and flexible

**Comment by shinayser** [comment]
Ok, you got a point.
I am closing this issue since then. Thanks @brianegan.
