### ISSUE TITLE
sort() operator

### ISSUE THREAD

**Issue by Arxing** [ReactiveX/rxdart#362]
I know i can sort by this way:
```dart
  observable
    .toList()
    .asObservable()
    .map((list) => list..sort(comparator))
    .flatMap((list) => Observable.fromIterable(list));
```
but these codes are lengthy.

if these codes can simplify to this:
```dart
observable
    .sort(comparator);
```
it will be simple and intuitive.

**Comment by hoc081098** [comment]
Using extension method :)
```dart
extension SortExtension<T> on Observable<T> {
    Observable<T> sort(comparator) {
         return observable
            .toList()
            .asObservable()
            .map((list) => list..sort(comparator))
            .flatMap((list) => Observable.fromIterable(list));
    }
}
```

**Comment by Arxing** [comment]
thank you!
it's so cool!
dart will support extension method!

**Comment by hoc081098** [comment]
Dart 2.6.0-dev will support extension methods 😺

**Comment by frankpepermans** [comment]
The only way I could see this, from an API standpoint, would be:

`Future<List<T>> sort([int compareHandler(T a, T b)]);`

...which would actually be a shorthand for:

```
var list = await stream.toList();

list.sort();
// or Observable.fromIterable(list..sort());
```
...but (as you said)  with extension methods, I don't see it as a must for rxdart :)
