### ISSUE TITLE
how to close result state?

### ISSUE THREAD

**Issue by bhanuka96** [ReactiveX/rxdart#374]
When tap result, how to close state?

**Comment by frankpepermans** [comment]
Hi there,

Can you provide a bit more info?
I.e. a code snippet

**Comment by hoc081098** [comment]
i don't understand what you mean

**Comment by bhanuka96** [comment]
I have a form. I need to store user select result. And also I need to change state. How do I do it? Is it possible to change state here?

```
 onTap: () => showItem(context, item),

void showItem(BuildContext context, SearchResultItem item) {
//change state
}
```

**Comment by hoc081098** [comment]
I think it is good :))

**Comment by brianegan** [comment]
Looks good, @bhanuka96! Gonna close this out for now, please let us know if you need more help :)
