### ISSUE TITLE
Combine  connected query

### ISSUE THREAD

**Issue by kepuza** [ReactiveX/rxdart#375]
```
Stream matchCombine;

@override
  void initState() {
    super.initState();
    matchCombine = _firestore
        .collection('matches')
        .where('match', arrayContains: widget.firebaseUser.uid)
        .where('status', isEqualTo: true)
        .snapshots()
        .map((convert) {
      return convert.documents.map((f) {

        Observable<Matches> match = f.reference
            .snapshots()
            .map<Matches>((document) => Matches.fromMap(document.data));

        Observable<User> user = _firestore
            .collection("users")
            .document(
            widget.firebaseUser.uid == f.data['matcher'] ? f.data['pairer'] : f.data['matcher'])
            .snapshots()
            .map<User>((document) => User.fromMap(document.data));

        Observable<Message> message = _firestore
            .collection('matches')
            .document(f.documentID)
            .collection("chat")
            .orderBy('date', descending: true)
            .limit(1)
            .snapshots()
            .expand((snapShot) => snapShot.documents)
            .map<Message>((document) => Message.fromMap(document.data));

        return Observable.combineLatest3(match, user, message,
                (matches, user, message) => CombinedStream(matches, user, message));
      });
    }).map((convert) {
      return Observable.combineLatestList(convert);
    });
  }
```

How can i combine this. 
I've searched everywhere but couldn't find a solution.
Where am I doing wrong

**Comment by frankpepermans** [comment]
`Observable.combineLatest` will give you an Observable (a Stream if you will),
but you use `map` throughout:

`map` is used to transform something synchronously, for example map a `User` object to it's first and last name -> `users.map((user) => '${user.first} ${user.last}')`

If however you need to do something `async`, then use `asyncMap` for Futures and use `flatMap` or `switchMap` for Streams

**Comment by kepuza** [comment]
i think im doing wrong this part

```
map((convert) {
      return Observable.combineLatestList(convert);
    });
```

**Comment by brianegan** [comment]
Yep, that's exactly right, @kepuza!

What you need to do is replace that `map` with either `flatMap` or `switchMap`, depending on the functionality you're looking for.

`flatMap` will subscribe to each `Observable.combineLatestList(convert)` and emit it's results until it shuts down. `switchMap` will subscribe to each `Observable.combineLatestList(convert)` and cancel the previous subscription if the `converter` function is called again.

**Comment by kepuza** [comment]
> Evet, bu kesinlikle doğru Kepuza !
> 
> Yapmanız gereken , aradığınız işlevselliğe bağlı olarak bunu veya `map`ile değiştirmektir .`flatMap``switchMap`
> 
> `flatMap`Her birine abone olacak `Observable.combineLatestList(convert)`ve kapanana kadar sonuçlarını yayacaktır. işlev tekrar çağrılırsa `switchMap`her birine abone olur `Observable.combineLatestList(convert)`ve önceki aboneliği iptal eder `converter`.

but i dont know how can i do before im doing with angular like that 

```
mergeMap(observables => {
            return observables.length > 0 ? combineLatest(observables) : of([]);
        })
```

now i cant do it with rxdart

**Comment by kepuza** [comment]
https://gist.github.com/kepuza/a9afd994aea032a6c55fbfcd5d932619

im doing with angular and works perfectly but i cant convert this for flutter

**Comment by brianegan** [comment]
You'd change:

```
.map((convert) {
      return Observable.combineLatestList(convert);
    });
```

to

```
.flatMap((observables) {
      return observables.length > 0 ? Observable.combineLatestList(observables) : Observable.just([]);
    });
```

**Comment by kepuza** [comment]
> You'd change:
> 
> ```
> .map((convert) {
>       return Observable.combineLatestList(convert);
>     });
> ```
> 
> to
> 
> ```
> .flatMap((observables) {
>       return observables.length > 0 ? Observable.combineLatestList(observables) : Observable.just([]);
>     });
> ```

Give me error "The method 'flatMap' isn't defined for the class 'Stream'

**Comment by brianegan** [comment]
Ah, my bad. You'd also need to convert your firebase Stream into an Rx observable. So, for `flatMap` to work, you'd also need to do this:

old:
```
_firestore
        .collection('matches')
        .where('match', arrayContains: widget.firebaseUser.uid)
        .where('status', isEqualTo: true)
        .snapshots()
 ```

new:

```
Observable(_firestore
        .collection('matches')
        .where('match', arrayContains: widget.firebaseUser.uid)
        .where('status', isEqualTo: true)
        .snapshots())
 ```

Note: You won't need to do this in the next version of RxDart!

**Comment by kepuza** [comment]
> Observable(

Thanks you so much you are best 

im doing no problem i think its working i add StreamBuilder 

```
debugPrint(snapshot.toString());
debugPrint(snapshot.data.toString());
```

its give me error 

`I/flutter (29827): AsyncSnapshot<List<CombinedStream>>(ConnectionState.active, null, type '_MapStream<DocumentSnapshot, Matches>' is not a subtype of type 'Observable<Matches>')`

my full code like that

https://gist.github.com/kepuza/1803f62ef20172fc5f90546225b03b6b

**Comment by brianegan** [comment]
This is a standard Dart `TypeError`

Change:

```
Observable<Matches> match = f.reference
```

to

```
Stream<Matches> match = f.reference
```

You'll need to do this for your `User` and `Message` Streams as well.

`f.refernece...` returns a Stream, not an Observable. You only need to wrap a Stream in an Observable when you want to access the extra operators RxDart provides, such as the `flatMap` operator mentioned above. 

In this case, you don't need any of those operators, you can just use the raw `Stream` class.

**Comment by kepuza** [comment]
> Bu standart bir dart `TypeError`
> 
> Değişiklik:
> 
> ```
> Observable<Matches> match = f.reference
> ```
> 
> için
> 
> ```
> Stream<Matches> match = f.reference
> ```
> 
> Bunu hem sizin `User`hem de `Message`Streams için yapmanız gerekecektir .
> 
> `f.refernece...`Gözlemlenebilir değil bir Akış döndürür. `flatMap`Yukarıda belirtilen işleç gibi, RxDart'ın sağladığı ek işleçlere erişmek istediğinizde yalnızca bir Akışı Gözlemlenebilir'e sarmanız gerekir .
> 
> Bu durumda, bu operatörlerden hiçbirine ihtiyacınız yok, sadece ham `Stream`sınıfı kullanabilirsiniz .


I thank you very, very much. I'm updateing my code like that
https://gist.github.com/kepuza/1803f62ef20172fc5f90546225b03b6b

but in StreamBuilder debugPrint show nothing

`debugPrint(snapshot.data.toString());`

**Comment by brianegan** [comment]
It's probably a good idea to debugPrint the `snapshot` on each frame to see if an error or done event got sent through for some reason.

**Comment by kepuza** [comment]
> It's probably a good idea to debugPrint the `snapshot` on each frame to see if an error or done event got sent through for some reason.
> 
> Do not put the debugPrint inside any other logic, just to see what it's delivering. That should point you to the problem


thank you very much I succeeded with your help

**Comment by brianegan** [comment]
Cool, good luck and have fun :)

**Comment by kepuza** [comment]
i will ask you last question how can i sort this stream like message.date

my old code 

```
mergeMap(observables => {
            return observables.length > 0 ? combineLatest(observables) : of([]);
        }), tap(m => {
            if (m.length > 0) {
                return m.sort((a, b) => {
                    const aD = a.date ? a.date.toDate() : a.matchDate.toDate();
                    const bD = b.date ? b.date.toDate() : b.matchDate.toDate();
                    return bD < aD ? -1 : 1;
                });
            } else {
                return m;
            }
        })
```

whats the tap operator for dart ?

**Comment by kepuza** [comment]
> Cool, good luck and have fun :)

i will ask you last question how can i sort this stream like message.date

my old code

```
mergeMap(observables => {
            return observables.length > 0 ? combineLatest(observables) : of([]);
        }), tap(m => {
            if (m.length > 0) {
                return m.sort((a, b) => {
                    const aD = a.date ? a.date.toDate() : a.matchDate.toDate();
                    const bD = b.date ? b.date.toDate() : b.matchDate.toDate();
                    return bD < aD ? -1 : 1;
                });
            } else {
                return m;
            }
        })
```

whats the tap operator for dart ?

**Comment by brianegan** [comment]
`doOnX` -- `doOnData`, etc

**Comment by kepuza** [comment]
Hey brianegan i cant do it with doOnData sorting. My last code like that and works perfectly but i need sorting this list like message.date i do it like that but give me error what can i do for sorting

```
_matchCombine = Observable(_firestore
            .collection('matches')
            .snapshots())
        .map((convert) {
      return convert.documents.map((f) {
        Stream<Matches> match = Observable.just(f)
            .map<Matches>((document) => Matches.fromSnapshot(document));

        Stream<User> user = _firestore
            .collection("users")
            .document(..)
            .snapshots()
            .map<User>((document) => User.fromSnapshot(document));

        Stream<Message> message = _firestore
            .collection('matches')
            .document(f.documentID)
            .collection("chat")
            .orderBy('date', descending: true)
            .limit(1)
            .snapshots()
            .expand((snapShot) => snapShot.documents)
            .map<Message>((document) => Message.fromSnapshot(document));

        return Observable.combineLatest3(match, user, message,
            (matches, user, message) => CombinedStream(matches, user, message));
      });
    }).switchMap((observables) {
      return observables.length > 0
          ? Observable.combineLatestList(observables)
          : Observable.just([]);
    }).doOnData((onData) {
      return onData.sort((CombinedStream a, CombinedStream b) {
        return a.message.date.compareTo(b.message.date);
      });
    });
```

**Comment by kepuza** [comment]
> `doOnX` -- `doOnData`, etc

How can i do it this is the last one left for me to finish

**Comment by brianegan** [comment]
Ah, that would just be a normal `map` then.

```dart
.map((combinedStreams) {
      return combinedStreams.sort((CombinedStream a, CombinedStream b) {
        return a.message.date.compareTo(b.message.date);
      });
    })
```

**Comment by kepuza** [comment]
> Ah, that would just be a normal `map` then.
> 
> ```dart
> .map((combinedStreams) {
>       return combinedStreams.sort((CombinedStream a, CombinedStream b) {
>         return a.message.date.compareTo(b.message.date);
>       });
>     })
> ```

This is give me error "The return type 'void' isn't a List<CombinedStream>, as defined by anonymous closure"

**Comment by kepuza** [comment]
> > Ah, that would just be a normal `map` then.
> > ```dart
> > .map((combinedStreams) {
> >       return combinedStreams.sort((CombinedStream a, CombinedStream b) {
> >         return a.message.date.compareTo(b.message.date);
> >       });
> >     })
> > ```
> 
> This is give me error "The return type 'void' isn't a `List<CombinedStream>`, as defined by anonymous closure"

**Comment by frankpepermans** [comment]
Try using double dots, i.e. list..sort

**Comment by kepuza** [comment]
> Try using double dots, i.e. list..sort

This error fixed but have new error "The function expression type 'int Function (CombinedStreaam, CombinedStream)' isn't of type 'int Function (dynamic, dynamic)'. This means its parameter or return type doesn't match what is expected. Consider changing parameter  type(s) or returned type(s). "

**Comment by kepuza** [comment]
i fixed this problem now my code like that but now its give me error

The following NoSuchMethodError was thrown building StreamBuilder<List<CombinedStream>>(dirty, state: _StreamBuilderBaseState<List<CombinedStream>, AsyncSnapshot<List<CombinedStream>>>#e11b9):
The getter 'length' was called on null.
Receiver: null
Tried calling: length


```
.switchMap((observables) {
      return observables.length > 0
          ? Observable.combineLatestList(observables)
          : Observable.just([]);
    }).map((combinedStreams) {
      if(combinedStreams.length > 0) {
        return combinedStreams..sort((a, b) {
          return a.message.date.compareTo(b.message.date);
        });
      } else {
        return combinedStreams;
      }
    });
```

**Comment by kepuza** [comment]
> i fixed this problem now my code like that but now its give me error
> 
> The following NoSuchMethodError was thrown building StreamBuilder<List>(dirty, state: _StreamBuilderBaseState<List, AsyncSnapshot<List>>#e11b9):
> The getter 'length' was called on null.
> Receiver: null
> Tried calling: length
> 
> ```
> .switchMap((observables) {
>       return observables.length > 0
>           ? Observable.combineLatestList(observables)
>           : Observable.just([]);
>     }).map((combinedStreams) {
>       if(combinedStreams.length > 0) {
>         return combinedStreams..sort((a, b) {
>           return a.message.date.compareTo(b.message.date);
>         });
>       } else {
>         return combinedStreams;
>       }
>     });
> ```

I put debugPrint in streamBuilder

`debugPrint(snapshot.toString());`

Its says this error

`I/flutter ( 9319): AsyncSnapshot<List<CombinedStream>>(ConnectionState.active, null, Unsupported operation: Cannot modify an unmodifiable list)`

I think we cant map and sorting in combineLatestList inside

**Comment by brianegan** [comment]
Heya @kepuza -- Our bad -- we're emitting a list that can't be modified. You can convert that into a list that can be modified using `List.from(combinedStreams)..sort(...)`

I'm gonna go ahead and cut this thread off for now... many of these errors are pretty standard coding errors / easy to Google. If we can help with Rx specific behavior, please let us know!
