### ISSUE TITLE
Bug in BehaviorSubject when sync true

### ISSUE THREAD

**Issue by smiLLe** [ReactiveX/rxdart#376]
Hi, i just found a (for me) weird behavior when using two sync BehaviorSubject.

This code is working:
```dart
  final sub = BehaviorSubject<int>(sync: true);
  final sub2 = BehaviorSubject<int>(sync: true);
  sub.listen((data) {
    sub2.add(data);
  });
  sub.add(1);
  expect(sub2.value, 1);
```

This code does not work as it seems that the Stream become async when using a seed.
```dart
  final sub = BehaviorSubject<int>.seeded(null, sync: true);
  final sub2 = BehaviorSubject<int>.seeded(null, sync: true);
  sub.listen((data) {
    sub2.add(data);
  });
  sub.add(1);
  expect(sub2.value, 1); /// value is null (or the seeds value)
```

Am i missing something here?

**Comment by brianegan** [comment]
Heya @smiLLe -- That's a good catch, and I've debated removing the `sync` property from `BehaviorSubject`. The way BehaviorSubject works in RxDart is a bit tricky to get right and requires some events be delivered async.

I wanted to keep `sync` in there in hopes I could find a way to make it work in a truly synchronous way, but haven't found one just yet.

**Comment by smiLLe** [comment]
@brianegan  thanks for your answer :) By looking into the code i already thought that it is not "meant" to be used sync. 
That is, why I closed this issue.
