### ISSUE TITLE
Q: what is the equivalent of Observable.Create in other RX ecosystems?

### ISSUE THREAD

**Issue by kentcb** [ReactiveX/rxdart#377]
Hi,

I've not been able to find an equivalent to [Observable.Create](http://reactivex.io/documentation/operators/create.html) in rxdart. Is there one?

**Comment by hoc081098** [comment]
Stream generator async*

**Comment by kentcb** [comment]
@hoc081098 Can you elaborate? How would I use this to create an observable that wraps a `Timer`? i.e. it needs to start the timer when a listener attaches, and cancel the timer when the listener detaches.

I came up with this code whilst playing around this morning:

```dart
    Timer timer;
    final subject = PublishSubject<String>(
      onListen: () {
        timer = Timer.periodic(const Duration(seconds: 30), (_) {});
      },
      onCancel: () {
        timer?.cancel();
      },
    );
    final stopSignal = Observable<dynamic>(actions).whereType<TearDown>();
    return subject.takeUntil(stopSignal);
```
It's pretty awful.

**Comment by hoc081098** [comment]
Use built-in constructor https://api.flutter.dev/flutter/dart-async/Stream/Stream.periodic.html :))

**Comment by hoc081098** [comment]
In my opinion, using StreamController<T> is right way to community between callback world and reactive world 😂

**Comment by kentcb** [comment]
@hoc081098 Yeah, it wasn't a great example because my intention is to evenually _not_ use `Stream.periodic`. Why? See [here](https://github.com/ReactiveX/rxdart/issues/322) and [here](https://github.com/flutter/flutter/issues/40074).

I feel like I'm going around in circles trying to use rxdart and I suspect this will have been my last attempt :(

**Comment by frankpepermans** [comment]
This looks to be more of a test / fakeAsync related issue though, or do you suspect it's something to do with takeUntil?

**Comment by kentcb** [comment]
@frankpepermans I _initially_ thought it was rxdart, hence opening the issue on this repo. However, when I looked further into it a subsequent time, I was able to reproduce it using only Flutter and `TestAsync`, so I do believe the issue lies there. But all the same, the only use case I have for rxdart right now is an Epic in Redux middleware to manage timers, and I can't because of this problem.

**Comment by talamaska** [comment]
@kentcb Why you need timers in redux and epics

**Comment by kentcb** [comment]
@talamaska Because I want my middleware to periodically dispatch an action.

**Comment by frankpepermans** [comment]
Not sure how we can help here unfortunately,

Maybe try a different approach, use a normal Timer to set a single interval, and keep an isClosed flag next to it.
When it fires, do your action and if isClosed is still false, set up a new single Timer?

If you can toggle isClosed externally, then your custom Stream should stop correctly?

**Comment by kentcb** [comment]
@frankpepermans Your workaround is exactly what I'm doing :) However, the app I'm working on has need for this kind of periodic behavior in several different places, so I was hoping to one day leverage Epics to simplify things.

I'm happy to close this issue, by the way, as I know it's not really an rxdart issue.

**Comment by frankpepermans** [comment]
Dunno if this will 100% work (I've never intercepted timers via Zone).
But with this snippet, you could still keep using Stream.periodic and get a reference to the created Timer:

```
import 'dart:async';

void main() async {
  final stream = Stream.periodic(const Duration(seconds: 1), (i) => i);
  final wrappedStream = PeriodicTimerWrapper(stream);

  wrappedStream.listen(print);
  // as opposed to stream.listen(print);

  await Future.delayed(const Duration(seconds: 3));

  wrappedStream.close();
}

class PeriodicTimerWrapper<T> {
  final Stream<T> _stream;
  Timer _timer;

  PeriodicTimerWrapper(this._stream);

  StreamSubscription<T> listen(void Function(T) onListen) =>
      runZoned(() => _stream.listen(onListen),
          zoneSpecification: ZoneSpecification(
              createPeriodicTimer: (_, ZoneDelegate parent, Zone zone,
                      Duration period, void f(Timer timer)) =>
                  _timer = parent.createPeriodicTimer(zone, period, f)));

  void close() => _timer?.cancel();
}
```
