### ISSUE TITLE
ValueStream not exported?

### ISSUE THREAD

**Issue by frank06** [ReactiveX/rxdart#378]
I'm on `0.23.0-dev.2`, super useful extensions!

I'd like my methods to return streams of type `ValueStream` (that interface perfectly describes what I want to expose), but that doesn't seem to be exported in the base barrel file.

If I try to import it directly (`import 'package:rxdart/src/streams/value_stream.dart';`) then I get a warning for trying to import an implementation.

```
Don't import implementation files from another package.dart(implementation_imports)
```

**Comment by hoc081098** [comment]
Fixed by https://github.com/ReactiveX/rxdart/commit/eeaf3af5fd5fa039d345e7e9b01683806ef4c315

**Comment by brianegan** [comment]
Sorry about that, @frank06! Had a CI failure that I needed to work out before publishing. That's all fixed and `ValueStream` is now exported as part of `0.23.0-dev.3`! Thanks so much for reporting the issue :)

**Comment by frank06** [comment]
Ah, no worries @brianegan and thank you for these great extensions!
