### ISSUE TITLE
Replacement for Observable?

### ISSUE THREAD

**Issue by PritishSawant** [ReactiveX/rxdart#380]
Now that `Observable` is removed from latest version of `rxdart`, we can use Dart's lang `Stream` instead of it, but what if I use methods like `combineLatest2` with `Stream`. I tried  `rxdart_codemod`  but it doesn't seem to do anything with the breaking changes.

**Comment by hoc081098** [comment]
Rx.combineLatest2

**Comment by hoc081098** [comment]
abstract class Rx contains static methods: zip, combineLatest, concat, merge, race, etc

**Comment by PritishSawant** [comment]
@hoc081098 Thanks a lot
