### ISSUE TITLE
Add `mapNotNull` operator

### ISSUE THREAD

**Issue by shinayser** [ReactiveX/rxdart#382]
Sometimes is interesting to perform complex operations inside map and for some values you just want to ignore.
Today we need to methods to acomplish this: `map` and a `where` afterwards, like:

```dart
enum Result { IS_EVEN, IS_MULTIPLE_OF_3 }

void main(List<String> arguments) async {
  var stream = Stream.fromIterable([0, 1, 2, 3, 4, 5]);

  stream.map((value) {
    if (value.isEven) {
      return Result.IS_EVEN;
    }

    if (value % 3 == 0) {
      return Result.IS_MULTIPLE_OF_3;
    }

    return null;
  }).where((it) => it != null);
}
```

To avoid an addition of a new trasnformer onto the stream chain we could just implement an `mapNotNull` method, that will ignore the elements that returned null through the `convert` lambda.

**Comment by hoc081098** [comment]
Seem like to `compactMap` in `rxswift`

**Comment by shinayser** [comment]
Yes, but I think the naming that rxswift has chosen is pretty bad. `mapNotNull` is more intuitive and is also used by other libraries (even Kotlin uses it)

**Comment by frankpepermans** [comment]
Now that we have extension methods, creating this operator using map and where is easily done.

Not sure if this warrants a specific rxdart entry, but that's just my opinion of course.

**Comment by shinayser** [comment]
@frankpepermans As you can see on @hoc081098 comment, other implementations has such method. So i think it could be nice we having one like that.

**Comment by frankpepermans** [comment]
I know, but it feels like API clutter honestly.

And why only mapNotNull? Basically you open the door for asyncMapNotNull, expandNotNull etc...

And then you are only covering null, I try to avoid null at all times, but sometimes use where to filter out InvalidState for example.

On phone so forgive the horrible formatting, but basically you just do

extension MapNotNullExtension on Stream

Stream mapNotNull(mapper) => map(mapper).where((event) => event != null);

**Comment by shinayser** [comment]
I understand your point.
Like I said, the problem is not the ease of use. Extensions will make it easy to workaround, yes. 
What I am pointing here is that this way, there will be **one more** transformer in the streaming chain.

And when you talk about avoind null at all times, actually it is not all that valid, even with the NNBD feature just around the corner. Null **is** an important state.

But like I said, I understand your point. Lets leave this issue open for others to contribute with more ideas and toughts!

**Comment by frankpepermans** [comment]
You could avoid null altogether in your example if you would want to, use flatMap and a Stream generator method.

Then only yield when you have an actual value.

I.e. stream.flatMap((value) async* {
if (value.isEven) yield value

**Comment by shinayser** [comment]
My sample was just for clarification purposes. My real world example is actaully big and complex to post  here.

**Comment by shinayser** [comment]
In my case, my stream is a byte stream. It emits List<int>.
In its `map` call, I have to mount my object and only after mounting it I am able to know if it is an inportant object or not. This is why I return null for thoses cases.

**Comment by frankpepermans** [comment]
Is it safe to return null here?
Someone else could read null as a failed decoded Object here, not a rejected one?

If flatMap and yield is not an option, maybe a partition would be, splitting the Stream into accepted and rejected Streams?

**Comment by frankpepermans** [comment]
Here's partition from rxjs https://www.learnrxjs.io/operators/transformation/partition.html

In Dart we could create a PartitionStream on return, which has for example a left and right Stream (naming could be better here), in any case, 2 Streams, created by the splitter Function provided.

Would this help?

**Comment by shinayser** [comment]
Actually the flatMap works yes! I tested few months ago but it was emiting nulls also, don't know why. But I tested right know and it worked properly. Thanks for the insight!

About the partition I don't know if it will be a fine addition without a destructuring feature embedded into the language.

**Comment by frankpepermans** [comment]
Yeah, pretty much the reason why we don't have partition yet, glad this works for you!

Come to think of it, using asyncExpand over flatMap might be better here, both will work though.

**Comment by hoc081098** [comment]
```dart
extension PartitionExt<T> on Stream<T> {
  /// Splits the this Observable into two, one with values that satisfy a
  /// predicate, and another with values that don't satisfy the predicate.
  List<Observable<T>> partition(bool predicate(T event)) =>
      ParititonUtil.parititon(this, predicate);
}

class ParititonUtil {
  /// Splits the [source] Observable into two, one with values that satisfy a
  /// [predicate], and another with values that don't satisfy the [predicate].
  static List<Observable<T>> parititon<T>(
    Observable<T> source,
    bool predicate(T event),
  ) {
    bool Function(T) not(bool test(T event)) => (event) => !test(event);
    if (source.isBroadcast) {
      return <Observable<T>>[
        source.where(predicate),
        source.where(not(predicate)),
      ];
    } else {
      final shared = source.share();
      return <Observable<T>>[
        shared.where(predicate),
        shared.where(not(predicate)),
      ];
    }
  }
}

```

**Comment by hoc081098** [comment]
extension MapNotNullExtension<T> on Stream<T> {
  Stream<R> mapNotNull<R>(R Function(T) mapper) {
    return transform(
      StreamTransformer<T, R>.fromHandlers(
        handleData: (value, sink) {
          final mappedValue = mapper(value);
          if (mappedValue != null) {
            sink.add(mappedValue);
          }
        }
      )
    );
  }
}

**Comment by hoc081098** [comment]
See #548
