### ISSUE TITLE
ZipStream erases stream types

### ISSUE THREAD

**Issue by klemen-forstneric** [ReactiveX/rxdart#386]
```
final a = BehaviorSubject<String>();
final b = BehaviorSubject<int>();
      
Rx.zip2(a, b, (x, y) { return null; });
```

The types of `x` and `y` seem to be `dynamic`. Is this by design?

**Comment by frankpepermans** [comment]
The types work the other way around,

If you for example pass a Function with
String a, int b

Then you are required to provide a Stream<String> and Stream<int> respectively.

**Comment by klemen-forstneric** [comment]
@frankpepermans, whoa that was a fast reply, thank you! 😄Okay, I understand. Is this just how Dart works or does it somehow make sense for RxDart to do it this way?

**Comment by frankpepermans** [comment]
Tbh I would expect Dart to pick up the Type from either the generic Stream Type, or the Function property Type.

But it doesn't obviously :/

I'll mess around with the signature later, dunno if it'll work tho.

**Comment by brianegan** [comment]
Hey -- I double checked the types and unfortunately there's not much we can do here :/ It's actually a known limitation with the Dart language. 

https://github.com/dart-lang/sdk/issues/37863

Kind of a bummer, but one of those times you'll have to explicitly add typing to the Constructor.
