### ISSUE TITLE
[Question] Different Debounce Duration depending on Event

### ISSUE THREAD

**Issue by ahawlitschek** [ReactiveX/rxdart#392]
I got a question regarding debounce. 

#168 and #220 are discussing a debounce selector. 
But for now, I wasn't able to achieve this behavior.

Could someone provide an example please?

Best regards
Adria

**Comment by frankpepermans** [comment]
Sure, there's debounce and debounceTime.

Using the first, simply return a timed Stream, based on the event's value if needed: https://github.com/ReactiveX/rxdart/blob/master/lib/src/transformers/backpressure/debounce.dart
