### ISSUE TITLE
CombineLatest doesn't work with different TextInputType 

### ISSUE THREAD

**Issue by keezysilencer** [ReactiveX/rxdart#394]
I am trying to validate an ID that consist of text and numbers and a PIN which is numbers only. 
Rx.combineLatest2 work only when both TextInputType is number but not when there are different.

**Comment by frankpepermans** [comment]
would you mind sharing some code?

thanks!

**Comment by keezysilencer** [comment]
Flutter code 
`Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 24),
                child: Text('Akwaaba Biom!',
                    style: TextStyle(
                      fontSize: 24,
                      fontWeight: FontWeight.w800,
                    )),
              ),
              StreamBuilder<String>(
                  stream: _bloc.userID,
                  builder: (context, snapshot) {
                    return TextField(
                      keyboardType: TextInputType.visiblePassword, //TextInputeType is different from _bloc.pin
                      onChanged: _bloc.userIDChanged,
                      decoration: InputDecoration(
                        border: UnderlineInputBorder(),
                        labelText: "User ID",
                        errorText: snapshot.error,
                      ),
                    );
                  }),
              StreamBuilder<String>(
                  stream: _bloc.pin,
                  builder: (context, snapshot) {
                    return Padding(
                      padding: const EdgeInsets.symmetric(vertical: 24),
                      child: TextField(
                        obscureText: _bloc.obscurePinText,
                        keyboardType: TextInputType.number, // TextInputeType is different from _bloc.user
                        onChanged: _bloc.pinChanged,
                        decoration: InputDecoration(
                          border: UnderlineInputBorder(),
                          suffixIcon: IconButton(
                              icon: _bloc.obscurePinText
                                  ? Icon(Icons.enhanced_encryption)
                                  : Icon(Icons.lock_open),
                              onPressed: (snapshot.hasError || snapshot.hasData)
                                  ? () => _bloc
                                      .changePinObscureText()
                                  : null),
                          labelText: "PIN",
                          errorText: snapshot.error,
                        ),
                      ),
                    );
                  }),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: <Widget>[
                  FlatButton(
                    onPressed: () =>
                        Navigator.of(context).pushNamed(Routes.forgotPIN),
                    child: Text('Forgot PIN?',
                        style: TextStyle(
                            color: Theme.of(context).primaryColor,
                            fontWeight: FontWeight.w500)),
                  ),
                  StreamBuilder<bool>(
                      stream: _bloc.loginCheck,
                      builder: (context, snapshot) {
                        return RaisedButton(
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(20)),
                            child: Text('Log In'),
                            textColor: Colors.white,
                            onPressed: snapshot.hasData
                                ? () => showDialog(
                                    context: context,
                                    builder: (BuildContext context) {
                                      _bloc.request();
                                      return LoadingPage(
                                        bloc: _bloc,
                                      );
                                    })
                                : null);
                      }),
                ],
              )
            ],
          ),`

Bloc code
`class LoginBloc {
final UserIDValidator  _userIDValidator = UserIDValidator();
 final PinValidator _pinValidator = PinValidator();

 final BehaviorSubject _userController = BehaviorSubject<String>();
final BehaviorSubject _pinController = BehaviorSubject<String>();
  

Stream<String> get userID =>
      _userController.stream.transform(_userIDValidator.validateID());
Stream<String> get pin =>
      _pinController.stream.transform(_pinValidator.validatePin());
 
// The problem is here! 
Stream<bool> get loginCheck =>
      Rx.combineLatest2(userID, pin, (id, p) => true);

  void request() async {
    // authentcate user
  }
}`

The code works when both TextInputType is set to 
TextInputType.number.

Thanks!

**Comment by frankpepermans** [comment]
So combineLatest2 will only trigger when both source Streams have emitted.

Did you try something like Rx.combineLatest2(userID.doOnData(_) => print('userId'), pin.doOnData((_) => print('pin')), (id, p) => true); ?

If you see both userId and pin logged, try adding another doOnData on the combined Stream itself.

**Comment by keezysilencer** [comment]
`Rx.combineLatest2(userID.doOnData() => print('userId'), pin.doOnData(() => print('pin')), (id, p) => true)` didn't work.

**Comment by keezysilencer** [comment]
I am able to log the userId and pin but nothing shows for the combined Stream itself.
`Rx.combineLatest2(userID.doOnData((u) {
      print(u);
    }), pin.doOnData((k){
      print(k);
    }), (id, p) => true).doOnData((z) {
      print(z);
      return true;
    });`

**Comment by frankpepermans** [comment]
Hmmm are you sure nothing else is going on?

This is a minimal test which works, 2 emitting Streams and events are combined.

```
var streamA = Stream<int>.fromIterable([1, 2, 3]);
  var streamB = Stream<int>.fromIterable([4, 5, 6]);

  Rx.combineLatest2(streamA, streamB, (int a, int b) => [a, b])
      .doOnData(print)
      .listen(null);
```

**Comment by keezysilencer** [comment]
The streams work perfectly when the TextInputType is the same. But it doesn't work when they are different. it doesn't emit any value
