### ISSUE TITLE
Give us Subject

### ISSUE THREAD

**Issue by passsy** [ReactiveX/rxdart#4]
`StreamController` is a good replacement for javas `PublishSubject`. But there is no replacement for the `BehaviorSubject` in rxdart.

Or I'm to stupid to get the latest emitted item of a `StreamController`

**Comment by frankpepermans** [comment]
Having Subjects would be nice, however I'm focusing more on getting the Observable side as feature complete as possible.

Not that it's of the table though, once Observables are fleshed out more it is the next logical step.

**Comment by dustinlessard-wf** [comment]
+1

**Comment by frankpepermans** [comment]
In progress,
see https://github.com/frankpepermans/rxdart/blob/master/lib/src/subject

**Comment by brianegan** [comment]
In progress. Closing this ticket in favor of more specific items.
