### ISSUE TITLE
Unable to update Observable.combineLatest2 to new syntax

### ISSUE THREAD

**Issue by tapizquent** [ReactiveX/rxdart#401]
I have tried everything possible trying to get the same functionality from Observable.combineLastest2 to the new Stream extensions but have not been able to do anything.

What is the correct way to update this?

**Comment by hoc081098** [comment]
Rx.combibeLatest2

**Comment by tapizquent** [comment]
WOW! Thank you so much! I did not find this in the docs. Should probably be more exposed. Thank you for your help!

**Comment by frankpepermans** [comment]
Just out of curiosity, where did you look?

We try to document as much as possible obviously :)
