### ISSUE TITLE
exhaustmap documentation page 404 not found

### ISSUE THREAD

**Issue by dafinoer** [ReactiveX/rxdart#403]
hi guys, i want to read exhaustmap doc, but page 404 not found.

https://pub.dev/documentation/rxdart/latest/rx/SwitchMapExtension/rx/ExhaustMapExtension/exhaustMap.html

**Comment by hoc081098** [comment]
https://pub.dev/documentation/rxdart/latest/rx/ExhaustMapExtension/exhaustMap.html
