### ISSUE TITLE
add doOnSubscribe like Rxjava?

### ISSUE THREAD

**Issue by Icyoung** [ReactiveX/rxdart#406]
I want a api to do something or operate the stream before the stream emitting.
If rxdart has similar api, please tell me, thanks.

**Comment by RollyPeres** [comment]
@Icyoung there's a `doOnListen` available on streams

**Comment by Icyoung** [comment]
I want to check login form before doing a http request in a chain code.

**Comment by Icyoung** [comment]
> @Icyoung there's a `doOnListen` available on streams

But when doOnListen is called, the Steam is emitted? Maybe? I am not sure.

**Comment by RollyPeres** [comment]
It's called when the subscription is created.
