### ISSUE TITLE
isListen

### ISSUE THREAD

**Issue by flashiran1** [ReactiveX/rxdart#409]
hi 

please add isListen for stream.listen

**Comment by frankpepermans** [comment]
What do you mean?

A `boolean` flag to determine whether or not a `Stream` is being listened to?

i.e.

```
var stream = Stream.empty();

print(stream.hasListener); // false

stream.listen(null);

print(stream.hasListener); // true
```

Like that?

**Comment by frankpepermans** [comment]
Closing as we didn't get more feedback, reopen if needed

**Comment by flashiran1** [comment]
That's right, thank you
