### ISSUE TITLE
Why are RepeatStream's description and RetryStream's description the same?

### ISSUE THREAD

**Issue by Funncy** [ReactiveX/rxdart#416]
I had a question reading the Rxdart api document. The two explanations are the same, but the actual function behaviors are different.

`RepeatStream repeats the specified number of times` and
`RetryStream tries until succeeded.`

The code works like that, but the explanation is the same, so it's confusing.

```Dart
RepeatStream<T> class
Creates a Stream that will recreate and re-listen to the source Stream the specified number of times until the Stream terminates successfully.
```

```Dart
RetryStream<T> class
Creates a Stream that will recreate and re-listen to the source Stream the specified number of times until the Stream terminates successfully.
```

**Comment by frankpepermans** [comment]
Probably a case of the ol' copy/paste syndrome, 
`repeat` indeed simply repeats n-times
`retry` only when `Exception`s occur

**Comment by Funncy** [comment]
thank you!
