### ISSUE TITLE
mapping a value stream to a new value stream synchronously

### ISSUE THREAD

**Issue by khainke** [ReactiveX/rxdart#419]
i don't know whether this is even feasible, but ideally I would like to have the ability to map a value stream in such a way to a new value stream, that the last value is instantly mapped to the created stream and not after a delay. Example code:

```dart
test('shareValue does not work synchronously', () async {
      BehaviorSubject<int> controller = BehaviorSubject.seeded(1);
      ValueStream<int> stream = controller.stream;

      int plusOne(int i) => i + 1;

      ValueStream<int> streamPlusOneNaive = stream.map(plusOne).shareValue();
      ValueStream<int> streamPlusOneSeeded = stream.hasValue
          ? stream.map(plusOne).shareValueSeeded(plusOne(stream.value))
          : stream.map(plusOne).shareValue();

      StreamSubscription<int> streamPlusOneNaiveSubscriber = streamPlusOneNaive.listen((_){});
      StreamSubscription<int> streamPlusOneSeededSubscriber = streamPlusOneSeeded.listen((_){});

      // ideally value would be available here without manual seeding it
      expect(stream.value, equals(1));
      expect(streamPlusOneNaive.value, isNull);
      expect(streamPlusOneSeeded.value, equals(2));

      await Future.delayed(Duration(milliseconds: 5));

      expect(stream.value, equals(1));
      expect(streamPlusOneNaive.value, equals(2));
      expect(streamPlusOneSeeded.value, equals(2));

      controller.add(2);

      // ideally values would be mapped here already
      expect(stream.value, equals(2));
      expect(streamPlusOneNaive.value, equals(2));
      expect(streamPlusOneSeeded.value, equals(2));

      await Future.delayed(Duration(milliseconds: 5));

      expect(stream.value, equals(2));
      expect(streamPlusOneNaive.value, equals(3));
      expect(streamPlusOneSeeded.value, equals(3));

      streamPlusOneNaiveSubscriber.cancel();
      streamPlusOneSeededSubscriber.cancel();
    });
```

**Comment by frankpepermans** [comment]
Not easy I'm afraid,
`refCount` is an extension method on `Stream`, and we have no way of knowing if a `Stream` is either sync or async...

When using `refCount`, we switch to a `BehaviorSubject` underneath obviously, but given that we don't know if the `Stream` is sync or async, we've chosen to always make the underlying controller async by default.

Ideally, this should fix things the way you'd want it, without a seeded hack:
`BehaviorSubject<int> controller = BehaviorSubject.seeded(1, true);`

If you try that in your test, you'll see that it does push event sync now *afterwards*, i.e. =>
```
controller.add(2);

      // ideally values would be mapped here already
      expect(stream.value, equals(2));
      expect(streamPlusOneNaive.value, equals(2));
      expect(streamPlusOneSeeded.value, equals(2));
```

would need to be

```
controller.add(2);

      // ideally values would be mapped here already
      expect(stream.value, equals(2));
      expect(streamPlusOneNaive.value, equals(3));
      expect(streamPlusOneSeeded.value, equals(3));
```

**Comment by frankpepermans** [comment]
I'll look into the first part of the test (i.e. make value available immediately after `shareValue`).
We use an async underlying `Subject`, which probably should be sync ones instead. (as we do with our Transformers).

The second part can be fixed if you use
`BehaviorSubject.seeded(1, sync: true);`

**Comment by frankpepermans** [comment]
I've had a closer look,
`BehaviorSubject` uses `startWith` when being listened to:
- `startWith` uses a `scheduleMicrotask` when inside `onListen`, to add that first event
- if we instead add right away, without the short delay, we get an exception deep down in the SDK

This is something we cannot fix:
(omit `scheduleMicrotask` in `startWith` and run behavior_subject.test)

Following the stack trace:
- They use a late subscription internally
- The subscription is being paused upon adding the first event
- When this pause happens, the subscription is not yet created

**Comment by khainke** [comment]
Thank you for your effort, for sharing these insights and for creating the pull request. Looking forward to it.

**Comment by frankpepermans** [comment]
We've added sync support now for Subjects, which should solve already a few things in the example.

Reopen if needed

**Comment by cedvdb** [comment]
I'm still having issues with this but I'm not using a `seeded` behavior subject, although the a value has been set by the time the mapped stream is accessed.

It would seem to me that a test should be added in the test cases provided by the PR, where a `BehaviorSubject` (unseeded) value has been set and a `map` function is used.

IE:

```dart
test('shareValue does not work synchronously', () async {
    BehaviorSubject<int> controller = BehaviorSubject(sync: true);
    ValueStream<int> stream = controller.stream;

    int plusOne(int i) => i + 1;

    ValueStream<int> streamPlusOne = stream.map(plusOne).shareValue();

    controller.add(1);

    StreamSubscription<int> streamPlusOneNaiveSubscriber = streamPlusOneNaive.listen((_){});
    StreamSubscription<int> streamPlusOneSeededSubscriber = streamPlusOneSeeded.listen((_){});

    expect(stream.value, equals(1));
    expect(streamPlusOneNaive.value, equals(2));
    expect(streamPlusOneSeeded.value, equals(2));

    streamPlusOneNaiveSubscriber.cancel();
    streamPlusOneSeededSubscriber.cancel();
  });

```
