### ISSUE TITLE
Question:Is it correct to show Observable on the readme 

### ISSUE THREAD

**Issue by fabiancrx** [ReactiveX/rxdart#422]
As of 0.23 Observable class was removed and extension methods in the Stream API were added. Despite that in the readme shows a comparison table between Observable and Stream, which in my understanding is not correct as previously stated and can mislead newcomers.
So If I'm not mistaken (Please correct me if I am ) the whole Observable vs Stream table should be refactored to show the current state of the library which would be your regular vanila dart streams and the Rx extended ones.

**Comment by frankpepermans** [comment]
I think it's still relevant, no?

We still have Rx in name, and the api is close to what you'd expect Rx to be.

To me, it seems many newcomers from other languages just discover rxdart and do not really bother learning Dart Streams, which indeed have unexpected behaviour. The table is there to kind of warn people about the differences.

**Comment by fabiancrx** [comment]
Yes, I do think it's still pretty relevant too.
What i failed to see was it was referencing just Rx observables not rxdart, and hence my misunderstanding. My confusion arose with the 0.22 to 0.23 change. 
prior to 0.23
As the library implemented an Observable class I thought the comparison table was between the rxdart implementation of observable and streams. 
after 0.23
With the changes introduced in 0.23 and dropping the observable class altogether i thought the table information was obsolete (as observable is not available in rxdart ).
Thanks for your quick reply and awesome work, I see now that the information is correct and wiil close the issue.
