### ISSUE TITLE
shareValue() only works if source is declared as a field

### ISSUE THREAD

**Issue by RollyPeres** [ReactiveX/rxdart#435]
Hey folks,

It appears that `shareValue()` only works for sources declared as fields.
If the source is either a method or just a getter, the sync `value` returns null. 
You can find a quick gist featuring this behavior at 
https://gist.github.com/RollyPeres/b39034b1abcb55eda0605eae072b3be1
Tested on `rxdart: ^0.23.1`.

Would like to hear your thoughts @frankpepermans , @brianegan . Cheers!

**Comment by frankpepermans** [comment]
In both cases where you get null, it is because you expect value to be available right after you create the `Stream`, which is not the case.

The click handler calls a method and a getter here, so they only get created within that Event handler. 
The first is actually already initialised beforehand, and has its event played already.

You effectively do:
`print(Stream.fromIterable([1]).shareValue().value);`

Whereas in the one that works, you do:
```
/// before clicking
final s = Stream.fromIterable([1]).shareValue();
/// some time later, onClick
print(s.value);
```
If you must have the value available in sync, then try
`BehaviorSubject.seeded(1)` for example

**Comment by RollyPeres** [comment]
That makes sense, thanks @frankpepermans !

I'm actually trying to avoid using a `BehaviorSubject` since I need to share a firebase stream in a repository class where I don't want to force a dispose, since it shouldn't have a dispose.

Basically I want something like:

```
Result get result => result$.value;
ValueStream<Result> get result$ => _firestore...shareValue();
```
This obviously doesn't work. Any alternative to this that I might be missing ?

**Comment by frankpepermans** [comment]
eagerly create the `Stream`, then inside the `getter`, return the reference to that `Stream`:

```
final ValueStream<Result> _result$ = _firestore...shareValue();
ValueStream<Result> get result$ => _result$;
```

But don't really on `.value` as a source of truth, you cannot control when exactly events play inside the `Stream`, so value is untrustworthy really.
`Stream`s are async, I'd stick to working async with them as well.

**Comment by RollyPeres** [comment]
I was also thinking about that, but I have an injected dependency on `Firestore` , `final Firestore _firestore;`

So I can't do `final ValueStream<Result> _result$ = _firestore...shareValue();` since only static members can be accessed in initializers.

**Comment by brianegan** [comment]
There's also `shareValueSeeded`, which will let you populate the `ValueStream` with an initial value. Does that work?

**Comment by RollyPeres** [comment]
@brianegan it doesn't. All it seems to do is share this seed value and that's it.

**Comment by hoc081098** [comment]
```dart

**Comment by hoc081098** [comment]
```dart

**Comment by hoc081098** [comment]
You can use `publishValue` together with `connect`: `publishValue` creates ValueStream and use `connect` to subscribe to source stream only once
```dart
class Repo {
  final ValueStream<Result> result$;
  Repo(Firestore firestore):
     result$ = firestore.getStream$().publishValue()..connect();
```

**Comment by frankpepermans** [comment]
@RollyPeres shareValue actually pipes through a BehaviorSubject under the hood.

Wouldn't you always need a dispose anyway?

**Comment by RollyPeres** [comment]
@hoc081098 that's a neat way of doing it, appreciate a lot your input. The downside is that `connect()` returns a `StreamSubscription` which should probably be cancelled, so back to square 1 :)

@frankpepermans was hoping I won't need it. Something around the lines of `.shareReplay(1)` from rxjs.

**Comment by frankpepermans** [comment]
Well, you could use a BehaviorSubject and auto close the subject using onCancel.

OnCancel is invoked when all subscriptions call cancel. Downside is that you can no longer subscribe at a later time of course.

**Comment by RollyPeres** [comment]
That's an interesting approach. I'll give it a shot. Thanks all for great insights!

**Comment by frankpepermans** [comment]
No prob!

@brianegan maybe we could add an autoClose extension? Which basically adds an onClose handler that closes the Subject when triggered?

**Comment by brianegan** [comment]
> Well, you could use a BehaviorSubject and auto close the subject using onCancel.
  >
  > OnCancel is invoked when all subscriptions call cancel. Downside is that you can no longer subscribe at a later time of course.

This is actually exactly what `shareValue` already does for ya! You can see the docs for an explanation and example: 

https://pub.dev/documentation/rxdart/latest/rx/ConnectableStreamExtensions/shareValue.html

You can see how it's implemented here: 
https://github.com/ReactiveX/rxdart/blob/master/lib/src/streams/connectable_stream.dart#L155
https://github.com/ReactiveX/rxdart/blob/master/lib/src/streams/connectable_stream.dart#L262

**Comment by brianegan** [comment]
Looking more closely at the root problem, I definitely support @hoc081098's suggestion, combined with a normal `shareValue` would work best:

```
class Repo {
  final ValueStream<Result> result$;
  Repo(Firestore firestore):
     result$ = firestore.getStream$().shareValue();
}
```

That would convert the firebase stream into a Broadcast ValueStream that will close down after all subscribers have stopped listening.

**Comment by RollyPeres** [comment]
You're absolutely right @brianegan 
```
class Repo {
  final ValueStream<Result> result$;
  Repo(Firestore firestore):
     result$ = firestore.getStream$().shareValue();
}
```
This would end up making the sync `value` available through `result$` and `refCount` should take care of cancelling!

**Comment by frankpepermans** [comment]
Oh indeed, forgot that `shareValue` calls `refCount` :)
