### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mohammadne** [ReactiveX/rxdart#437]
what I have is 2 seperate streams. and I have implementation like this :
```
Stream<bool> get isLastMediaItem {
    return Rx.combineLatest2<List<MediaItem>, MediaItem, bool>(
      queueStream,
      mediaItemStream,
      (queue, mediaItem) => mediaItem == queue.last,
    );
  }
}
```
what I want is to avoid unnecessary changes means my 2 streams may emit different values but may the evaluate to be false , I want that it compare last value and current value and only if they were not the same value , add that value to the stream , because adding same values causes an unnecessary rebuild in my ```StreamBuilder```

one possible way is to create my custom streamController and do that check but I wonder to know is that feature , implemented in RxDart ?

**Comment by mohammadne** [comment]
means rxdart add a value only if it has a diffrent value to pervious stream.value.
maybe it should use BehavioralSubject.

**Comment by hoc081098** [comment]
@mohammadne You can use [`distinct` operator](https://api.dart.dev/stable/2.7.2/dart-async/Stream/distinct.html) to skip events if they are equal to the previous data event

**Comment by frankpepermans** [comment]
Distinct is indeed a good option, closing
