### ISSUE TITLE
How to access additional methonds on Streams provided by RxDart in 0.23?

### ISSUE THREAD

**Issue by purplecandy** [ReactiveX/rxdart#438]
This might be a very stupid question but earlier this how I used to define my streams
```
Observable<int> get stream => _controller.stream;
```
and this would give me access to additional methods such as `debounceTime()` etc.
Now in the 0.23 update, they renamed as `ValueStream` and the default  `Stream` but now I can't access any additional methods.

How am I supposed to access them?

Thanks

**Comment by hoc081098** [comment]
Now all methods in `RxDart` are extension methods,  just import `rxdart` and call stream. debounceTime() as usual

**Comment by frankpepermans** [comment]
What @hoc081098 said,

Also, @brianegan made a lovely codemod to facilitate migrating to extension methods, see https://github.com/brianegan/rxdart_codemod
