### ISSUE TITLE
0.24 switchMap causes Bad state: Stream has already been listened to 

### ISSUE THREAD

**Issue by Mike278** [ReactiveX/rxdart#448]
This test passes on 0.23.1 and fails on 0.24 with 'Bad state: Stream has already been listened to.'
```dart
  test('rxdart 0.24 switchMap', () async {
    {
      final a = BehaviorSubject<String>();
      final b = BehaviorSubject<String>();
      final c = a.switchMap((_) => b);
      a.add('a');
      b.add('b');
      expect(await a.first, 'a');
      expect(await a.first, 'a');
      expect(await b.first, 'b');
      expect(await b.first, 'b');
      expect(await c.first, 'b');
      expect(await c.first, 'b');
    }

    {
      final a = db.customSelectQuery("select 'a' as a").map(($) => $.readString('a')).watchSingle();
      final b = db.customSelectQuery("select 'b' as b").map(($) => $.readString('b')).watchSingle();
      final c = a.switchMap((_) => b);
      expect(await a.first, 'a');
      expect(await a.first, 'a');
      expect(await b.first, 'b');
      expect(await b.first, 'b');
      expect(await c.first, 'b');
      expect(await c.first, 'b'); // in rxdart 0.24: Bad state: Stream has already been listened to.
    }
  });
```

The streams in the second example come from the [moor](https://github.com/simolus3/moor) package, and I'm guessing it's specifically [this transformation](https://github.com/simolus3/moor/blob/master/moor/lib/src/runtime/executor/stream_queries.dart#L191) from [this StreamTransformer](https://github.com/simolus3/moor/blob/master/moor/lib/src/utils/start_with_value_transformer.dart) that's causing issues. Since this began after upgrading rxdart I've started by creating an issue in this repo, but I'll create an issue with moor if rxdart is behaving as expected here. Is this the breaking change mentioned [here](https://github.com/ReactiveX/rxdart/blob/master/CHANGELOG.md#0240-dev1)?

**Comment by frankpepermans** [comment]
I'm not familiar with moor, and cannot test your second example as it was posted here.

what do:
- `a.isBroadcast`
- `b.isBroadcast`
- `c.isBroadcast`
give?

**Comment by frankpepermans** [comment]
I was able to recreate your failing test using this:
```
test('rxdart 0.24 switchMap', () async {
    {
      final a = StreamController<String>.broadcast().stream.transform(StartWithValueTransformer(() => 'a'));
      final b = StreamController<String>.broadcast().stream.transform(StartWithValueTransformer(() => 'b'));
      final c = a.switchMap((_) => b);

      expect(await a.first, 'a');
      expect(await a.first, 'a');
      expect(await b.first, 'b');
      expect(await b.first, 'b');
      expect(await c.first, 'b');
      expect(await c.first, 'b');
    }
  });
```
if you omit `switchMap`, for example do final c = a; then it also fails.
looks like a moor issue

**Comment by frankpepermans** [comment]
PS I've read in the moor source code that they prefer not to use rxdart due to it being a large framework, just noting that we provide specific imports as well, just subjects for example.

At compilation time, there is tree shaking as well.

**Comment by Mike278** [comment]
Ah right, I was initially going to submit an issue to moor first so I forgot to expand the repro - glad you were able to make it work though! Thanks for your help narrowing it down, I've opened an issue with moor.
