### ISSUE TITLE
Merge streams and maintain Subject's behaviour

### ISSUE THREAD

**Issue by jaween** [ReactiveX/rxdart#458]
This is a question about the features in this package.

I have two `BehaviorSubjects<int>`, `a` and `b`, as my sources. I would like to have a third `BehaviorSubject<int>`, `c`, which is the combination of `a` and `b`, which emits values in the order that the source streams emit.
For example:
```
a: 8...0...6.......4
b: ............1....
c: 8...0...6...1...4
```

I would like to maintain the `BehaviorSubject` feature that allows a new subscriber to initially receive the latest value (in this case, `4`), and to allow for multiple subscribers (broadcast stream).

The closest solution I have found is the `Rx.merge()` function, which merges an `Iterable` of `Streams` together in the way I'd like, but seems to lose the `BehaviorSubject` feature (doesn't emit the latest value when subscribed to). 

I'm wondering if RxDart has an out-of-the-box way to achieve this. Or should I just create a new composite `BehaviorSubject` that listens to the source streams and manage the subscriptions myself?

**Comment by frankpepermans** [comment]
You can just use Rx.merge().shareValue

**Comment by jaween** [comment]
Thank you very much, this works and it simplifies my code :)
