### ISSUE TITLE
Is there a pagination example for consuming a REST API?

### ISSUE THREAD

**Issue by vinkaga** [ReactiveX/rxdart#460]
I have seen a lot of examples but none of them retrieve data from a backend API and provide those values to the stream. More specifically, I am looking to find
1. How to signal to the stream to fetch more data.
2. How to handle retries if they are needed.

Thanks.

**Comment by hoc081098** [comment]
https://github.com/hoc081098/load_more_flutter_BLoC_pattern_RxDart_and_RxRedux

**Comment by vinkaga** [comment]
Thanks @hoc081098!
