### ISSUE TITLE
CombineLatestStream.list and connectionState

### ISSUE THREAD

**Issue by erf** [ReactiveX/rxdart#461]
I use `CombineLatestStream.list` to combine a set of `ValueStream` and observe that the `AsyncSnapshot.connectionState` changes alot between `waiting` and `active`.

Should it not show `waiting` untill values from all streams are present, and then change to `active`?

**Comment by hoc081098** [comment]
Pass `initialData` into `StreamBuilder`
```dart
final stream$ = Rx.combineLatest([...]).shareValueSeeded(seeded)
StreamBuilder(
  stream: stream$,
  initialData: stream$.value,
  builder: ...
)
```

**Comment by erf** [comment]
Ok, thanks. I will try that later. 

But i could just rather check for snapshot.data != null ?

Snapshot.data ( a list ) is only not null when it has values from all streams?

**Comment by hoc081098** [comment]
Just `shareValueSeeded(null)`, and in `builder`
```dart
List<...> data = snapshot.data;
if (data == null) return Loading();
return ListView(data);
```
