### ISSUE TITLE
Pairwise docs

### ISSUE THREAD

**Issue by feinstein** [ReactiveX/rxdart#466]
Pairwise docs say:

>Emits the n-th and n-1th events as a pair..

But what happens on the first emitted value? Does it wait until the second value arrives and then emits something, so there's a gap? Or does it emit a `List` with just one value?

**Comment by hoc081098** [comment]
> But what happens on the first emitted value? Does it wait until the second value arrives and then emits something, so there's a gap?

From [rxjs.dev](https://rxjs.dev/api/operators/pairwise):
`pairwise` emits on the second and subsequent emissions from the source Observable, but not on the first emission, because there is no previous value in that case.

> Or does it emit a List with just one value?

No. It alway emits a List with a length of 2
