### ISSUE TITLE
BehaviorSubject looping stream without any stream sink

### ISSUE THREAD

**Issue by saravananmnm** [ReactiveX/rxdart#469]
`@override
  Widget getWidget(context, AsyncSnapshot<bool> snapshot) {
    return StreamBuilder(
        stream: homeViewModel.viewStatus.stream,
        builder: (context, AsyncSnapshot<int> snapData) {
          if (snapData.hasData)
            return Scaffold(
                appBar: HomeView.viewIndex == 2
                    ? getAppBar()
                    : getCustomAppBar(),
                drawer: getMenuDrawer(),
                body: Container(child: getNavigationClass(snapData.data)));
          //body: getNavigationClass(1));
          else
            return CustomProgress(
              isTitleRequired: true,
            );
          // body: getNavigationClass(HomeView.viewIndex));
        });
  }
  getCustomAppBar(){
    return CustomAppBar(homeViewModel: homeViewModel,notificationListener: actionViewModel,);
  }`

**Comment by saravananmnm** [comment]
`class CustomAppBar extends StatelessWidget
    implements PreferredSizeWidget, AppbarListener {
  static int count = 0;
  CustomLocationUpdates customLocationUpdates;
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin;
  FirebaseMessaging firebaseMessaging = new FirebaseMessaging();
  BuildContext mContext;
  BaseNavigator navigator;
  NotifyListener notificationListener;

  //var notifyCount = BehaviorSubject<int>();
  var status = BehaviorSubject<bool>();
  CustomSharedPrefs customSharedPrefs;
  LoginRepository loginRepository;
  HomeViewModel homeViewModel;

  CustomAppBar({this.homeViewModel,this.notificationListener}) {
    var container = kiwi.Container();
    loginRepository = container<LoginRepository>();
    customLocationUpdates = container<CustomLocationUpdates>();
    navigator = container<BaseNavigator>();
    customSharedPrefs = container<CustomSharedPrefs>();
    print('Notification called...');
    getNotificationView();
  }

  @override
  Widget build(BuildContext context) {
    mContext = context;
    return PreferredSize(
        child: AppBar(
          elevation: 1.0,
          title: getStatusText(),
          centerTitle: true,
          actions: <Widget>[
           // getLocation()
          ],
          flexibleSpace: CustomAppBarBackground(),
        ),
        preferredSize: Size.fromHeight(50));
  }
  getLocation(){
    return LocationSwitchView(
      customLocationUpdates: customLocationUpdates,
      homeUpdateListener: homeViewModel,
      appbarListener: this,
    );
  }

  getStatusText() {
    return Container(
        child: StreamBuilder(
            stream: status.stream,
            initialData: false,
            builder: (context, AsyncSnapshot<bool> snapshot) {
              if(snapshot.hasData)
              return Container(
                child: Text(
                  snapshot.data
                      ? StringConstant.Available
                      : StringConstant.Offline,
                  style: TextStyle(
                      color: snapshot.data
                          ? ColourConstant.COLOR_BLUE
                          : ColourConstant.COLOR_GREY,
                      fontFamily: ReleaseConstant.OpenSans,
                      fontSize: 18.0),
                ),
              );
              else return Container();
            }));
  }

  /*getNotification() {
    return new Stack(
      alignment: Alignment.center,
      children: <Widget>[
        new Icon(
          Icons.notifications,
          size: 20.0,
        ),
        new Positioned(
          top: 3.0,
          bottom: 3.0,
          child: new Stack(
            children: <Widget>[
              new Icon(
                Icons.brightness_1,
                color: Colors.transparent,
                size: 23.0,
              ),
              new Positioned(
                  top: 1.0,
                  left: 4.0,
                  child: StreamBuilder(
                      stream: notifyCount.stream,
                      builder: (context, snapshot) {
                        if (snapshot.hasData) {
                          return new Text(
                              snapshot.data == 0 ? '' : '${snapshot.data}',
                              style: new TextStyle(
                                  color: ColourConstant.COLOR_WHITE,
                                  fontSize: 11.0,
                                  fontWeight: FontWeight.w500));
                        } else {
                          return Container();
                        }
                      }))
            ],
          ),
        )
      ],
    );
  }*/

  getNotificationView() async {
    await initialize();
  }

  showNotification() async {
    var androidPlatformChannelSpecifies = new AndroidNotificationDetails(
      "CA",
      "Courier Alliance",
      "Courier Alliance",
      importance: Importance.Max,
      groupKey: 'iex',
      groupAlertBehavior: GroupAlertBehavior.Children,
      priority: Priority.High,
      color: Colors.blue,
      autoCancel: true,
      largeIcon: DrawableResourceAndroidBitmap('@mipmap/ic_launcher'),
      icon: '@mipmap/ic_launcher',
    );
    var iOSPlatformChannelSpecifics =
        new IOSNotificationDetails(presentAlert: true);
    var platformChannelSpecifics = new NotificationDetails(
        androidPlatformChannelSpecifies, iOSPlatformChannelSpecifics);
    firebaseMessaging.configure(
        onLaunch: (Map<String, dynamic> msg) {
          print(" onLaunch called ${(msg)}");
        },
        onResume: (Map<String, dynamic> msg) {
          print(" onResume called ${(msg)}");
        },
        onMessage: (Map<String, dynamic> msg) async {
          notificationListener.onNotify();
          print('Started :${DateTime.now().millisecond}');
           count = count + 1;
          // notifyCount.sink.add(count);
          print(" onMessage called ${msg}");
          String val = '';
          val = msg['data']['message'];
          await flutterLocalNotificationsPlugin.show(
              count, 'Courier Alliance', val, platformChannelSpecifics,payload: 'CA');
          print('Displayed :${DateTime.now().millisecond}');
        },
        onBackgroundMessage: myBackgroundMessageHandler);
  }

  Future onDidReceiveLocalNotification(
      int id, String title, String body, String payload) async {
    showDialog(
      context: mContext,
      builder: (BuildContext context) => new CupertinoAlertDialog(
        title: new Text(title),
        content: new Text(body),
        actions: [
          CupertinoDialogAction(
            isDefaultAction: true,
            child: new Text('Ok'),
            onPressed: () async {
              Navigator.of(context, rootNavigator: true).pop();
            },
          )
        ],
      ),
    );
  }

  void initialize() async {
    AndroidInitializationSettings android = new AndroidInitializationSettings(
        '@mipmap/ic_launcher'); //@mipmap/ic_launcher
    IOSInitializationSettings ios = new IOSInitializationSettings(
        onDidReceiveLocalNotification: onDidReceiveLocalNotification);
    var initSettings = new InitializationSettings(android, ios);
    flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();
    flutterLocalNotificationsPlugin.initialize(initSettings);
    firebaseMessaging.requestNotificationPermissions(
        const IosNotificationSettings(sound: true, alert: true, badge: true));
    firebaseMessaging.onIosSettingsRegistered
        .listen((IosNotificationSettings setting) {
      print('IOS Setting Registed');
    });
    showNotification();
  }

  @override
  Size get preferredSize => Size.fromHeight(55);

  @override
  void onStatusUpdate(bool data) {
    status.sink.add(data);
  }
}`

**Comment by saravananmnm** [comment]
lutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
I/flutter ( 9389): Notification called...
E/Dart    ( 9389): ../../third_party/dart/runtime/vm/heap/scavenger.cc: 565: error: Out of memory.
E/DartVM  ( 9389): version=2.8.3 (stable) (Tue May 26 18:39:38 2020 +0200) on "android_ia32"
E/DartVM  ( 9389): pid=9389, thread=9501, isolate=main(0xbddfe700)
E/DartVM  ( 9389): isolate_instructions=c3c52900, vm_instructions=c3c52900
E/DartVM  ( 9389):   pc 0xc3d785ee fp 0xf363d138 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x17675ee
E/DartVM  ( 9389):   pc 0xc3ffc7d1 fp 0xf363d158 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x19eb7d1
E/DartVM  ( 9389):   pc 0xc3c529d7 fp 0xf363d188 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x16419d7
E/DartVM  ( 9389):   pc 0xc3f52063 fp 0xf363d1c8 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x1941063
E/DartVM  ( 9389):   pc 0xc3f5361a fp 0xf363d2c8 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x194261a
E/DartVM  ( 9389):   pc 0xc3f53cb6 fp 0xf363d308 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x1942cb6
E/DartVM  ( 9389):   pc 0xc3f4669f fp 0xf363d388 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x193569f
E/DartVM  ( 9389):   pc 0xc3f44ddb fp 0xf363d3d8 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x1933ddb
E/DartVM  ( 9389):   pc 0xc3f44c39 fp 0xf363d438 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x1933c39
E/DartVM  ( 9389):   pc 0xc3cfe7c4 fp 0xf363d488 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x16ed7c4
E/DartVM  ( 9389):   pc 0xc3d4fc4d fp 0xf363d4d8 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x173ec4d
E/DartVM  ( 9389):   pc 0xc3f1c110 fp 0xf363d518 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x190b110
E/DartVM  ( 9389):   pc 0xc3cee330 fp 0xf363d578 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x16dd330
E/DartVM  ( 9389):   pc 0xc3ced2cd fp 0xf363d5d8 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x16dc2cd
E/DartVM  ( 9389):   pc 0xc3cecc93 fp 0xf363d638 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x16dbc93
E/DartVM  ( 9389):   pc 0xc3ced39b fp 0xf363d928 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x16dc39b
E/DartVM  ( 9389):   pc 0xc3ffb58a fp 0xf363d9d8 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x19ea58a
E/DartVM  ( 9389):   pc 0xc380bf3b fp 0xf363da08 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x11faf3b
E/DartVM  ( 9389):   pc 0xc380c038 fp 0xf363da78 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x11fb038
E/DartVM  ( 9389):   pc 0xc381a6fe fp 0xf363dac8 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x12096fe
E/DartVM  ( 9389):   pc 0xc381a432 fp 0xf363dae8 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x1209432
E/DartVM  ( 9389):   pc 0xc3818dd4 fp 0xf363dbe8 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x1207dd4
E/DartVM  ( 9389):   pc 0xc3818a71 fp 0xf363dd28 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x1207a71
E/DartVM  ( 9389):   pc 0xc3827679 fp 0xf363de18 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x1216679
E/DartVM  ( 9389):   pc 0xc37d50c4 fp 0xf363de38 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x11c40c4
E/DartVM  ( 9389):   pc 0xc37d7a0a fp 0xf363dea8 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x11c6a0a
E/DartVM  ( 9389):   pc 0xc37d794f fp 0xf363ded8 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x11c694f
E/DartVM  ( 9389):   pc 0xc37ddb5b fp 0xf363def8 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x11ccb5b
E/DartVM  ( 9389):   pc 0xc37ddb89 fp 0xf363df18 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x11ccb89
E/DartVM  ( 9389):   pc 0xed067488 fp 0xf363df48 android::SimpleLooperCallback::handleEvent(int, int, void*)+0x28
E/DartVM  ( 9389):   pc 0xed068415 fp 0xf363e098 android::Looper::pollInner(int)+0x415
E/DartVM  ( 9389):   pc 0xed067f4f fp 0xf363e0d8 android::Looper::pollOnce(int, int*, int*, void**)+0x3f
E/DartVM  ( 9389):   pc 0xe2793781 fp 0xf363e128 ALooper_pollOnce+0x61
E/DartVM  ( 9389):   pc 0xc37dda98 fp 0xf363e148 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x11cca98
E/DartVM  ( 9389):   pc 0xc37d78fd fp 0xf363e168 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x11c68fd
E/DartVM  ( 9389):   pc 0xc37d745d fp 0xf363e188 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x11c645d
E/DartVM  ( 9389):   pc 0xc37dafaa fp 0xf363e1c8 /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so+0x11c9faa
E/DartVM  ( 9389):   pc 0xed29b8e6 fp 0xf363e1e8 /apex/com.android.runtime/lib/bionic/libc.so+0x11a8e6
E/DartVM  ( 9389):   pc 0xed2306a8 fp 0xf363e218 /apex/com.android.runtime/lib/bionic/libc.so+0xaf6a8
E/DartVM  ( 9389): -- End of DumpStackTrace
F/libc    ( 9389): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9501 (18.ui), pid 9389 (.tvs.iex_driver)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2020-06-22 14:37:19+0530
pid: 9389, tid: 9501, name: 18.ui  >>> in.tvs.iex_driver <<<
uid: 10134
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    eax 00000000  ebx 000024ad  ecx 0000251d  edx 00000006
    edi ed28333e  esi f363d0b0
    ebp ef37cad0  esp f363d058  eip ef37cad9
backtrace:
      #00 pc 00000ad9  [vdso] (__kernel_vsyscall+9)
      #01 pc 00092328  /apex/com.android.runtime/lib/bionic/libc.so (syscall+40) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #02 pc 000ad651  /apex/com.android.runtime/lib/bionic/libc.so (abort+193) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #03 pc 016419e3  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #04 pc 01941062  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #05 pc 01942619  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #06 pc 01942cb5  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #07 pc 0193569e  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #08 pc 01933dda  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #09 pc 01933c38  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #10 pc 016ed7c3  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #11 pc 0173ec4c  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #12 pc 0190b10f  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #13 pc 016dd32f  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #14 pc 016dc2cc  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #15 pc 016dbc92  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #16 pc 016dc39a  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #17 pc 019ea589  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #18 pc 011faf3a  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #19 pc 011fb037  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #20 pc 012096fd  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #21 pc 01209431  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #22 pc 01207dd3  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #23 pc 01207a70  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #24 pc 01216678  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #25 pc 011c40c3  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #26 pc 011c6a09  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #27 pc 011c694e  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #28 pc 011ccb5a  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #29 pc 011ccb88  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #30 pc 00018487  /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+39) (BuildId: 288ba3aff5b46dbd7e74be954af88b83)
      #31 pc 00019414  /system/lib/libutils.so (android::Looper::pollInner(int)+1044) (BuildId: 288ba3aff5b46dbd7e74be954af88b83)
      #32 pc 00018f4e  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+62) (BuildId: 288ba3aff5b46dbd7e74be954af88b83)
      #33 pc 00013780  /system/lib/libandroid.so (ALooper_pollOnce+96) (BuildId: 2b4362d3e0db6d6e8fbea7ad8414fbae)
      #34 pc 011cca97  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #35 pc 011c68fc  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #36 pc 011c645c  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #37 pc 011c9fa9  /data/app/in.tvs.iex_driver-4pAUcEPOEKPWFpngrFqcDw==/lib/x86/libflutter.so (BuildId: 30dba9f3961f0a1f2f1f5d22ea6d814b6dcd165f)
      #38 pc 0011a8e5  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+53) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #39 pc 000af6a7  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+71) (BuildId: 76290498408016ad14f4b98c3ab6c65c)

**Comment by saravananmnm** [comment]
rxdart: ^0.24.1

C:\Saravanan\Flutter_Sdk\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18362.900], locale en-IN)
    • Flutter version 1.17.2 at C:\Saravanan\Flutter_Sdk\flutter
    • Framework revision 5f21edf8b6 (4 weeks ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

**Comment by saravananmnm** [comment]
This issue not happens, if i run via terminal command. But when i run via Run or Debug button from Android studio it's crashed.

**Comment by saravananmnm** [comment]
any other solutions?

**Comment by saravananmnm** [comment]
i cant able to check debug mode any more. in terminal doesnt have any debug run option.

**Comment by hoc081098** [comment]
Too much information 🧠 🧠 🧠
Please provide the code that reproduces your problem and format it using:
~~~text
```dart
Your code here
```
~~~

**Comment by frankpepermans** [comment]
Agreed,

try to isolate the issue and please provide cleanly formatted code, there's not much we can investigate without that.
