### ISSUE TITLE
BehaviorSubject's stream.first Future never completes if the controller was started non-seeded

### ISSUE THREAD

**Issue by andreyeurope** [ReactiveX/rxdart#473]

**Comment by andreyeurope** [comment]
If needed, I can provide code to reproduce this.

**Comment by hoc081098** [comment]
That is default behavior of `Stream.first`

**Comment by frankpepermans** [comment]
An example is always useful,
BehaviorSubjects will not close after a first triggers, you would need to call close on the subject for complete to happen.

If the stream.first is the only consumer, then cancel should occur though.

**Comment by andreyeurope** [comment]
Note: I'm not a rxdart wizard and this might be the intended behavior, but it still seems really weird for the code to be executed after `await stream.first` to not actually execute.

**Comment by frankpepermans** [comment]
Can you provide an example?

There's not much rxdart going on here, `stream.first` returns a `Future`, the await simply blocks until that future completes.

**Comment by andreyeurope** [comment]
> Can you provide an example?
> 
> There's not much rxdart going on here, `stream.first` returns a `Future`, the await simply blocks until that future completes.

Yeah. I will come with the example a bit later. I don't have access to the code atm.

**Comment by andreyeurope** [comment]
So this is the code I use for controlling the stream:
```
final _searchFilterController = new BehaviorSubject<DoctorSearchFilter>();
  Stream<DoctorSearchFilter> get getSearchFilter => _searchFilterController.stream;
  void Function(DoctorSearchFilter) get _setSearchFilter => _searchFilterController.sink.add;

  Future<void> setCategory(DoctorCategory category) async {
    try {
      print("start");
      final currentFilter = await getSearchFilter.first;
      print("requested");
      _setSearchFilter(DoctorSearchFilter(category, [], Gender.All));
      _setSearchState(BookingSearchState.List);
    } catch (err, st) {
      Crashlytics.instance.recordError(err, st);
      print(err);
    }
  }
```
The code above is from Flutter.

And then, when I trigger the function above, I get the next console output:
```
I/flutter ( 8026): start
I/flutter ( 8026): start
I/flutter ( 8026): start
```

You can see that there are actually 2 `print` method calls, but only one is being executed.
If I modify the `BehaviorSubject` to start as seeded with a `null` value:
```
  final _searchFilterController = new BehaviorSubject<DoctorSearchFilter>.seeded(null);
```

The console output will look like this:
```
I/flutter ( 8026): start
I/flutter ( 8026): requested
I/flutter ( 8026): start
I/flutter ( 8026): requested
```

**Comment by hoc081098** [comment]
Try using `BehaviorSubject.value` instead of

**Comment by frankpepermans** [comment]
Right,
So await effectively blocks your code execution,
You await the first event, but it is only added on the next lines, so nothing happens.

If seeded, then you already have an initial event, triggering first.

You could modify the example to: stream.first.then(...) which is non blocking

**Comment by andreyeurope** [comment]
I see. I was supposing that the stream will return null if no value was propagated.
But I learned that it is not. Will use the `controller.value` from now on to get the current value where possible.

Thank you both @hoc081098 and @frankpepermans.

I will close this, as this was the intended behavior.
