### ISSUE TITLE
Error: The getter 'Observable' isn't defined

### ISSUE THREAD

**Issue by zukijuki** [ReactiveX/rxdart#474]
My project never update for 6 months (written by someone & last build was successful), but today I want to update it but face some errors:

>lib/src/blocs/account/account_bloc.dart:69:33: Error: The getter 'Observable' isn't defined for the class 'AccountBloc'.
>Try correcting the name to the name of an existing getter, or defining a getter or field named 'Observable'.

it seems `Observable` come from **rxdart** library, but I'm not sure about it.

My Code:
```
//Merging username and password streams
Stream<bool> get saveValid => Observable.combineLatest4(nameStream, phoneNumberStream, emailStream, addressStream, (name, phoneNumber, email, address) => true);
```

**rxdart** version in my pubspec.yaml : `rxdart: ">=0.18.1 <0.24.1"`

any idea to solve this?

nb: please let me know if this error does not come from rxdart, I will forward this to flutter repo

**Comment by frankpepermans** [comment]
Observable was removed a while ago when Dart got extension methods,
Check our release notes for more info, in your case, you probably just need to bump up the bloc version.
