### ISSUE TITLE
Callbacks to doOnCancel() and doOnDone() both got invoked after a stream is drained

### ISSUE THREAD

**Issue by torinkwok** [ReactiveX/rxdart#480]
```dart
RangeStream(1, 3)
  .doOnCancel(() => print('Cancelled'))
  .doOnDone(() => print('Done'))
  .doOnError(() => print('Oops'))
  .listen((n) {
    print(n);
  });
```
The output of  the code above is:

```
1
2
3
Canceled
Done
```

Here I expected that only the callback passed to `doOnDone()` was called after the `RangeStream` is drained. However, `doOnCancel()`'s callback also got called.

According to the Rx class documentation:

* [`doOnCancel()`](https://pub.dev/documentation/rxdart/latest/rx/DoExtensions/doOnCancel.html) invokes the given callback function when the stream subscription is cancelled.
* [`doOnDone()`](https://pub.dev/documentation/rxdart/latest/rx/DoExtensions/doOnDone.html) invokes the given callback function when the stream finishes emitting items.

In my opinion, because the stream is done without any problems (i.e. error or manual cancellation), `doOnDone()`'s callback should have been *exclusively* invoked. The fact (correct me if I'm wrong, please) that when stream is done the subscription would be *cancelled* in background (hence `doOnCancel()`) perhaps can justify the inconsistency. But a more concrete and solid explanation would be appreciated.

Thanks.

**Comment by hoc081098** [comment]
* RangeStream includes onDone event, calling onDone is normal behavior.

**Comment by torinkwok** [comment]
@hoc081098 Yes, calling `doOnDone()` is certainly normal. What I consider abnormal is that `doOnCancel()`'s callback also got called in this case.

**Comment by hoc081098** [comment]
@torinkwok. calling `onCancel` is normal behavior.

* According to Dart docs [StreamController](https://api.dart.dev/stable/2.8.4/dart-async/StreamController/StreamController.html), [StreamController.broadcast](https://api.dart.dev/stable/2.8.4/dart-async/StreamController/StreamController.broadcast.html):

> ... onCancel when the listener ends its subscription. If onCancel needs to perform an asynchronous operation, onCancel should return a future that completes when the cancel operation is done.

> ... the onCancel is called when there are no longer any active listeners. If a listener is added again later, after the onCancel was called, the onListen will be called again.

* In other ReactiveX implementations like `RxSwift`: `onCancel` is also known as  `onDispose`, and `onDispose` will be called when `Observable` emits onError or onComplete notification, [Observable Contract](http://reactivex.io/documentation/contract.html):
> Subscribing and Unsubscribing:
> ...
> When an Observable issues an OnError or OnComplete notification to its observers, this ends the subscription.

[RxSwift-Do.swift-L69](https://github.com/ReactiveX/RxSwift/blob/61dabd4edd673a39b40482733cb98e3348358c9c/RxSwift/Observables/Do.swift#L69) , [RxSwift-Do.swift-L108](https://github.com/ReactiveX/RxSwift/blob/61dabd4edd673a39b40482733cb98e3348358c9c/RxSwift/Observables/Do.swift#L108)

**Comment by torinkwok** [comment]
@hoc081098 Now I got it. Thank you very much for your helpful references.
