### ISSUE TITLE
How to implement api call throttling for typeahead autocomplete

### ISSUE THREAD

**Issue by fedotxxl** [ReactiveX/rxdart#482]
Hello. I'm using the following code to make API requests to implement autocomplete:

```
this.query$.throttleTime(Duration(milliseconds: 200), trailing: true).switchMap((q) => _requestSuggestions(q)).listen((items) {
      this.suggestionItems$.add(items);
    });
```

There is a problem with this implementation: at the beginning, it waits 200ms and makes first requests. 

How to implement the same behavior + make the first request instantly? `trailing: false` will not work because it can skip the last request

**Comment by frankpepermans** [comment]
There's many ways to do that, you could use `throttle` instead of `throttleTime` to return a `Stream` with better timings, or:
`Rx.merge([query$.take(1), query$.skip(1).throttleTime(Duration(milliseconds: 200), trailing: true)]);`

**Comment by hoc081098** [comment]
Hi @fedotxxl, I have just opened a PR, so we can use `throttleTime`  like this:
```dart
this.query$
    .throttleTime(Duration(milliseconds: 200), trailing: true, leading: true)
    .switchMap((q) => _requestSuggestions(q))
    .listen((items) {
      this.suggestionItems$.add(items);
    });
```
