### ISSUE TITLE
Cannot use extension methods after flutter & dart upgrade

### ISSUE THREAD

**Issue by f0rx** [ReactiveX/rxdart#494]
**Describe the bug**
After upgrading Flutter and Dart SDK, I can not access the extension methods from rxdart, like `onErrorReturnWith`.

**Steps to reproduce**
1. Import `rxdart` - `import 'package:rxdart/rxdart.dart';`
2. Create a function that returns a stream
```dart
Stream<dynamic> watch() async* {
    return Stream.fromIterable([1, 2, 3])
          .onErrorReturnWith((error) => print("Some error ==> $error"));
}
```
4. Analyzer error
```bash
error: Stream isn't a type. (not_a_type at [f0rx] lib\note\data\repositories\note_repository_impl.dart:56)

error: The method 'onErrorReturnWith' isn't defined for the type 'Stream'. (undefined_method at [f0rx] lib\note\data\repositories\note_repository_impl.dart:64)
```
5. Pubspec.yaml
```yaml
name: Software
description: A new Flutter Application,

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  rxdart: ^0.24.1
  ...
```

**Screenshots**
[rxdart bug - visual](https://firebasestorage.googleapis.com/v0/b/test-lab-03.appspot.com/o/bugs%2Frxdart_bug_1.png?alt=media&token=4ea4e58c-d1b9-43e1-be56-c2d48847e1ad)
[Dart Analysis - visual](https://firebasestorage.googleapis.com/v0/b/test-lab-03.appspot.com/o/bugs%2Frxdart_bug_2.png?alt=media&token=ba781452-400c-4e22-b333-56a21fff8ffc)

![rxdart_bug_2](https://user-images.githubusercontent.com/28307747/91648036-8ce51100-ea5a-11ea-9c36-ea8466e0222d.png)

**Flutter Doctor**
```bash
[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.16299.15], locale en-US)
    • Flutter version 1.21.0-9.2.pre at C:\src\flutter
    • Framework revision 81a45ec2e5 (2 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Anne\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Anne\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.45.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```
#### PS: I discovered the `Stream<T>` extension in file `default_if_empty.dart` (from rxdart) collides with dart:async `Stream` class.

**Comment by hoc081098** [comment]
1. Remove `async*`
2. Return type of callback pass to `onErrorReturnWith` must be not `void` and must be same generic type of `Stream`. That case is `int`
```dart
Stream<dynamic> watch() {
  return Stream.fromIterable([1, 2, 3]).onErrorReturnWith((error) {
    print("Some error ==> $error");
    return -1;
  });
}
```

**Comment by f0rx** [comment]
Permit me to change that.
I don't want to return the stream, rather I want to yield each result from the stream
```dart
Stream<int> watch() async* {
  yield* Stream.fromIterable([1, 2, 3]).onErrorReturnWith((error) {
    print("Some error ==> $error");
    return -1;
  });
}
```

**Comment by f0rx** [comment]
Before I upgraded flutter, this was not an issue. This definitely happens after upgrading flutter.

**Comment by f0rx** [comment]
I finally got to fix this.
Regarding issue #63922, I had to edit animation_controller.dart to add the @ symbol before required to fix compilation issues. And I guess this had serious repercussions.

FIX: I had to git reset the animation_controller.dart file to HEAD

This was not really an issue, I'll close this now.
