### ISSUE TITLE
Can I somehow run tasks in background using rxDart?

### ISSUE THREAD

**Issue by Turbozanik** [ReactiveX/rxdart#495]
It was really life saving when in RxJava I was able to user observerOn/subscribeOn. 
Can I somehow do the same with RxDart?
For expample I have the following code:
```
 @override
  Stream<List<TaskDto>> getReports() {
    return Stream.fromFuture(_reportService.getReports()).map((value) {
      List _list = List<TaskDto>();
      return _list;
    });
  }
```

As it seems to me, the ```_reportService.getReports()``` part will be executed in the background thread due to dio/retrofit logic(at least I hope so), but map will be executed in the main thread, is there a way I can execute it in backgroud thread?
I think I have found a workaround as you can see below, but it does not looks like a right approach.

```
class ReportsRepositoryImpl extends ReportsRepository {
  final _reportService = createReportsService();

  @override
  Stream<List<TaskDto>> getReports() {
    return Stream.fromFuture(_reportService.getReports()).asyncMap((value) {
      return getFeatureTransformer(value.mData);
    });
  }

  Future<List<TaskDto>> getFeatureTransformer(List<Report> itemList) async {
    return compute(getTaskList, itemList);
  }

  static List<TaskDto> getTaskList(List<Report> itemList) {
    return List<TaskDto>();
  }
  
}
```

**Comment by hoc081098** [comment]
Dart has a single thread, or event-loop, of execution and `Futures are not Threads`.
You can use `Isolate` which allow you to execute code in a different process

**Comment by Turbozanik** [comment]
> Dart has a single thread, or event-loop, of execution and `Futures are not Threads`.
> You can use `Isolate` which allow you to execute code in a different process

And that's exactly what i am doing using compute, but the draw back for this approach is that I am forced to create static functions for this, and I wanted to know if there any better solution and if there is a better solution how can I use it with rxDart.

**Comment by hoc081098** [comment]
You can use `ReceivePort` and `SendPort` like https://github.com/filiph/hn_app/blob/master/lib/src/notifiers/worker.dart
