### ISSUE TITLE
maybe we need `takeLast` ?

### ISSUE THREAD

**Issue by HannibalKcc** [ReactiveX/rxdart#497]
[rxjs takeLast](https://rxjs.dev/api/operators/takeLast).

`takeLast` is a useful `API`，but i didn't find a similar `API` in `rxdart` or `dart stream`.can we provide this `API` in future?

TKS for any help.

**Comment by ThomasKliszowski** [comment]
👋 

Why did you close  this issue?

**Comment by HannibalKcc** [comment]
sry, solved my problem with the help of complex code,so i closed it(i think it was unwise).

you think i need reopen this issue?

**Comment by frankpepermans** [comment]
I suppose we could add it,
If the Stream does not emit a huge amount of data,
You could for now do (sorry mobile)

final list = await stream.asList
list.reversed.take(amount)

**Comment by ThomasKliszowski** [comment]
@frankpepermans this could work indeed, but working out of streams is not encouraged.

My personal usecase was to only emit the last item when this stream completes.
I could use [last](http://reactivex.io/documentation/operators/last.html), but the **Dart** implementation returns a `Future` and break the stream.
As **ReactiveX** points out, the implementation of [takeLast](http://reactivex.io/documentation/operators/takelast.html) is more likely to be done in streams, and could be exactly what I want.

I started to write something on my side, I will try to fill a PR.

**Comment by ThomasKliszowski** [comment]
Here you go #546
