### ISSUE TITLE
Transforming a broadcast stream with share() doesn't respect refCount

### ISSUE THREAD

**Issue by smkhalsa** [ReactiveX/rxdart#514]
The following test times out:

```dart
test('can cancel shared stream when no listeners remain', () async {
  final isDone = Completer();

  final controller = StreamController.broadcast();
  final stream = controller.stream.share().doOnDone(isDone.complete);
  StreamSubscription subscription;
  subscription = stream.listen((event) async {
    await subscription.cancel();
  });
  expect(isDone.future, completes);
});
```

The `stream`'s underlying PublishSubject always shows that it has a listener, even before the listen method is called.

The refCount doesn't appear to be respected (and the stream, therefore, isn't shut down when no listeners remain)  when transforming broadcast streams.

**Comment by frankpepermans** [comment]
onDone will only trigger when you close your controller or subject, onCancel should trigger when no subscriptions are active, if I remember correctly.
On my phone atm so cannot check the implementation.

**Comment by smkhalsa** [comment]
Thanks @frankpepermans for the quick response.

The same test times out with `doOnCancel` as well

```dart
test('can cancel shared stream when no listeners remain', () async {
  final isCanceled = Completer();

  final controller = StreamController.broadcast();
  final stream = controller.stream.share().doOnCancel(isCanceled.complete);
  StreamSubscription subscription;
  subscription = stream.listen((event) async {
    await subscription.cancel();
  });
  expect(isCanceled.future, completes);
});
```

**Comment by hoc081098** [comment]
It seems like a bug because `asBroadcastStream` doesn't cancel source `StreamSubscription` when `Stream` stops having listener.
https://github.com/dart-lang/sdk/issues/26686 https://github.com/ReactiveX/rxdart/issues/455

**Comment by smkhalsa** [comment]
The following test times out as well (even in #515). Is this expected?

My assumption is that the inner Stream would close since it no longer has any listeners once the outer StreamSubscription cancels.

```dart
test('can cancel shared stream when no listeners remain', () async {
  final isCanceled = Completer();
  final isDone = Completer();
  final controller = StreamController<bool>();

  final stream = controller.stream.startWith(false).switchMap(
        (value) => NeverStream()
            .startWith(true)
            .shareValue()
            .doOnCancel(() => isCanceled.complete())
            .doOnDone(() => isDone.complete()),
      );

  StreamSubscription sub;
  sub = stream.listen((event) => sub.cancel());
  
  await expectLater(isCanceled.future, completes);
  await expectLater(isDone.future, completes);
});
```

**Comment by smkhalsa** [comment]
@hoc081098 any thoughts on this?

**Comment by hoc081098** [comment]
@smkhalsa I think expected behaviour is: Stream is cancelled and no done event is sent.

**Comment by smkhalsa** [comment]
Interesting. So is there no way to close streams that use `share()` / `shareValue()`? Does this not create the potential for memory leaks?

**Comment by hoc081098** [comment]
@smkhalsa You can use `onCancel` event to clean up resource. This not create memory leaks as well.

_Sent from my Redmi  7A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by smkhalsa** [comment]
> `onCancel` is called when onDone event is delivered or cancelling StreamSubscription

This doesn't appear to be happening with `PublishConnectableStream` / `ValueConnectableStream`:

For example, the following test fails:

```dart
test('can close share() stream', () async {
  final isCanceled = Completer();
  final controller = StreamController<bool>();
  controller.stream
      .shareValue()
      .doOnCancel(() => isCanceled.complete())
      .listen(null);

  controller.add(true);
  await Future.delayed(Duration.zero);

  await controller.close();

  expect(isCanceled.future, completes);
});
```

**Comment by hoc081098** [comment]
@smkhalsa just updated #515, please checkout it
