### ISSUE TITLE
BehaviorSubject/ValueStream - any way to access the last error if it occurred?

### ISSUE THREAD

**Issue by timnew** [ReactiveX/rxdart#517]
`BehaviorSubject` and `ValueStream` provided a way to check whether latest value exists and get its value if it does.

Wondering is it possible to have the equivalent for the latest error?

Actually I found it shouldn't be too difficult as `_Wrapper` has already recorded the latest error and stack trace. The only thing needed is just add a few API to expose it.

**Comment by hoc081098** [comment]
We have added `bool get hasError` and `Object get error` into `ValueStream` since version  `0.25.0-beta`. Please check out

**Comment by timnew** [comment]
@hoc081098 Can it also expose `stackTrace` along with the `error`, which will be useful to understand where the error occurred, it might not be useful to the UI, but it is kind of important for the diagnosis.
