### ISSUE TITLE
CombineLatestStream default value

### ISSUE THREAD

**Issue by robbysoerya** [ReactiveX/rxdart#519]
` Stream<bool> get submitValid => CombineLatestStream.combine4(nameStream,
      emailStream, passwordStream, confPasswordStream, (a, b, c, d) => true);`

value of `submitValid` return true or null, why default value or else is `null` and not `false`?

**Comment by hoc081098** [comment]
(a, b, c, d) => true always return true

**Comment by robbysoerya** [comment]
@hoc081098 I mean, why if the conditions are not met, the value of `submitValid` return null, why not return `false`?

**Comment by hoc081098** [comment]
@robbysoerya  Do you use it with `StreamBuilder`? `CombineLatestStream` only emit data when all `Stream`s emit data. If using `StreamBuilder`, `snapshot.data` is null in this case

**Comment by robbysoerya** [comment]
@hoc081098 You're right, I guess it can return `false` if there is no data, thank you for your answer
