### ISSUE TITLE
Null Safety Migration

### ISSUE THREAD

**Issue by TimWhiting** [ReactiveX/rxdart#528]
Null safety is now in [beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730), and they are encouraging package authors to start migration. I would like to update my package to use null-safety, but I depend on this package.

Any ideas when you will migrate?

**Comment by TimWhiting** [comment]
A quick check with `pub outdated --mode=null-safety` shows the following:
```
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name         Current  Upgradable  Resolvable             Latest                 

dev_dependencies:   
build_runner         -        ✗1.10.6     ✗1.10.6                ✗1.10.6                
build_web_compilers  -        ✗2.15.2     ✗2.15.2                ✗2.15.2                
mockito              -        ✗3.0.2      ✗4.1.3                 ✗4.1.3                 
pedantic             -        ✗1.9.0      ✓1.10.0-nullsafety.3   ✓1.10.0-nullsafety.3   
stack_trace          -        ✗1.9.6      ✓1.10.0-nullsafety.6   ✓1.10.0-nullsafety.6   
test                 -        ✗1.15.5     ✓1.16.0-nullsafety.10  ✓1.16.0-nullsafety.10  

No pubspec.lock found. There are no Current versions.
Run `pub get` to create a pubspec.lock with versions matching your pubspec.yaml.

4  dependencies are constrained to versions that are older than a resolvable version.
To update these dependencies, edit pubspec.yaml.
```

So I'm guessing you might need to wait for these dependencies?

**Comment by hoc081098** [comment]
https://github.com/ReactiveX/rxdart/pull/507

**Comment by frankpepermans** [comment]
Still working on it, see https://github.com/ReactiveX/rxdart/tree/nnbd

**Comment by hoc081098** [comment]
Published first nnbd version: https://pub.dev/packages/rxdart/versions/0.26.0-nullsafety.0

**Comment by ryanheise** [comment]
Are there plans for a preview stable release?

https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010
