### ISSUE TITLE
doOnError, doOnData, doOnListen fails if stream results with an error, need an advice how can I fix this.

### ISSUE THREAD

**Issue by Turbozanik** [ReactiveX/rxdart#533]
I am trying to make a network request with doOnError, doOnData, doOnListen operators and in my case if request fails, app crashes with the following error.
Error:  [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: type 'DoStreamTransformer<dynamic>' is not a subtype of type 'StreamTransformer<List<SpotDto>, dynamic>' of 'streamTransformer'
#0      Stream.transform (dart:async/stream.dart)
#1      DoExtensions.doOnListen (package:rxdart/src/transformers/do.dart:294:7)
#2      BasePagingController.addLoadingLogic (package:app/presentation/base/pagination/base_paging_controller.dart:13:19)
#3      BaseBloc.handlePagingFuture (package:app/presentation/base/base_bloc.dart:50:22)
#4      SpotListBlock.refreshSpots (package:app/presentation/pages/spotlist/spot_list_block.dart:28:12)
#5      SpotListScreenState.build.<anonymous closure>.<anonymous closure> (package:app/presentation/pages/spotlist/spot_list_screen.dart:51:42)
#6      RefreshIndicatorState._show.<anonymous closure> (package:flutter/src/material/refresh_indicator.dart:368:62)
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:11<…>

Code and issue explanation:
**First step is making request from bloc:**
![Screen Shot 2020-12-03 at 15 07 31](https://user-images.githubusercontent.com/7550948/101017075-a9717780-357a-11eb-91e9-ce35f14209c0.png)
**Second step, base error handling wrappers in base bloc:**
![Screen Shot 2020-12-03 at 15 07 46](https://user-images.githubusercontent.com/7550948/101017254-e2a9e780-357a-11eb-9eb7-61bc0ccfe455.png)
**Third step, handling pages in page controller(doOnError, doOnData, doOnListen are here ot controll pages):**
![Screen Shot 2020-12-03 at 15 08 01](https://user-images.githubusercontent.com/7550948/101017345-040ad380-357b-11eb-8f6c-20e56e168762.png)
**Fourth step is dio error flow showcase:**
![Screen Shot 2020-12-03 at 15 08 34](https://user-images.githubusercontent.com/7550948/101017428-243a9280-357b-11eb-8462-6aa5315fd19c.png)
**Fifs step is the place where StreamTransformer<List<SpotDto>, dynamic> is comming from:**
![Screen Shot 2020-12-03 at 15 09 36](https://user-images.githubusercontent.com/7550948/101017510-3b798000-357b-11eb-8146-e448eef11a88.png)

So, it seems to be all details I have, the question is how can I fix this, and be able to use doOnError, doOnData, doOnListen even if stream fails.
PS: I was also trying to place handleError before doOnError etc, but it was still crashing the app..

**Comment by hoc081098** [comment]
Trying `doOnError(e, s)`

**Comment by Turbozanik** [comment]
Still fails with the same error.

[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: type 'DoStreamTransformer<dynamic>' is not a subtype of type 'StreamTransformer<List<SpotDto>, dynamic>' of 'streamTransformer'
#0      Stream.transform (dart:async/stream.dart)
#1      DoExtensions.doOnError (package:rxdart/src/transformers/do.dart:249:7)
#2      BasePagingController.addLoadingLogic (package:app/presentation/base/pagination/base_paging_controller.dart:13:19)
#3      BaseBloc.handlePagingFuture (package:app/presentation/base/base_bloc.dart:51:22)
#4      SpotListBlock.refreshSpots (package:app/presentation/pages/spotlist/spot_list_block.dart:28:12)
#5      SpotListScreenState.build.<anonymous closure>.<anonymous closure> (package:app/presentation/pages/spotlist/spot_list_screen.dart:51:42)
#6      RefreshIndicatorState._show.<anonymous closure> (package:flutter/src/material/refresh_indicator.dart:368:62)
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:110<…>

**Comment by hoc081098** [comment]
```dart
handlePagingFuture(..., BasePagingController<DataType> pagingController)
```
instead of
```dart
handlePagingFuture(..., BasePagingController pagingController)
```

**Comment by Turbozanik** [comment]
Thanks! It works. Can you explain why it works =)? I am new to dart, and to me dynamic was the same to BasePagingController<Object>, but seems like it's not.
