### ISSUE TITLE
Help : [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'DebounceStreamTransformer<dynamic>' is not a subtype of type 'StreamTransformer<String, dynamic>' of 'streamTransformer'

### ISSUE THREAD

**Issue by x4080** [ReactiveX/rxdart#538]
Hi, I got this error
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'DebounceStreamTransformer<dynamic>' is not a subtype of type 'StreamTransformer<String, dynamic>' of 'streamTransformer'
```
after updating to rxdart from ^0.22.0

the snippet is
```
    _searchevents
        .debounce((_) => TimerStream(true, Duration(milliseconds: 200)))
        .switchMap((keyword) async* {
...
```

_searchevents is
```
final PublishSubject _searchevents =
      PublishSubject<String>();
```

How to fix it ? Already tried using cast but wont work

Thanks in advance for helping

**Comment by hoc081098** [comment]
final PublishSubject<String> _searchEvents

**Comment by x4080** [comment]
Hi @hoc081098 , thanks again for answering, could you explain more the right syntax i should apply?

Thanks

**Comment by hoc081098** [comment]
@x4080 AVOID annotating generic type with dynamic as much as possible. In your case:
```dart
final PublishSubject _searchevents =
      PublishSubject<String>();
```
Type of `_searchevents` is `PublishSubject<dynamic>`. Should be changed to `final _searchevents = PublishSubject<String>();` 
or  `final PublishSubject<String> _searchevents = PublishSubject<String>();`

**Comment by x4080** [comment]
@hoc081098 Thanks for the tip, it works. I didnt know that was a mistake, sorry
