### ISSUE TITLE
CombineLatestStream.combine2 mixed data types

### ISSUE THREAD

**Issue by matthewkooshad** [ReactiveX/rxdart#539]
How can i adjust the below to specify that [0] of this returned stream will be String type and [1] of this returned stream will be int type?

```
CombineLatestStream<dynamic, List> getStream() {
    return CombineLatestStream.combine2(getStrings(), getInts(), (s1, s2) => [s1, s2]);
  }
```

**Comment by hoc081098** [comment]
Using  `tuple` package:

```dart
import 'package:tuple/tuple.dart';

Stream<Tuple2<String, int>> s = <CombineLatestStream.combine2(
  string$,
  int$,
  (String s, int i) => Tuple2<String, ịnt>(s, i));
```

_Sent from my Redmi  7A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by matthewkooshad** [comment]
@hoc081098 i installed tuple: ^1.0.3, and i've been using: rxdart: ^0.24.0
The argument type 'Tuple2<String, int> Function(String, int)' can't be assigned to the parameter type 'Tuple2<String, int> Function(List<String>, List<int>)'.

**Comment by hoc081098** [comment]
@matthewkooshad what is type of getStrings and getInts

**Comment by matthewkooshad** [comment]
Stream<List<String>> and Stream<List<int>>

**Comment by hoc081098** [comment]
@matthewkooshad 
```dart
import 'package:tuple/tuple.dart';

Stream<List> a$;
Stream<List> b$;
Stream<Tuple2<List, List>> s = CombineLatestStream.combine2(
  a$,
  b$,
  (List a, List b) => Tuple2(a, b),
);
```

**Comment by matthewkooshad** [comment]
thanks @hoc081098 !
