### ISSUE TITLE
RetryWhen's RetryError is not a transparent solution

### ISSUE THREAD

**Issue by larssn** [ReactiveX/rxdart#544]
So I have a peeve with RetryError. My problem with it is that it wraps and thus obfuscates the original error. This in turn makes retryWhen non-transparent: you can't insert retryWhen into an existing stream hierarchy and expect it to work as it used to work, because exceptions now get transformed to RetryError.

I ran into a scenario like the above, where I had to inject retry logic into existing stream(s), but ended up having to refactor out the RetryError from the existing RxDart code, to make it behave as expected.

Can we discuss if it would be possible to remove RetryError from this operator? It does not belong IMO, and unhandled errors should never be scooped up mid-transit: they are important for breaking out of the control flow.

**Comment by hoc081098** [comment]
Hi @larssn, Please see #547
