### ISSUE TITLE
The method 'switchMap' isn't defined for the type 'Stream'.

### ISSUE THREAD

**Issue by RomanSoviak** [ReactiveX/rxdart#549]
In `rxdart: ^0.25.0` and `flutter_bloc: ^6.1.1` I have this issue with imports

**Comment by hoc081098** [comment]
please post some lines of code

**Comment by RomanSoviak** [comment]
` @override
  Stream<Transition<HomeEvent, HomeState>> transformEvents(
    Stream<HomeEvent> events,
    TransitionFunction<HomeEvent, HomeState> transitionFn,
  ) =>
      events.switchMap(transitionFn);`

**Comment by hoc081098** [comment]
```dart
import 'package:rxdart/rxdart.dart'
```
