### ISSUE TITLE
Non-nullable-by-default value streams

### ISSUE THREAD

**Issue by ryanheise** [ReactiveX/rxdart#550]
A seeded `ValueStream` (e.g. as produced via `BehaviorSubject.seeded`) can in principle always have a non-null value, but this is unfortunately not reflected by the type system and consequently requires null checks on `stream.value`. In an app where all value streams are seeded, it can be quite inconvenient that the the nullsafe features of the language don't help.

Because `T` is a subtype of `T?` for all `T`, we can solve this problem by having a seeded subclass of `ValueStream`:

```dart
abstract class SeededValueStream<T> extends ValueStream<T> {
   @override
   T get value => super.value!;
}
```

(I understand rxdart now implements `value` as an extension method, but this is just to illustrate the general principle of how the typing could work.)

We can then have the `seeded` constructors return `SeededValueStream`s.

**Comment by hoc081098** [comment]
But when callling `BehaviorSubject.addError(e, s)`, `value` returns `null` 😃

**Comment by ryanheise** [comment]
Then, the `SeededValueStream.value` getter could be made to throw the actual stream error. But that would violate the substitution principle if `SeededValueStream` is a subclass of `ValueStream`, or at least would be a breaking API change.

If you take a look at the `AsyncSnapshot` class in the standard libraries, it implements both approaches. It provides a getter that returns `T?`and then provides another getter that returns `T` which either returns the value or throws the error if there is an error.

**Comment by hoc081098** [comment]
Why not use `ValueStream.requireValue`:
https://github.com/ReactiveX/rxdart/blob/7a1c89b386a90d8d19ee8cfff3feaf85ef9e0085/lib/src/streams/value_stream.dart#L27

**Comment by ryanheise** [comment]
Ah yes, that is exactly what I was looking for :-). Apologies, I am still navigating my way around the new code and extension methods and didn't notice it already does this. I'll close this issue.

**Comment by ryanheise** [comment]
Although I've closed the issue, I would say I do slightly prefer the `AsyncSnapshot` API where `requireData` throws the actual underlying stream error, and not merely a null check assertion.

**Comment by hoc081098** [comment]
See PR #551
