### ISSUE TITLE
What is the best way to create dependent network requests?

### ISSUE THREAD

**Issue by Turbozanik** [ReactiveX/rxdart#576]
I RxJava I would simply call flatMap, it suites this task perfectly.
But in rxDart, what is the right way to execute first request, grab its data and pass it the second request? 
Probably I can also use FlatMap, but is seems like the order of objects might be lost. And as I understood it works differently from RxJava flatMap.
So just wanted to be sure, that I use it the right way.

**Comment by hoc081098** [comment]
> Probably I can also use FlatMap, but is seems like the order of objects might be lost. And as I understood it works differently from RxJava flatMap.
RxDart's FlatMap is the same as RxJava

**Comment by hoc081098** [comment]
Check my package `rxdart_ext` (https://pub.dev/packages/rxdart_ext/versions/0.1.1-dev.1), which provides `Single` type
```dart
import 'package:http/http.dart' as http;

Single<User> fetchUser(String id) {
  return Single.fromCallable(() => http.get(Uri.parse('$baseUrl/users/$id')))
      .flatMapSingle((res) => res.statusCode == HttpStatus.ok
          ? Single.value(res.body)
          : Single.error(Exception('Cannot fetch user with id=$id')))
      .map((body) => User.fromJson(jsonEncode(body)));
}
```

**Comment by faisalmushtaq007** [comment]
@Turbozanik Hey there, i have same task as you had. but i am not able to find any good solution or example. Could you help me here. How did you solved your issue?

**Comment by Turbozanik** [comment]
@faisalmushtaq007 Take a look at `example `method https://gist.github.com/Turbozanik/51c04145c441479be2e82598da989069
