### ISSUE TITLE
Set and emit the new value on v0.26.0

### ISSUE THREAD

**Issue by dernoun** [ReactiveX/rxdart#577]
I upgrade an existing app that use rxdart, i get this exception for all the `BehavioreSubject` that try to set a new value. 
Code that throw the error _There isn’t a setter named 'value' in class 'ValueStreamExtensions'._ : 
```
  final BehaviorSubject<double> aspectR = BehaviorSubject()..value = 16 / 9;
  final BehaviorSubject<bool> isLoading = BehaviorSubject()..value = true;
```
How to solve this ?

**Comment by hoc081098** [comment]
Using `BehaviorSubject .seeded(...)` or `BehaviorSubject()..add(...)`
