### ISSUE TITLE
rxdart do not use standard reactivex pattern.

### ISSUE THREAD

**Issue by rouddy** [ReactiveX/rxdart#581]
stream and future is good enough.
but future is not exact same with single, completable or maybe.
future is run right after creatation while reactivex is run when it subscribed.
so i suggest to use single, completable, maybe with not future but stream.

**Comment by hoc081098** [comment]
Just using regular Stream
I am adding Single to my package rxdart_ext

**Comment by rouddy** [comment]
thanx for notice.
i'll try rxdart_ext.

**Comment by hoc081098** [comment]
hey @rouddy 
I just published, trying it :)) https://pub.dev/packages/rxdart_ext/versions/0.1.1-dev.0
