### ISSUE TITLE
add takeUntilCompleted

### ISSUE THREAD

**Issue by cedvdb** [ReactiveX/rxdart#584]
Edit: could we have takeUntilCompleted that acts like takeUntil but instead finishes when the stream passed as param completes ?

**Comment by hoc081098** [comment]
You can publish a lib, such as my lib  (focusing on did_change_dependencies) https://github.com/hoc081098/did_change_dependencies/blob/master/lib/src/did_change_dependencies.dart :))

**Comment by cedvdb** [comment]
I'm on the wrong repository, I thought this was the bloc package. Still I think a takeUntilCompleted would be a nice addition

**Comment by hoc081098** [comment]
Just use `takeUntil` and `ignoreElements` :))
```dart
takeUntilCompleted(stream) = takeUntil(stream.ignoreElements())
```

**Comment by cedvdb** [comment]
has become

`.takeUntil(Stream.fromFuture(stream.drain()))`
