### ISSUE TITLE
Documentation issue on DebounceStreamTransformer<T>

### ISSUE THREAD

**Issue by mnkeis** [ReactiveX/rxdart#598]
https://github.com/ReactiveX/rxdart/blob/ec9409235a3b8833027d6a830d5daceb5a59639b/lib/src/transformers/backpressure/debounce.dart#L26-L29

Looking for this behaviour I realized that actually the transformer emits the last element on the list instead of the entire list.

I understand that the expected behaviour is actually the implemented and not the stated on the documentation, or, I misunderstood the documentation.

I don't know if there's another way to achieve what I need, but I've already implemented a new operator and I'm ready to post a pull request if there's a missing feature.

**Comment by hoc081098** [comment]
I think that is a copy-paste mistake (copied from `buffer` operator)
https://github.com/ReactiveX/rxdart/blob/ec9409235a3b8833027d6a830d5daceb5a59639b/lib/src/transformers/backpressure/buffer.dart#L18
