### ISSUE TITLE
Dartdocs doesn't seem to work

### ISSUE THREAD

**Issue by dotdotcommadot** [ReactiveX/rxdart#60]
The link to Dartdocs doesn't seem to work:
https://www.dartdocs.org/documentation/rxdart

**Comment by frankpepermans** [comment]
Dartdocs are auto generated when you upload to pub and it fails for rxdart, but also for flutter, jaguar, etc..

So I suppose it is more a Dartdocs issue

**Comment by brianegan** [comment]
This is indeed a DartDocs issue:

https://github.com/dart-lang/dartdoc/pull/1329

I've asked them to bump up the priority and deploy a fix to the site. Not sure if it will work, but hopefully it does :)

**Comment by brianegan** [comment]
And it worked! They should be shipping the fix to DartDocs soon
