### ISSUE TITLE
Possible memory leak in groupBy

### ISSUE THREAD

**Issue by feinstein** [ReactiveX/rxdart#606]
I have a stream that emmits updates for items. Each item had an ID and I need to show a notification for each item update. A good example would be a shopping App, where we show a notification whenever an order was updated with more items, or finished.

I am using `groupBy` to separate the items per ID, so I can `debounce` all the updates from the same item later (most status updates happen in milliseconds and only the last one is relevant).

My concern is that `groupBy` will hold a reference from each ID, even if the item with that ID will never again send any notifications. Since I have lots of updates, this can lead to a major memory leak.

Is this covered by the lib? Are there mechanisms to avoid memory leaks with `groupBy`?

I am thinking about using a window maybe, but I am not sure if that's enough or if `groupBy` itself can handle it better.

**Comment by hoc081098** [comment]
Currently, I think there is no way to do that

**Comment by function1983** [comment]
@feinstein could you provide a minimal working code for your case? I face the same business issue and I got mine (kind of) working but not sure if I implemented it right. Here is my code:

```
    Stream<GroupedStream<ItemEvent, String>> groupedStream = events.where((event) {
      return (event is ItemUpdateEvent);
    }).groupBy((v) {
      return (v as ItemUpdateEvent).itemID;
    },
            durationSelector: (_) => Stream.periodic(const Duration(
                milliseconds: 2000)));

    Stream<ItemEvent> debounceStream = groupedStream.map((e) {
      return e.debounceTime(Duration(milliseconds: 1000));
    }).flatMap((v) => v);
```
`ItemUpdateEvent class extends ItemEvent`
