### ISSUE TITLE
BehaviorSubject.distinct() looses it's value

### ISSUE THREAD

**Issue by fdietze** [ReactiveX/rxdart#610]
```dart
  final s = BehaviorSubject.seeded(5);
  print(s.value); // prints 5
  print(s.distinct().value); // throws!
```

Repl:
https://replit.com/@FelixDietze/RundownAstonishingMacro#main.dart
(the repl is on rxdart 0.25, because it only runs dart 2.6, but I experience the same bug with rxdart 0.27.1 and dart 2.13)

**Comment by hoc081098** [comment]
Because seeded data will be replayed asynchronously (scheduleMicrotask).

**Comment by fdietze** [comment]
Thank you for the explanation. How do I deal with that then? `sync: true` didn't help.

**Comment by hoc081098** [comment]
You can use `first`
```dart
final s = BehaviorSubject.seeded(5);
await s.distinct().first; // 5
```
or use `valueOrNull`
```
final str = BehaviorSubject.seeded(5).distinct();
str.valueOrNull; // null
await Future.delayed(Duration.zero);
str.valueOrNull; // 5
```

**Comment by fdietze** [comment]
Thank you.
