### ISSUE TITLE
testing support

### ISSUE THREAD

**Issue by susonthapa** [ReactiveX/rxdart#613]
Coming from Android world, we used to have `TestObservers` with functions like `assertValueCount`. But I didn't find any such classes in **RxDart** (maybe I'm looking at the wrong place). 
For testing I have used the `test` packages that supports stream testing and I have implemented few `StreamMatchers`. I was just curious if there is any official testing support in the library?

**Comment by hoc081098** [comment]
You can use [Stream.length](https://api.dart.dev/stable/2.14.1/dart-async/Stream/length.html)
```dart
final aStream = Stream.fromIterable([1, 2]);
expect(aStream.length, completion(2));
```
