### ISSUE TITLE
Why is it impossible to import BackpressureStreamTransformer?

### ISSUE THREAD

**Issue by AlexandrFarkas** [ReactiveX/rxdart#632]
rxdart 0.27.2

**Comment by hoc081098** [comment]
Hi, please provide some line of codes to reproduce your problem

**Comment by hoc081098** [comment]
BackpressureStreamTransformer is just internal class, we do not export it

**Comment by hoc081098** [comment]
You can import it via: `import 'package:rxdart/src/transformers/backpressure/backpressure.dart';
`
