### ISSUE TITLE
CombineLatestStream emits data events after error events

### ISSUE THREAD

**Issue by TatsuUkraine** [ReactiveX/rxdart#641]
Not quite sure if it's expected behavior or an error.

So I have the following case.

I have StreamA and StreamB. Both wrapped with combine latest stream and simple string concat. StreamA emits and event `1`, then StreamB emits `2`. I get a data event like `1 2`. Then StreamA emits an error event. The output of combine latest is an error event as well. All fine for now.

Now StreamB emits an event `3`. Combine latest produces output like `1 3`. Which is not quite expected)

So the question is - is described behavior is expected or it's an issue?

Here is a test case for this scenario with expected behavior (in my opinion) and it will fail

```dart
    final expectedResult = [
      '1 2',
      '3 4'
    ];
    final StreamController<int> controller1 = StreamController.broadcast(sync: true);
    final StreamController<int> controller2 = StreamController.broadcast(sync: true);

    final streamWithError = CombineLatestStream.combine2(
      controller1.stream,
      controller2.stream,
      (int aValue, int bValue) {
        return '$aValue $bValue';
      }
    );

    int count = 0;

    streamWithError.listen(
      expectAsync1((value) {
        expect(value, expectedResult[count++]);
      }, count: 2),
      onError: expectAsync2((Exception e, StackTrace s) {
        expect(e, isException);
      }, count: 1)
    );

    controller1.sink.add(1);
    controller2.sink.add(2);
    controller2.sink.addError(Exception());
    controller1.sink.add(3);
    controller2.sink.add(4);
```

With current implementation of CombineLatestStream expected result looks like this
```dart
final expectedResult = [
      '1 2',
      '3 2',
      '3 4',
    ];
```

**Comment by hoc081098** [comment]
That is expected behavior, in rxdart, the error event and data event are separated.
See https://github.com/ReactiveX/rxdart#rx-observables-vs-dart-streams

**Comment by TatsuUkraine** [comment]
@hoc081098 sorry, but could you point where this describes as expected behavior? I'm curious because I would understand if after emitting 3 to controller1 combine latest doesn't generate any event, or generate error event that he go last time from controller2. Instead it generates a data event with last data event from controller1 nevertheless last event there was an error event

**Comment by TatsuUkraine** [comment]
@hoc081098 I also curious, if it's an expected behavior , will it make sense to add another combine latest stream variant that will be matching test case that I provided? Or maybe update existing one with some flag like `pauseOnError` or `errorAware` ?

**Comment by hoc081098** [comment]
- Combinelatest:
![](https://rxjs.dev/assets/images/marble-diagrams/combineLatest.png)

- Zi
<img width="826" alt="rxjs-zip" src="https://user-images.githubusercontent.com/36917223/140305827-0fa5623f-ebb7-4db0-bdec-6daaad24e654.png">
p

**Comment by TatsuUkraine** [comment]
@hoc081098 yes, but there is nothing said about errors

**Comment by TatsuUkraine** [comment]
My only concern in that scenario that strramB forces data event while streamA has an error event

**Comment by TatsuUkraine** [comment]
> will it make sense to add another combine latest stream variant that will be matching test case that I provided? Or maybe update existing one with some flag like `pauseOnError` or `errorAware` ?

Also curious what you think about this part of my question?

**Comment by hoc081098** [comment]
What's about `materialize`:
```dart
Rx.combineLatest(streamA.materialize(), streamB.materialize(), (Notification<int> a, Notification<int> b) {
    if (a.isOnError || b.isOnError) return null;
    if (a.isOnData && b.isOnData) return '${a.requireData} ${b.requireData}';
    return null;
}).whereType<String>();
```

**Comment by simon-lammes** [comment]
Wouldn't it make sense to have the combined stream emit error events as long as any of its input streams' last emitted event was an error? This sounds like a reasonable default behavior. The current behavior seems surprising to me, and I haven't found any documentation about it. RxJS cannot be used as a reference because the combined stream closes with an error as soon as one of the input streams emits an error. However, the proposed behavior would be "closer" to RxJS than the current implementation.

I assume that combineLatest means the latest event of each stream is considered, even if that event was an error. So when a value event is combined with an error event, the result should also be an error.

I would be happy to find out which behavior makes the most sense for Dart streams, which differ from RxJS observables and therefore cannot copy their exact behavior.
