### ISSUE TITLE
Bad state: too many elements

### ISSUE THREAD

**Issue by cntoss** [ReactiveX/rxdart#667]
Below is an error on behaviorsubject when .sink.add called more than once 
this error is not always happen 

sample code:

     //initialization
     final _orders = BehaviorSubject<String>();

    //update
    update() {
    _order.sink.add('xyz');
    }

if I called update() method several times then I got exception

Unhandled Exception: Bad state: Too many elements
#0      Stream.single.<anonymous closure> (dart:async[/stream.dart:1354:11]())
#1      _rootRunUnary (dart:async[/zone.dart:1434:47]())
#2      _CustomZone.runUnary (dart:async[/zone.dart:1335:19]())
#3      _CustomZone.runUnaryGuarded (dart:async[/zone.dart:1244:7]())
#4      _BufferingStreamSubscription._sendData (dart:async[/stream_impl.dart:341:11]())
#5      _BufferingStreamSubscription._add (dart:async[/stream_impl.dart:271:7]())
#6      _MultiStreamController.addSync (dart:async[/stream_impl.dart:1129:36]())
#7      _MultiControllerSink.add
package:rxdart/…/utils/forwarding_stream.dart:135
#8      _StartWithStreamSink.onData
package:rxdart/…/transformers/start_with.dart:12
#9      _rootRunUnary (dart:async[/zone.dart:1434:47]())
#10     _CustomZone.runUnary (dart:async[/zone.dart:1335:19]())
#11     _CustomZone.runUnaryGuarded (dart:async[/zone.dart:1244:7]())
#12     _BufferingStreamSubscription._sendData (dart:async[/stream_impl.dart:3]()<…>

**Comment by hoc081098** [comment]
Use Stream.first instead single

**Comment by hoc081098** [comment]
@cntoss please add some codes to reproduce this issue

**Comment by feizhaojun** [comment]
Have you resolved this? I get the same exception.

**Comment by hoc081098** [comment]
> Have you resolved this? I get the same exception. 

Did you use `behaviorSubjec.single`?
