### ISSUE TITLE
Merge operator has potential bug

### ISSUE THREAD

**Issue by lestathc** [ReactiveX/rxdart#67]
See following code
```dart
  test('rx.Observable.merge does not deal properly', () async {
     // This will fail:
     // const list<num> expectedOutput = const <num> [1, 2, 3, 4, 5, 6];
     const list<num> expectedOutput = const <num> [1, 4, 2, 5, 3, 6];
 
     StreamController<num> sc1 = new StreamController<num>();
     StreamController<num> sc2 = new StreamController<num>();
 
     int count = 0;
     Stream<num> observable = new Observable<num>.merge([sc1.stream, sc2.stream]);
 
     observable.listen(expectAsync1((num result) {
       // test to see if the combined output matches
       expect(result, expectedOutput[count++]);
     }, count: expectedOutput.length));
 
     sc1.add(1);
     sc1.add(2);
     sc1.add(3);
     sc2.add(4);
     sc2.add(5);
     sc2.add(6);
  });
```
Or
https://github.com/lestathc/rxdart/commit/c211c2a7c039d4e4877b9123fbdba3ca141e22c0

If I changed the stream controller to StreamController<num>(sync: true), then the output will be [1, 2, 3, 4, 5, 6].

I think any order sensitive operators may have this kind of potential bug. The reason is that multiple async StreamControllers has its own execution strategy for multi add operations in one event loop, but which is not FIFO.

**Comment by lestathc** [comment]
And for these code

```dart
     sc1.add(1);
     sc1.add(2);
     sc1.add(3);
     sc2.add(4);
     sc2.add(5);
     sc2.add(6);
```

You can change the order between `sc1` and `sc2`, like 

```dart
     sc1.add(1);
     sc1.add(2);
     sc2.add(4);
     sc2.add(5);
     sc1.add(3);
     sc2.add(6);
```

The output is still `[1, 4, 2, 5, 3, 6]`

**Comment by frankpepermans** [comment]
I don't know if this is actually an issue for merge to solve, like you showed, using sync true would ensure that the sequence of events on subscribe matches that of the additions. If the sequence is crucial, using sync true is the way to go.

Merge's goal is to simply unify the subscribe of n streams, regardless of their sequences.

I'll check how this is handled in other rx implementations though, if they force the same sequence we can adapt our merge

**Comment by lestathc** [comment]
First, `sync:true` should be used with care as its document.

Also, I did check with RxJs, RxJava and ReactiveCocoa, they followed the FIFO order.

And just FYI, in async dart stream controller, if you write code like my example, the event queue looks like
```
 -- head
| [sc1: 1] -> [sc1: 2] -> [sc1: 3]
| [sc2: 4] -> [sc2: 5] -> [sc2: 6]
 -- tail
```

There are only two tasks in the queue, and each task is also a list of small tasks. Then the first task is executed, it run the small task `[sc1: 1]` and re-dispatch the rest of small tasks into the queue again, the queue became:
```
 -- head
| [sc2: 4] -> [sc2: 5] -> [sc2: 6]
| [sc1: 2] -> [sc1: 3]
 -- tail
```
Then the `[sc2: 4]` is executed, the queue became:
```
 -- head
| [sc1: 2] -> [sc1: 3]
| [sc2: 5] -> [sc2: 6]
 -- tail
```
...
...

So, I don't think it is a real bug of your `merge` operator, but as I said, it might be a potential issue may cause user being confused.

**Comment by brianegan** [comment]
Honestly, thanks for the detailed look and discussion. Really appreciate your time and thoughts and pushing us to make this a really solid implementation. 

 I want to look at the RxJava example a bit more and try playing around with schedulers and merge. I wonder if thinking about async : true more like 'scheduleOn(backgroundThread)' might be a useful analogy.

**Comment by brianegan** [comment]
I've dug into this a bit more from the RxJava side. I didn't quite have time to look at RxJS, but I imagine similar outcomes:

By default, if you don't provide a scheduler to RxJava, the work will happen on the same thread as the subscriber. In other words, it's fully synchronous. E.g. `sync: true`.

When I wrote RxJava code that scheduled work on different background threads (using the built in `Schedulers.io()` & `Schedulers.computation()`), the results of `merge` did not consistently come back in order. Which totally make sense -- you schedule async work on background threads, and as soon as that happens, order isn't guaranteed unless you force it to be.

Therefore, the more I think about this, the more I do believe thinking of `async` streams as `scheduleOn(backgroundThread)` might be a helpful analogy for the documentation. What do you think, is that helpful or confusing?

**Comment by lestathc** [comment]
Right, RxJava and RxJs `scheduleOn(backgroundThread)` both follow the same event queue status like I described in my previous thread. But ReactiveCocoa does not, it is still FIFO. 

Actually, `scheduleOn` is not well defined behavior in ReactiveX. 

I agree with it to document `async` stream is auto scheduled on a `microtask` scheduler (you may also want to introduce scheduler concept in this lib). Unless there is any better solution.

**Comment by brianegan** [comment]
Yep, good call. I think Frank has taken a look at adding Schedulers to this lib already, and something we'll defo include.

Since I feel pretty confident we don't have a bug in merge, but rather require more documentation around these quirks, I've gone ahead and opened a specific ticket for that task: https://github.com/ReactiveX/rxdart/issues/71

Please add any more items to that ticket you'd like see documented and I'll put it together :)
