### ISSUE TITLE
Is there any way to AutoDispose BehaviorSubjects ?!

### ISSUE THREAD

**Issue by JoDeveloper** [ReactiveX/rxdart#672]

**Comment by hoc081098** [comment]
you can check https://pub.dev/packages/disposebag

**Comment by JoDeveloper** [comment]
@hoc081098 is there any way without any outside packages ?

**Comment by hoc081098** [comment]
IMO, this feature should not be in `rxdart` :)), you can use my packages or copy/paste into your project without any problem :))
