### ISSUE TITLE
Retry operator did not re-trigger onListen/onSubscribe side effect

### ISSUE THREAD

**Issue by lestathc** [ReactiveX/rxdart#69]
As described in [ReactiveX `retry` operator](http://reactivex.io/documentation/operators/retry.html), current observable should be resubscribed once an error occurs. 

But existing implementation does not do that.

**Comment by frankpepermans** [comment]
There's an important gotcha to consider here,

In Dart we have 2 Stream types, single-subscription and multi-subscription.

For multi-subscription, there is no issue, we simply resubscribe when onError triggers,
on the other hand single-subscriptions cannot be resubscribed to (it would throw).

For the latter, either we simply swallow the Error, pretty much the current retry implementation, or we let retry throw right away, with a proper message saying resubscription is impossible here

thoughts?

**Comment by frankpepermans** [comment]
> or we let retry throw right away, with a proper message saying resubscription is impossible here

Here I mean, we throw even if no onError occurs, the retry operator simply should not be allowed on a single-subscription Observable

**Comment by brianegan** [comment]
Yeah, another tricky difference between the two implementations!

That's an interesting idea -- perhaps the best way would be to add an assert clause at the earliest possible point that would inform the developer that retry only works with multi-subscription streams.

That way we can "fail fast" and inform the developer of the mistake, rather than swallowing the developer error.

**Comment by lestathc** [comment]
Hi, @frankpepermans 

For multi-subscription stream, the onListen side effect will only be trigged at the first time it is listened. 
See: https://dartpad.dartlang.org/b25b41c71f035fd61cb16b4a9a6e3fab

So, I think either document that the `retry` won't trigger the `onListen` side effect, or change the api to something like:

```dart
retry(Stream streamCreator()) {
   ...
   onError: (_) {
      streamCreator().listen(streamController.add, ...)
   }
}
```
Then `streamCreator` will be used to restart side effect (like sending http request).

How do you think?
