### ISSUE TITLE
LICENSE is not detected by pub.dev

### ISSUE THREAD

**Issue by alestiago** [ReactiveX/rxdart#740]
## Description

The package is being reported as having an "unknown" license by pub.dev, see image:

![CleanShot 2023-09-27 at 15 26 26](https://github.com/ReactiveX/rxdart/assets/44524995/3b87953f-b96d-452b-9dcc-f76eca20bbd9)

## Further context

There are already two somewhat duplicate issues that point out how this could be fixed, see #706 and #693 .

**Comment by hoc081098** [comment]
Thanks @alestiago, fixed 🙏
