### ISSUE TITLE
`PublishSubject` doesn't work with `concatWith` operator

### ISSUE THREAD

**Issue by haashem** [ReactiveX/rxdart#750]
In the below example, `concatWith` should emits the values added by stream 2:

```dart
void exampleOf(String of, {required void Function() action}) {
  print('\n———Example $of———');
  action();
}

exampleOf('concatWith(Iterable<Stream>)', action: () {
    final stream1 = Stream.fromIterable([2, 3, 4]);
    final stream2 = PublishSubject<int>();

    stream1.concatWith([stream2]).listen(
      (event) => print('append: $event'),
      onDone: () => print('Done'),
    );
    stream2.add(5);
    stream2.close();
  });
```

**Expected:**
```
———Example concatWith(Iterable<Stream>)———
append: 2
append: 3
append: 4
append: 5
Done
```

**Actual:**
```
———Example concatWith(Iterable<Stream>)———
append: 2
append: 3
append: 4
Done
```

But if I replace `PublishSubject` with `BehaviorSubject` it works as expected.
I think it's a bug.

**Comment by hoc081098** [comment]
all elements from stream1 will be delivered to the result stream with microtask delays (async by default).

At this time, adding value to PublishSubject is ignored, because the stream1 is listening.

```
--2--3--4
-5
```

**Comment by hoc081098** [comment]
See https://github.com/ReactiveX/rxdart?tab=readme-ov-file#rx-observables-vs-dart-streams, and https://api.flutter.dev/flutter/dart-async/Stream-class.html
| A source of asynchronous data events.
