### ISSUE TITLE
Question: What's the versioning policy for this repo?

### ISSUE THREAD

**Issue by dustinlessard-wf** [ReactiveX/rxdart#8]
Do you intend on following semantic versioning with this repo?

If so, are you open to the idea of adding something like this to the readme?

https://github.com/workiva/w_transport#versioning-and-stability

**Comment by frankpepermans** [comment]
I'm unbiased really, if it helps, I've no problem adapting semantic versioning.

I'll have a look later when I get back to work

**Comment by frankpepermans** [comment]
Had a closer look, 

Perhaps it would be better to hold off semantic versioning until the API is more stable?

startWith now takes an Iterable => could become startWith and startWithMany instead (breaking change)
combineLatest and zip could be opened up to allow better type safety => combineTwoLatest, zipThree, ...

I'm sure there's more improvements that can be made, once the API would be reviewed and set in stone, semantic versioning would be easier.

Thoughts?

**Comment by joseluis** [comment]
If you are seriously planning to introduce breaking changes in the public API I agree that it would be sensible to take that into consideration. Prioritizing that work and releasing it at the same time of adopting semver while bumping the version to 1.0.0 is a reasonable possibility.

**Comment by dustinlessard-wf** [comment]
+1, good idea

**Comment by zoechi** [comment]
I hope you don't mind I chime in.
For semver below 1.0.0 breaking changes increase only the minor number.
I'd also suggest to create a version tag in the github repo for released commits.
```
git tag 0.6.2+1
git push --tags
pub publish
```

**Comment by dustinlessard-wf** [comment]
+1 to creating a version tag in the github repo.  That would be super helpful.

**Comment by travissanderson-wf** [comment]
+100 to creating github releases that identify the versions being pushed to pub
+100 to semver, would also really like to see 1.0.0, personally

**Comment by frankpepermans** [comment]
tags have been added tracking back to v0.5.0

**Comment by travissanderson-wf** [comment]
thanks that is a huge help
