### ISSUE TITLE
Class 'BehaviorSubject<int>' has no instance method 'listen'

### ISSUE THREAD

**Issue by adaojunior** [ReactiveX/rxdart#90]
On you documentation you have this:

```
/// ### Example
///
///     final subject = new BehaviorSubject<int>();
///
///     subject.add(1);
///     subject.add(2);
///     subject.add(3);
///
///     subject.listen(print); // prints 3
///     subject.listen(print); // prints 3
///     subject.listen(print); // prints 3
```

But when I try to run this same example I get this error: `Class 'BehaviorSubject<int>' has no instance method 'listen'`

**Comment by adaojunior** [comment]
Also, shouldn't `BehaviorSubject` extend `Observable`  ?

**Comment by frankpepermans** [comment]
Hi Adao,

I'm not sure why you would get an error on listen, where does it originate from, the analyzer or at runtime? 

Could you perhaps share some more info, like the pubspec and sdk/dartium version?

A BehavioSubject is actually a StreamController in Dartland, but the get stream will give you an Observable.

**Comment by adaojunior** [comment]
OK, this is the code I tried to run:

```
final subject = new BehaviorSubject<int>();
subject.add(1);
subject.add(2);
subject.add(3);

subject.listen(print);
subject.listen(print); 
subject.listen(print);
```

And both analyzer and runtime complain about: `Class 'BehaviorSubject<int>' has no instance method 'listen'`.

I believe this is happening because you're not extending `Subject` that itself extend `Observable`, see:

- https://github.com/ReactiveX/rxjs/blob/master/src/BehaviorSubject.ts#L9
- https://github.com/ReactiveX/rxjs/blob/master/src/Subject.ts#L22


You implementation don't extend Subject, so it also doesn't extend `Observable`, see:

- https://github.com/ReactiveX/rxdart/blob/master/lib/src/subject/behavior_subject.dart#L37

I've trying to learn RxJs and I decided to port (or at least try to port) [ngrx/store](https://github.com/ngrx/store) to dart.

**Comment by frankpepermans** [comment]
The example appears to be wrong, a BehaviorSubject has a stream property, which is an Observable that can be listened to.

We'll correct the sample

**Comment by adaojunior** [comment]
Ok, I check and on both `RxJs` and `RxJava` BehaviorSubject extends `Subject` making it a `Observable`. Would you consider having a similar implementation ?

**Comment by frankpepermans** [comment]
This discussion came up before, see https://github.com/ReactiveX/rxdart/issues/88

This is similar for the rxdart behaviour subject. We already have a StreamController from the dart:async lib, BehaviorSubject follows that design.

We could do an rx implementation from scratch, bypassing anything Dart already provides out of the box, but then you'd need to learn 2 different async implementations.

**Comment by adaojunior** [comment]
Oh I see the discussion, I do agree with Alex that `the best thing about is lost in the process - parity of features/api with other Rx implementations`. But I also like that you're trying to get it as darty as possible, this way rxdart works well with the current stream implementation of dart, an example being `new Observable<KeyboardEvent>(document.onKeyUp)`.
Is is at least possible to have `BehaviorSubject` extend `Observable` ? I know we can access it by calling `.stream`, but you could extend `Observable` and proxy the method calls to `.stream`. This way the API would be similar without changing the fact that you use `StreamController`.

**Comment by frankpepermans** [comment]
I'd say no, because people who are comfy with Dart streams would expect BehaviorSubject to act as a StreamController, but that's just my opinion of course!

I'd rather change it to a different name then, i.e. BehaviorControllor to have a better distinction.

Again just my 2 cents here

**Comment by brianegan** [comment]
> Is is at least possible to have BehaviorSubject extend Observable ?

Hrm, this is interesting! @frankpepermans, since we simply implement, but don't extend StreamController, could we have our cake and eat it too? Meaning, implement `StreamController` and extend `Observable`? I'm gonna give it a shot, as in other implementations, Subjects are in fact Observables and think we could honor that as well.

**Comment by brianegan** [comment]
Decided to fix the docs but decided not to extend Observable just yet as we plan on renaming the repo, and might change the naming for this just a bit.

**Comment by adaojunior** [comment]
Ok, keep me updated, I'll test the new version and give some feedback if necessary.
