### ISSUE TITLE
Implement distinctUntilChanged

### ISSUE THREAD

**Issue by adaojunior** [ReactiveX/rxdart#91]
Any plans to implement `distinctUntilChanged` ? see example on [rxjs](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-distinctUntilChanged)

**Comment by frankpepermans** [comment]
Dart has distinct, which is actually distinctUntilChanged, whereas the rxjs distinct is different and does not exist: https://api.dartlang.org/stable/1.19.1/dart-async/Stream/distinct.html

**Comment by frankpepermans** [comment]
see also: https://github.com/ReactiveX/rxdart/pull/92
