### ISSUE TITLE
Add 'if' operator

### ISSUE THREAD

**Issue by dotdotcommadot** [ReactiveX/rxdart#96]
Creating complex if / else structures is quite hard when your method chain is growing.
RxJS has a nice solution to it:
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/if.md

It takes a 'condition' method, a 'thenSource' and an 'elseSource' as parameters.

**Comment by brianegan** [comment]
Ah, interesting one. Not totally opposed to implementing it, but would love a bit more info. I'd rather not add an abstraction if a simple language construct would do. Could you provide an example where this is more useful than a normal function? 

Just as a comparison for discussion, here's what I'm thinking:

*Normal function*

```dart
Stream<int> ifStream(bool shouldRun) => shouldRun
    ? new Observable<int>.just(42)
    : new Observable<int>.empty();

Stream<int> elseStream(bool shouldRun) => shouldRun
    ? new Observable<int>.just(42)
    : new Observable<int>.just(56);

// Normal usage
ifStream(true).listen(print); // prints 42
ifStream(false).listen(print); // prints nothing

// Nice with flatmap
new Observable<bool>.just(false)
    .flatMap(elseStream)
    .listen(print); // prints 56
 ```

*If factory*

```dart
var shouldRun = true;

Stream<int> stream = new Observable.if(() => shouldRun, new Observable.just(42));

Stream<int> stream = new Observable.if(() => shouldRun, new Observable.just(42), new Observable.just(56));
```

**Comment by brianegan** [comment]
Since i haven't heard back for a while, gonna close this out for now. Please write back if you'd like us to consider re-opening it!
