### ISSUE TITLE
New Name: Ideas & Discussion!

### ISSUE THREAD

**Issue by brianegan** [ReactiveX/rxdart#98]
Given the feedback we heard in issue #95, we've decided it's best to go ahead and rename the repo! We should probably also create a Github org of a similar name.

Please submit each name as an individual comment and we can use 👍 to help guide us a bit with votes!

**Comment by brianegan** [comment]
From mattpodwysocki: "ReactiveDart"

Explanation:
I still like the idea of Rx + Dart which is to say that it could be analogous to ReactiveCocoa versus RxSwift, so say ReactiveDart being the name here.

**Comment by brianegan** [comment]
super_streams

Alliteration! And clearly conveys the `Stream` base

**Comment by frankpepermans** [comment]
I do like ReactiveDart so +1 from me.

A bit more fun inspired: a list of dart terminology right here http://dartbrokers.com/dart-terms.html

Shangai looks fun!
'Hitting a single, double and triple of the same number in the same throw'

Definitely sounds awesome from the description!

**Comment by Solido** [comment]
In the java world Rx is a library with roots in netflix RxJava and Reactive is a manifesto for app.
The full name is  io.reactivex » rxjava-reactive-streams.

RxDart-reactive-streams sounds great. I understand RxDart can be a set of libraries (Flutter, Mongo, YouNameIt) one of them is Reactive Streams.

**Comment by johnbland-wf** [comment]
Name: `RxStreams`

**Comment by johnbland-wf** [comment]
Name: `RxDartStreams`

**Comment by travissanderson-wf** [comment]
fwiw RxStreams is exactly what I was thinking too

**Comment by BugsBunnyBR** [comment]
StreamsX for additional operations and RxDart, that could use StreamsX as backbone but provide the Subject and Observable stuff.

**Comment by RollyPeres** [comment]
`StreamExtensions`
